{
    ":COPY_ALERT": "${0}:\n${1}\n\nLo vol\u00e8tz tractar malgrat tot ?",
    ":AUTO_patron": "Client",
    ":NO_PATRON_BARCODE": "Entratz lo c\u00f2de de barras d\u2019un client",
    ":RETURN_NO_RESPONSE": "No response from server when attempting return.",
    ":ADDRESS": "${0}\n${1}\n${2}, ${3} ${4}",
    ":AUTO_no_in_bresv": "Lo client a pas restituit cap de ressorsas u\u00e8i :",
    ":AUTO_ready_bresv": "Aquestas reservacions del client son pr\u00e8stas per \u00e8sser presas en liurason :",
    ":AUTO_ATTR_VALUE_pickup": "Prene en liurason",
    ":AUTO_resource": "Ressorsa",
    ":AUTO_in_bresv": "Lo client a restituit aquelas ressorsas u\u00e8i",
    ":RETURN_SUCCESS": "Restitucion capitada.",
    ":RESERVATIONS_ERROR": "Error de comunicacion amb lo servidor (demanda de reservacions) :",
    ":AUTO_out_bresv": "Lo client a sortit aquelas reservacions :",
    ":NO_SUCH_RETURNABLE_RESOURCE": "Pas cap de ressorsa tornabla d'aqueste mena.",
    ":AUTO_no_ready_bresv": "Lo client a pas cap de reservacions que son pr\u00e8stas per \u00e8sser presas en liurason pel moment.",
    ":AUTO_patron_barcode": "Entrar lo c\u00f2de de barras del client :",
    ":AUTO_return_h1": "Restitucion d\u2019articles reservats",
    ":AUTO_ATTR_VALUE_return": "Retorn",
    ":PICKUP_NO_RESPONSE": "No response from server when attempting pickup.",
    ":RETURN_ERROR": "Error de comunicacion amb lo servidor (temptativa de restitucion) :",
    ":PICKUP_ERROR": "Error de comunicacion amb lo servidor (temptativa de presa de liurason) :",
    ":RETURNABLE_RESOURCE_ERROR": "Error a la rec\u00e8rca d\u2019una ressorsa tornabla :",
    ":RESERVATIONS_NO_RESPONSE": "No response from server when asking for reservations.",
    ":AUTO_ATTR_VALUE_reset": "Escafar/ client nov\u00e8l",
    ":SELECT_SOMETHING": "Av\u00e8tz pas seleccionat cap de reservacion.",
    ":AUTO_barcode_type": "Restituit amb lo c\u00f2de de barras seguent :",
    ":AUTO_ATTR_VALUE_go": "Validar",
    ":NOTICE_CHANGE_OF_PATRON": "Note that the resource scanned was out on reservation to a different\npatron than the last resource you scanned.  If this is not\nexpected, stop to examine outstanding reservations for your patron\nor on the resource.",
    ":AUTO_no_out_bresv": "Lo client a pas mai de reservacions sortidas pel moment.",
    ":AUTO_h1": "Presa en liurason de reservacions"
}