{
    ":TFORMS_LABEL_SUM": "Sum",
    ":TEMPLATE_CONF_SELECT_CANCEL": "Select the value, or cancel:",
    ":TRANSFORMS_SUM": "Sum",
    ":TFORMS_LABEL_FIRST5": "First 5 characters (for US ZIP code)",
    ":TEMPLATE_CONF_DEFAULT": "Value ${0}:",
    ":TRANSFORMS_MIN": "Min",
    ":TRANSFORMS_DATE": "Date",
    ":OPERATORS_GT_EQUAL": "Greater than or equal to",
    ":FILTERS_LABEL_EQUALS": "Equals",
    ":TFORMS_LABEL_MIN": "Min",
    ":OPERATORS_LTE_TIME": "On or Before (Date/Time)",
    ":TFORMS_LABEL_DOY": "Day of Year",
    ":TRANSFORMS_AGE": "Age",
    ":FILTERS_LABEL_NE_ANY": "Does Not Equal Any",
    ":TFORMS_LABEL_DOW": "Day of Week",
    ":FILTERS_LABEL_LT_TIME": "Before (Date/Time)",
    ":OPERATORS_EQ_ANY": "Equals Any",
    ":FOLDER_WINDOW_COLNAME_ALL": "All",
    ":LINK_NULLABLE_NONE": "None",
    ":FILTERS_LABEL_GT_EQUAL": "Greater than or equal to",
    ":RPT_BUILDER_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?",
    ":TRANSFORMS_ROUND": "Round",
    ":TFORMS_LABEL_RAW_DATA": "Raw Data",
    ":OPERATORS_NULL_BLANK": "Is NULL or Blank",
    ":OPERATORS_EQUALS": "Equals",
    ":FOLDER_WINDOW_REPORT_OUTPUT": "Report Output: ${0}",
    ":TEMPLATE_CONF_CONFIRM_STATE": "Click OK for TRUE and Cancel for FALSE.",
    ":TFORMS_LABEL_AGE": "Age",
    ":TEMPLATE_CONF_EQUALS": "Equals",
    ":TRANSFORMS_DAY_NAME": "Day Name",
    ":REPORT_EDITOR_REPORT_FOLDERS": "Report Folders",
    ":FILTERS_LABEL_LSE_TIME": "On or Before (Date/Time)",
    ":FILTERS_LABEL_NOT_BETWEEN": "Not between",
    ":TRANSFORMS_MAX": "Max",
    ":TFORMS_LABEL_HOD": "Hour of day",
    ":TRANSFORMS_YEAR_TRUNC": "Year",
    ":TFORMS_LABEL_COUNT_DISTINCT": "Count Distinct",
    ":TFORMS_LABEL_DAY_NAME": "Day Name",
    ":TEMPLATE_CONF_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?",
    ":TEMPLATE_CONF_NO_MATCH": "Field does not match one of list (comma separated):",
    ":OPERATORS_LESS_THAN": "Less than",
    ":FOLDERS_TEMPLATES": "Templates",
    ":OPERATORS_NOT_BETWEEN": "Not between",
    ":TFORMS_LABEL_MAX": "Max",
    ":FILTERS_LABEL_GTE_TIME": "On or After (Date/Time)",
    ":TFORMS_LABEL_MONTH_TRUNC": "Year + Month",
    ":TRANSFORMS_DOM": "Day of Month",
    ":WIDGET_YEARS": "Year(s)",
    ":OPERATORS_GT_TIME": "After (Date/Time)",
    ":TFORMS_LABEL_QUARTERS_AGO": "Quarters ago",
    ":TRANSFORMS_DOW": "Day of Week",
    ":TEMPLATE_CONF_IN": "Field matches one of list (comma separated):",
    ":LINK_NULLABLE_DEFAULT": "Default",
    ":OPERATORS_NOT_NULL_BLANK": "Is not NULL or Blank",
    ":WIDGET_QUARTERS": "Quarter(s)",
    ":TRANSFORMS_DOY": "Day of Year",
    ":FILTERS_LABEL_NOT_IN": "Not in list",
    ":TRANSFORMS_QOY": "Quarter of Year",
    ":FOLDER_WINDOW_COLNAME_SELECT": "Select",
    ":OPERATORS_IS_NOT_NULL": "Is not NULL",
    ":TFORMS_LABEL_LAST": "Last Value",
    ":SOURCE_BROWSE_AGGREGATE": "Aggregate",
    ":TRANSFORMS_LAST": "Last Value",
    ":TFORMS_LABEL_WOY": "Week of Year",
    ":TEMPLATE_CONF_BARE": "Bare",
    ":FOLDER_WINDOW_CHANGE_FOLDERS": "Change Folders",
    ":FILTERS_LABEL_NULL_BLANK": "Is NULL or Blank",
    ":OPERATORS_NE_ANY": "Does Not Equal Any",
    ":REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Please provide an output folder",
    ":SOURCE_BROWSE_NON_AGGREGATE": "Non-Aggregate",
    ":TRANSFORMS_COUNT_DISTINCT": "Count Distinct",
    ":TRANSFORMS_FIRST": "First Value",
    ":TEMPLATE_CONF_SUCCESS_SAVE": "Template ${0} was successfully saved.",
    ":FILTERS_LABEL_GT_TIME": "After (Date/Time)",
    ":TRANSFORMS_QUARTERS_AGO": "Quarters ago",
    ":OPERATORS_LT_TIME": "Before (Date/Time)",
    ":TFORMS_LABEL_MONTH_NAME": "Month Name'",
    ":TRANSFORMS_INT": "Drop trailing decimals",
    ":OPERATORS_LT_EQUAL": "Less than or equal to",
    ":FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)",
    ":TRANSFORMS_MOY": "Month of Year",
    ":FILTERS_LABEL_LESS_THAN": "Less than",
    ":FOLDERS_TEMPLATE": "Template",
    ":FILTERS_LABEL_LIKE": "Contains Matching substring",
    ":TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string",
    ":OPERATORS_ILIKE": "Contains Matching substring (ignore case)",
    ":LINK_NULLABLE_RIGHT": "Parent",
    ":FILTERS_LABEL_LT_EQUAL": "Less than or equal to",
    ":TRANSFORMS_SUBSTRING": "Substring",
    ":TRANSFORMS_MONTH_NAME": "Month Name",
    ":OPERATORS_IN_LIST": "In list",
    ":TFORMS_LABEL_AVERAGE": "Average",
    ":TRANSFORMS_LOWER": "Lower case",
    ":FOLDERS_REPORT": "Report",
    ":TFORMS_LABEL_DOM": "Day of Month",
    ":FILTERS_LABEL_IN": "In list",
    ":TEMPLATE_CONF_RAW_DATA": "Raw Data",
    ":TFORMS_LABEL_DATE": "Date",
    ":TFORMS_LABEL_FIRST": "First Value",
    ":TFORMS_LABEL_INT": "Drop trailing decimals",
    ":TFORMS_LABEL_UPPER": "Upper case",
    ":TEMPLATE_CONF_TRUE": "True",
    ":TRANSFORMS_FIRST5": "First 5 characters (for US ZIP code)",
    ":TRANSFORMS_HOUR_TRUNC": "Hour",
    ":LINK_NULLABLE_LEFT": "Child",
    ":FILTERS_LABEL_NOT_NULL_BLANK": "Is not NULL or Blank",
    ":TRANSFORMS_MONTHS_AGO": "Months ago",
    ":TRANSFORMS_HOD": "Hour of day",
    ":SOURCE_SETUP_CORE_SOURCES": "Core Sources",
    ":REPORT_EDITOR_INVALID_DATE_ALERT": "invalid start date -  YYYY-MM-DD",
    ":FOLDER_WINDOW_SELECT_ITEM": "Please select an item from the list",
    ":TRANSFORMS_AVERAGE": "Average",
    ":TFORMS_LABEL_LOWER": "Lower case",
    ":OPERATORS_NOT_IN_LIST": "Not in list",
    ":TEMPLATE_CONF_NOT_IN": "Field does not match one of list (comma separated):",
    ":TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Change the field hint to:",
    ":OPERATORS_LIKE": "Contains Matching substring",
    ":FOLDER_WINDOW_COLNAME_NONE": "None",
    ":TFORMS_LABEL_MONTHS_AGO": "Months ago",
    ":TFORMS_LABEL_YEAR_TRUNC": "Year",
    ":TRANSFORMS_UPPER": "Upper case",
    ":OPERATORS_IS_NULL": "Is NULL",
    ":TFORMS_LABEL_COUNT": "Count",
    ":FILTERS_LABEL_NOT_NULL": "Is not NULL",
    ":WIDGET_MONTHS": "Month(s)",
    ":TRANSFORMS_BARE": "Raw Data",
    ":WIDGET_REAL_DATE": "Real Date",
    ":SOURCE_SETUP_ALL_AVAIL_SOURCES": "All Available Sources",
    ":OPERATORS_GTE_TIME": "On or After (Date/Time)",
    ":REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Please change the report name",
    ":FILTERS_LABEL_GREATER_THAN": "Greater than",
    ":TFORMS_LABEL_MOY": "Month of Year",
    ":FOLDERS_OUTPUT": "Output",
    ":REPORT_EDITOR_OUTPUT_FOLDERS": "Output Folders",
    ":TEMPLATE_CONF_CONFIRM_RESET": "You have already added the [${0}] field\nfrom the [${1}] source. Click OK if you\nwould like to reset this field.",
    ":TRANSFORMS_FIRST_WORD": "First contiguous non-space string",
    ":FILTERS_LABEL_NULL": "Is NULL",
    ":REPORT_EDITOR_ENTER_NAME_ALERT": "Please enter a report name",
    ":WIDGET_RELATIVE_DATE": "Relative Date",
    ":TEMPLATE_CONF_BOOLEAN_VALUE": "Boolean Value",
    ":TEMPLATE_CONF_BETWEEN": "Field value is between (comma separated):",
    ":SOURCE_SETUP_CONFIRM_EXIT": "You have started building a template!\n Selecting a new starting source will destroy the current template and start over.  Is this OK?",
    ":FOLDERS_REPORTS": "Reports",
    ":TFORMS_LABEL_HOUR_TRUNC": "Hour",
    ":FILTERS_LABEL_BETWEEN": "Between",
    ":REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Please provide a report folder",
    ":TEMPLATE_CONF_FALSE": "False",
    ":TRANSFORMS_WOY": "Week of Year",
    ":OPERATORS_GREATER_THAN": "Greater than",
    ":TEMPLATE_CONF_NOT_BETWEEN": "Field value is not between (comma separated):",
    ":TRANSFORMS_MONTH_TRUNC": "Year + Month",
    ":TRANSFORMS_COUNT": "Count",
    ":OPERATORS_BETWEEN": "Between",
    ":WIDGET_DAYS": "Day(s)",
    ":FILTERS_LABEL_EQ_ANY": "Equals Any",
    ":TFORMS_LABEL_QOY": "Quarter of Year",
    ":TFORMS_LABEL_ROUND": "Round",
    ":TEMPLATE_CONF_PROMPT_CHANGE": "Change the column header to: ${0}"
}