{
    ":CANCEL": "Anullar",
    ":MASTER_RECORD": "Principal",
    ":CONFIRM_DELETE_RESULT": "Deleted authority record # ${0}.",
    ":NONE_LINK": "[None]",
    ":LINKED_BIBS": "Number of linked bibliographic records: ${0}",
    ":AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    ":AUTHORITY_FIELDS": "Authority Fields (${0})",
    ":VIEW_MARC": "View MARC",
    ":CONFIRM_DELETE_PROMPT": "Confirm deletion of record # ${0}",
    ":MENU_MERGE": "Marcar per fusion",
    ":ACTIONS": "Accions",
    ":MENU_DELETE": "Suprimir",
    ":DELETE": "Suprimir",
    ":CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    ":MERGE_RESULT_SUCCESS": "Record merge is complete.",
    ":SAVE_RESULT_SUCCESS": "Record was saved.",
    ":SAVE": "Enregistrar",
    ":HIDE_MARC": "Hide MARC",
    ":CONFIRM_DELETE_TITLE": "Delete the authority record: \"${0}\"?",
    ":THESAURI": "Thesauri (${0})",
    ":MENU_EDIT": "Modificar",
    ":TARGET_RECORD": "Cibla"
}