{
    ":SELECT_A_BRSRC_THEN": "You have clicked 'Reserve Selected', but nothing is selected!\n\nYou must select a resource from the large box above.\n\n***  If resources that you would select are highlighted in RED, ***\nthese items are not available during the requested time; if\npossible, choose another resource or change the reservation time.",
    ":ACTOR_CARD_NOT_FOUND": "Patron barcode not found. Please try again.",
    ":NO_EXISTING_BRESV": "This user has no existing reservations at this time.",
    ":AUTO_bresv_grid_resource": "Resource",
    ":ON_FLY_NO_RESPONSE": "No response from server attempting to make item a bookable resource.",
    ":CXL_BRESV_FAILURE": "Error cancelling reservations; server silent.",
    ":AUTO_i_need_this_resource": "I need this resource...",
    ":AUTO_bresv_grid_type": "Type",
    ":HERE_ARE_EXISTING_BRESV": "Existing reservations for",
    ":BRSRC_RETRIVE_ERROR": "Error retrieving resource: ",
    ":AUTO_ATTR_VALUE_reserve_brsrc": "Reserve Selected",
    ":NO_BRA_RESULTS": "Couldn't retrieve booking resource attributes.",
    ":AUTO_ATTR_VALUE_button_edit_existing": "Edit selected",
    ":GET_BRESV_LIST_ERR": "Error while retrieving reservation list: ",
    ":CREATE_BRESV_OK_MISSING_TARGET_BLOCKED_BY_CIRC": "The desired reservation(s) are blocked by circulation(s) with the following due date(s):\n${0}",
    ":CREATE_BRESV_OK_MISSING_TARGET": "Created ${0} reservation(s), but ${1} of these could not target any resources.\n\nThis means that it won't be possible to fulfill some of these\nreservations until a suitable resource becomes available.",
    ":AUTO_ending_at": "and",
    ":GET_BRESV_LIST_NO_RESULT": "No results from server retrieving reservation list.",
    ":AUTO_arbitrary_resource": "Enter the barcode of a catalogued, bookable resource:",
    ":CXL_BRESV_SUCCESS": "Cancelled ${0} reservation(s)",
    ":AUTO_choose_a_brt": "Choose a Bookable Resource Type",
    ":AUTO_starting_at": "Between",
    ":NO_USABLE_BRSRC": "No reservable resources.  Adjust start and end time\nuntil a resource is available for reservation.",
    ":COULD_NOT_RETRIEVE_BRT_PASSED_IN": "Error retrieving booking resource type",
    ":CREATE_BRESV_SERVER_ERROR": "Server error trying to create reservation: ",
    ":AUTO_brt_noncat_only": "Show only non-catalogued bookable resource types",
    ":INVALID_TS_RANGE": "You must choose a valid start and end time for the reservation.",
    ":ON_FLY_ERROR": "Error attempting to make item a bookable resource:",
    ":CREATE_BRESV_OK_MISSING_TARGET_WILL_CANCEL": "Since the requested resource could not be targeted, this\nreservation will now be cancelled.",
    ":WHERES_THE_BARCODE": "Enter a patron's barcode to make a reservation.",
    ":CREATE_BRESV_SERVER_NO_RESPONSE": "No response from server after trying to create reservation.",
    ":ERROR_FETCHING_AOUS": "Could not retrieve organisational unit settings.\nThis is a non-fatal error, but you may wish to\ncontact your system administrator.",
    ":AUTO_bresv_grid_end_time": "End time",
    ":AUTO_email_notify": "Send email notification when resource is available for pickup.",
    ":AUTO_bresv_grid_start_time": "Start time",
    ":ANY": "ANY",
    ":OUTSTANDING_BRESV": "Outstanding reservations for patron",
    ":CREATE_BRESV_OK": "Created ${0} reservation(s)",
    ":NEED_EXACTLY_ONE_BRT_PASSED_IN": "Can't book multiple resource types at once",
    ":AUTO_ATTR_VALUE_next": "Next",
    ":CXL_BRESV_SELECT_SOMETHING": "You have not selected any reservations to cancel.",
    ":NO_TARG_DIV": "Could not find target div",
    ":AUTO_explain_bookable": "To reserve an item that is not yet registered as a bookable resource, find it in the catalogue or under <em>Display Item</em>, and select <em>Make Item Bookable</em> or <em>Book Item Now</em> there.",
    ":AUTO_with_these_attr": "With these attributes:",
    ":NO_BRT_RESULTS": "There are no bookable resource types registered.",
    ":CREATE_BRESV_LOCAL_ERROR": "Exception trying to create reservation: ",
    ":AUTO_ATTR_VALUE_button_cancel_existing": "Cancel selected",
    ":UNTARGETED": "None targeted",
    ":AUTO_ATTR_VALUE_reserve_brt": "Reserve Any",
    ":BRSRC_NOT_FOUND": "Could not locate that resource.",
    ":AUTO_or": "- Or -",
    ":GET_PATRON_NO_RESULT": "No server response after attempting to look up patron by barcode.",
    ":AUTO_pickup_lib_selector": "Choose the pickup library for this reservation:",
    ":CXL_BRESV_FAILURE2": "Error cancelling reservations:\n",
    ":AUTO_patron_barcode": "Reserve to patron barcode:"
}