{
    ":CANCEL": "Annuler",
    ":MASTER_RECORD": "Original",
    ":CONFIRM_DELETE_RESULT": "Notice d\u2019autorit\u00e9 # ${0. supprim\u00e9e.",
    ":NONE_LINK": "[Aucun]",
    ":LINKED_BIBS": "Nombre de fiches bibliographiques associ\u00e9es : ${0}",
    ":AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    ":AUTHORITY_FIELDS": "Authority Fields (${0})",
    ":VIEW_MARC": "Voir le MARC",
    ":CONFIRM_DELETE_PROMPT": "Confirmer la suppression de la notice # ${0}",
    ":MENU_MERGE": "Marquer pour fusion",
    ":ACTIONS": "Actions",
    ":MENU_DELETE": "Supprimer",
    ":DELETE": "Supprimer",
    ":CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    ":MERGE_RESULT_SUCCESS": "Fusion de la notice termin\u00e9e.",
    ":SAVE_RESULT_SUCCESS": "Notice sauvegard\u00e9e.",
    ":SAVE": "Sauvegarder",
    ":HIDE_MARC": "Cacher MARC",
    ":CONFIRM_DELETE_TITLE": "Supprimer la notice d\u2019autorit\u00e9 : \\\"${0}\\\"?",
    ":THESAURI": "Thesauri (${0})",
    ":MENU_EDIT": "Modifier",
    ":TARGET_RECORD": "Cible"
}