{
    ":DUPE_USERNAME": "Username is already in use",
    ":SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    ":ALL_CARDS_ACTIVE": "Active",
    ":REQUESTING_USER": "Account requested by ${0} ${1}",
    ":RESET_PASSWORD": "Generate Password",
    ":SHOW_REQUIRED": "Show Only Required Fields",
    ":DUPE_PATRON_EMAIL": "Found ${0} patron(s) with the same email address",
    ":HOLD_NOTIFY_SMS": "SMS: ",
    ":DUPE_PATRON_PHONE": "Found ${0} patron(s) with the same phone number",
    ":DUPE_PATRON_ADDR": "Found ${0} patron(s) with the same address",
    ":SHOW_ALL": "Show All Fields",
    ":VERIFY_PASSWORD": "Verify Password",
    ":EXAMPLE": "Example: ",
    ":USER_SETTINGS": "User Settings",
    ":ADDRESS_MAILING": "Mailing",
    ":INVALID_FORM": "Form is invalid.  Please edit and try again.",
    ":ADDRESS_BILLING": "Billing",
    ":PARENT_OR_GUARDIAN": "Parent/Guardian",
    ":SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    ":INVALIDATE": "Invalidate",
    ":UPDATE_EXPIRE_DATE": "Update Expire Date",
    ":DUPE_PATRON_NAME": "Found ${0} patron(s) with the same name",
    ":SEE_ALL": "See All",
    ":ADDRESS_PENDING": "This is a pending address: ",
    ":SAVE_CLONE": "Save &amp; Clone",
    ":ADDRESS_HEADER": "Address",
    ":DELETE": "Delete",
    ":STAT_CATS": "Statistical Categories",
    ":ALL_CARDS_BARCODE": "Barcode",
    ":HOLD_NOTIFY_EMAIL": "Email: ",
    ":ADDRESS_OWNED": "This address is owned by another user: ",
    ":HOLD_NOTIFY_PHONE": "Phone: ",
    ":REPLACE_BARCODE": "Replace Barcode",
    ":SHOW_SUGGESTED": "Show Suggested Fields",
    ":ADD": "Add",
    ":SAVE": "Save",
    ":REPLACED_ADDRESS": "Replaces address ${0}<br/> ${1} ${2}<br/> ${3}, ${4} ${5}",
    ":BARCODE_IN_USE": "Barcode is already in use",
    ":SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    ":DEFAULT_ADDRESS_TYPE": "MAILING",
    ":NEED_ADDRESS": "An address is required during registration.",
    ":SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    ":DUPE_PATRON_IDENT": "Found ${0} patron(s) with the same identification",
    ":ALL_CARDS_APPLY": "Apply Changes",
    ":ALL_CARDS_CLOSE": "Close",
    ":ADDRESS_APPROVE": "Approve Address",
    ":DELETE_ADDRESS": "Delete address ${0}?",
    ":ALL_CARDS_PRIMARY": "Primary",
    ":ADDRESS_NEW": "New Address"
}