{
    ":CLONE_SESSION_NAME": "Copia de ${0}",
    ":EDIT": "Editar",
    ":SELECT_MORE": "Haga clic aqu\u00ed para revisar todas las direcciones URL de sesi\u00f3n y / o seleccionar otras URLs para verificar",
    ":MARC_EDITOR_LINK": "Haga clic para abrir el Editor de MARC para este registro",
    ":NEED_UVUS": "Debe a\u00f1adir algunas combinaciones de etiquetas y subcampos.",
    ":REDIRECTING": "Cargando pr\u00f3xima interfaz ...",
    ":VERIFY_ALL": "Haga clic en 'Aceptar' para verificar todas las URL que pertenecen a esta sesi\u00f3n y combinar todos los t\u00e9rminos de b\u00fasqueda. Haga clic en \"Cancelar\" si el seleccionado, direcciones URL visibles son los \u00fanicos que desea verificar.",
    ":XPATH": "XPath",
    ":REREVIEW": "Abrir",
    ":REVIEW_ATTEMPT": "Revisar esta intento de verificaci\u00f3n",
    ":INTERFACE_SETUP": "Estableciendo interfaz ...",
    ":VERIFICATION_DIALOG": "Verificaci\u00f3n de URLs ...",
    ":CLONING": "Clonando sesi\u00f3n existente ...",
    ":CREATING": "Creando sesi\u00f3n ...",
    ":VERIFICATION_ATTEMPT_ID": "Verificaci\u00f3n intento ID: ${0}",
    ":SESSION_NAME": "Sesi\u00f3n '${0}'",
    ":CLONE_SESSION": "Clonar",
    ":EXTRACTING_URLS": "Extrayendo URLs ...",
    ":SAVING_TAGS": "Guardando etiqueta/ Selectores del subcampo ...",
    ":MARC_EDITOR_TITLE": "ID de registro #${0}",
    ":MARC_EDITOR_SAVE_RECORD": "Guardar Registro",
    ":NOTHING_SELECTED": "No hay filas seleccionadas, as\u00ed que no se efectuar\u00e1 ninguna acci\u00f3n",
    ":PERFORMING_SEARCH": "Realizando b\u00fasqueda ..."
}