{
    ":modifier_default": "S\u00e9lectionnez un modificateur",
    ":metabib": "Metarecord Search",
    ":site": "Site",
    ":depth": "Search Depth",
    ":new_modifier": "New Modifier",
    ":filter_default": "S\u00e9lectionnez un filtre",
    ":item_form": "Forme",
    ":during": "In Publication",
    ":more": "Plus...",
    ":filters": "Filtres",
    ":new_filter": "Nouveau filtre",
    ":advanced": "Advanced",
    ":faceted_searches": "Facettes",
    ":contains": "Contient",
    ":basic": "Basic",
    ":lit_form": "Forme litt\u00e9raire",
    ":format": "Type and Form",
    ":classed_searches": "Classed Searches",
    ":ascending": "Tri croissant",
    ":notcontains": "Ne contient pas",
    ":or": "OU",
    ":vr_format": "Videorecording Format",
    ":new_facet": "Nouvelle facette",
    ":bib_level": "Niveau bibliographique",
    ":item_type": "Type",
    ":remove": "Supprimer",
    ":staff": "Staff Search",
    ":modifiers": "Modificateurs",
    ":perform_search": "D\u00e9marrer !",
    ":audience": "Public",
    ":exact": "Exactly Matches",
    ":and": "ET",
    ":available": "Disponible",
    ":between": "Publi\u00e9s entre",
    ":before": "Publi\u00e9 avant",
    ":statuses": "Statuses",
    ":less": "...Moins",
    ":after": "Publi\u00e9 apr\u00e8s",
    ":sort": "Sort Axis",
    ":descending": "Tri d\u00e9croissant"
}