{
    ":TFORMS_LABEL_SUM": "Somme",
    ":TEMPLATE_CONF_SELECT_CANCEL": "S\u00e9lectionner la valeur, ou annuler :",
    ":TRANSFORMS_SUM": "Somme",
    ":TFORMS_LABEL_FIRST5": "Premiers 5 caract\u00e8res (pour code postal aux \u00c9tats-Unis)",
    ":TEMPLATE_CONF_DEFAULT": "Valeur ${0} :",
    ":TRANSFORMS_MIN": "Min",
    ":TRANSFORMS_DATE": "Date",
    ":OPERATORS_GT_EQUAL": "Sup\u00e9rieur ou \u00e9gal \u00e0",
    ":FILTERS_LABEL_EQUALS": "\u00c9gale \u00e0",
    ":TFORMS_LABEL_MIN": "Min",
    ":OPERATORS_LTE_TIME": "Jusqu'au (Date / heure)",
    ":TFORMS_LABEL_DOY": "Jour de l'ann\u00e9e",
    ":TRANSFORMS_AGE": "\u00c2ge",
    ":FILTERS_LABEL_NE_ANY": "Ne correspond \u00e0 aucun",
    ":TFORMS_LABEL_DOW": "Jour de la semaine",
    ":FILTERS_LABEL_LT_TIME": "Avant (Date/Heure)",
    ":OPERATORS_EQ_ANY": "\u00c9gale",
    ":FOLDER_WINDOW_COLNAME_ALL": "Tout",
    ":LINK_NULLABLE_NONE": "Aucun",
    ":FILTERS_LABEL_GT_EQUAL": "Sup\u00e9rieur ou \u00e9gal \u00e0",
    ":RPT_BUILDER_CONFIRM_SAVE": "Nom : ${0}\nDescription: ${1}\nEnregistrer le mod\u00e8le ?",
    ":TRANSFORMS_ROUND": "Arrondir",
    ":TFORMS_LABEL_RAW_DATA": "Donn\u00e9es brutes",
    ":OPERATORS_NULL_BLANK": "Est NULL ou vide",
    ":OPERATORS_EQUALS": "\u00c9gale \u00e0",
    ":FOLDER_WINDOW_REPORT_OUTPUT": "Sortie du rapport : ${0}",
    ":TEMPLATE_CONF_CONFIRM_STATE": "Cliquer OK pour VRAI et Annuler pour FAUX.",
    ":TFORMS_LABEL_AGE": "\u00c2ge",
    ":TEMPLATE_CONF_EQUALS": "\u00c9gale \u00e0",
    ":TRANSFORMS_DAY_NAME": "Nom du jour",
    ":REPORT_EDITOR_REPORT_FOLDERS": "R\u00e9pertoires de rapport",
    ":FILTERS_LABEL_LSE_TIME": "Jusqu'au (Date / heure)",
    ":FILTERS_LABEL_NOT_BETWEEN": "Pas entre",
    ":TRANSFORMS_MAX": "Max",
    ":TFORMS_LABEL_HOD": "Heure",
    ":TRANSFORMS_YEAR_TRUNC": "Ann\u00e9e",
    ":TFORMS_LABEL_COUNT_DISTINCT": "Calcul distinct",
    ":TFORMS_LABEL_DAY_NAME": "Nom du jour",
    ":TEMPLATE_CONF_CONFIRM_SAVE": "Nom : ${0}\nDescription: ${1}\nEnregistrer le mod\u00e8le ?",
    ":TEMPLATE_CONF_NO_MATCH": "Le champ ne correspond \u00e0 aucun \u00e9l\u00e9ment de la liste (s\u00e9par\u00e9 par virgule) :",
    ":OPERATORS_LESS_THAN": "Inf\u00e9rieur \u00e0",
    ":FOLDERS_TEMPLATES": "Mod\u00e8les",
    ":OPERATORS_NOT_BETWEEN": "Pas entre",
    ":TFORMS_LABEL_MAX": "Max",
    ":FILTERS_LABEL_GTE_TIME": "Le ou apr\u00e8s le (Date et heure)",
    ":TFORMS_LABEL_MONTH_TRUNC": "Ann\u00e9e + Mois",
    ":TRANSFORMS_DOM": "Jour du mois",
    ":WIDGET_YEARS": "Ann\u00e9e(s)",
    ":OPERATORS_GT_TIME": "Apr\u00e8s (Date/Heure)",
    ":TFORMS_LABEL_QUARTERS_AGO": "Des trimestres auparavant",
    ":TRANSFORMS_DOW": "Jour de la semaine",
    ":TEMPLATE_CONF_IN": "Champ correspond \u00e0 une entr\u00e9e de la liste (s\u00e9par\u00e9 par des virgules) :",
    ":LINK_NULLABLE_DEFAULT": "D\u00e9faut",
    ":OPERATORS_NOT_NULL_BLANK": "N'est pas NULL ou vide",
    ":WIDGET_QUARTERS": "Trimestre(s)",
    ":TRANSFORMS_DOY": "Jour de l'ann\u00e9e",
    ":FILTERS_LABEL_NOT_IN": "Pas dans la liste",
    ":TRANSFORMS_QOY": "Trimestre",
    ":FOLDER_WINDOW_COLNAME_SELECT": "S\u00e9lectionner",
    ":OPERATORS_IS_NOT_NULL": "N'est pas NULL",
    ":TFORMS_LABEL_LAST": "Derni\u00e8re valeur",
    ":SOURCE_BROWSE_AGGREGATE": "Regroupement",
    ":TRANSFORMS_LAST": "Derni\u00e8re valeur",
    ":TFORMS_LABEL_WOY": "Semaine de l'ann\u00e9e",
    ":TEMPLATE_CONF_BARE": "Vide",
    ":FOLDER_WINDOW_CHANGE_FOLDERS": "Changer les r\u00e9pertoires",
    ":FILTERS_LABEL_NULL_BLANK": "Est NULL ou vide",
    ":OPERATORS_NE_ANY": "Ne correspond \u00e0 aucun",
    ":REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Veuillez sp\u00e9cifier un r\u00e9pertoire de sortie",
    ":SOURCE_BROWSE_NON_AGGREGATE": "Non regroup\u00e9s",
    ":TRANSFORMS_COUNT_DISTINCT": "Calcul distinct",
    ":TRANSFORMS_FIRST": "Premi\u00e8re valeur",
    ":TEMPLATE_CONF_SUCCESS_SAVE": "Mod\u00e8le ${0} a \u00e9t\u00e9 enregistr\u00e9 avec succ\u00e8s.",
    ":FILTERS_LABEL_GT_TIME": "Apr\u00e8s (Date/Heure)",
    ":TRANSFORMS_QUARTERS_AGO": "Des trimestres auparavant",
    ":OPERATORS_LT_TIME": "Avant (Date/Heure)",
    ":TFORMS_LABEL_MONTH_NAME": "Nom du mois",
    ":TRANSFORMS_INT": "Supprimer les d\u00e9cimales",
    ":OPERATORS_LT_EQUAL": "Inf\u00e9rieur ou \u00e9gal \u00e0",
    ":FILTERS_LABEL_ILIKE": "Contient une sous-cha\u00eene correspondante (ignorer la casse)",
    ":TRANSFORMS_MOY": "Mois de l'ann\u00e9e",
    ":FILTERS_LABEL_LESS_THAN": "Inf\u00e9rieur \u00e0",
    ":FOLDERS_TEMPLATE": "Mod\u00e8le",
    ":FILTERS_LABEL_LIKE": "Contient des sous-cha\u00eenes correspondantes",
    ":TFORMS_LABEL_FIRST_WORD": "Premi\u00e8re cha\u00eene non-espace contig\u00fce",
    ":OPERATORS_ILIKE": "Contient une sous-cha\u00eene correspondante (ignorer la casse)",
    ":LINK_NULLABLE_RIGHT": "Parent",
    ":FILTERS_LABEL_LT_EQUAL": "Inf\u00e9rieur ou \u00e9gal \u00e0",
    ":TRANSFORMS_SUBSTRING": "Sous-cha\u00eene",
    ":TRANSFORMS_MONTH_NAME": "Nom du mois",
    ":OPERATORS_IN_LIST": "Dans la liste",
    ":TFORMS_LABEL_AVERAGE": "Moyenne",
    ":TRANSFORMS_LOWER": "Minuscules",
    ":FOLDERS_REPORT": "Rapport",
    ":TFORMS_LABEL_DOM": "Jour du mois",
    ":FILTERS_LABEL_IN": "Dans la liste",
    ":TEMPLATE_CONF_RAW_DATA": "Donn\u00e9es brutes",
    ":TFORMS_LABEL_DATE": "Date",
    ":TFORMS_LABEL_FIRST": "Premi\u00e8re valeur",
    ":TFORMS_LABEL_INT": "Supprimer les d\u00e9cimales",
    ":TFORMS_LABEL_UPPER": "Majuscules",
    ":TEMPLATE_CONF_TRUE": "Vrai",
    ":TRANSFORMS_FIRST5": "Premiers 5 caract\u00e8res (pour code postal aux \u00c9tats-Unis)",
    ":TRANSFORMS_HOUR_TRUNC": "Heure",
    ":LINK_NULLABLE_LEFT": "Enfant",
    ":FILTERS_LABEL_NOT_NULL_BLANK": "N'est pas NULL ou vide",
    ":TRANSFORMS_MONTHS_AGO": "Il y a plusieurs mois",
    ":TRANSFORMS_HOD": "Heure",
    ":SOURCE_SETUP_CORE_SOURCES": "Sources principales",
    ":REPORT_EDITOR_INVALID_DATE_ALERT": "Date initiale invalid - AAAA-MM-JJ",
    ":FOLDER_WINDOW_SELECT_ITEM": "Veuillez s\u00e9lectionner un \u00e9l\u00e9ment \u00e0 partir de la liste",
    ":TRANSFORMS_AVERAGE": "Moyenne",
    ":TFORMS_LABEL_LOWER": "Minuscules",
    ":OPERATORS_NOT_IN_LIST": "Pas dans la liste",
    ":TEMPLATE_CONF_NOT_IN": "Le champ ne correspond \u00e0 aucun \u00e9l\u00e9ment de la liste (s\u00e9par\u00e9 par virgule) :",
    ":TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Change the field hint to:",
    ":OPERATORS_LIKE": "Contient des sous-cha\u00eenes correspondantes",
    ":FOLDER_WINDOW_COLNAME_NONE": "Aucun",
    ":TFORMS_LABEL_MONTHS_AGO": "Il y a plusieurs mois",
    ":TFORMS_LABEL_YEAR_TRUNC": "Ann\u00e9e",
    ":TRANSFORMS_UPPER": "Majuscules",
    ":OPERATORS_IS_NULL": "Est NULL",
    ":TFORMS_LABEL_COUNT": "Comptage",
    ":FILTERS_LABEL_NOT_NULL": "N'est pas NULL",
    ":WIDGET_MONTHS": "Mois",
    ":TRANSFORMS_BARE": "Donn\u00e9es brutes",
    ":WIDGET_REAL_DATE": "Date r\u00e9elle",
    ":SOURCE_SETUP_ALL_AVAIL_SOURCES": "Tous les sources disponibles",
    ":OPERATORS_GTE_TIME": "Le ou apr\u00e8s le (Date et heure)",
    ":REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Please change the report name",
    ":FILTERS_LABEL_GREATER_THAN": "Sup\u00e9rieur \u00e0",
    ":TFORMS_LABEL_MOY": "Mois de l'ann\u00e9e",
    ":FOLDERS_OUTPUT": "Sortie",
    ":REPORT_EDITOR_OUTPUT_FOLDERS": "R\u00e9pertoires de sortie",
    ":TEMPLATE_CONF_CONFIRM_RESET": "Vous avez d\u00e9j\u00e0 ajout\u00e9 le champ [${0}] \nde la source. Cliquez sur ok si vous\nvoulez effacer ce champ.",
    ":TRANSFORMS_FIRST_WORD": "Premi\u00e8re cha\u00eene non-espace contig\u00fce",
    ":FILTERS_LABEL_NULL": "Est NULL",
    ":REPORT_EDITOR_ENTER_NAME_ALERT": "Veuillez entrer un nom de rapport",
    ":WIDGET_RELATIVE_DATE": "Date relative",
    ":TEMPLATE_CONF_BOOLEAN_VALUE": "Valeur bool\u00e9enne",
    ":TEMPLATE_CONF_BETWEEN": "Valeur du champ est entre (s\u00e9par\u00e9 par des virgules) :",
    ":SOURCE_SETUP_CONFIRM_EXIT": "Vous avez commenc\u00e9 \u00e0 construire un mod\u00e8le !\n Choisir une nouvelle source de d\u00e9marrage d\u00e9truira le mod\u00e8le en cours et recommencera. Est-ce bon ?",
    ":FOLDERS_REPORTS": "Rapports",
    ":TFORMS_LABEL_HOUR_TRUNC": "Heure",
    ":FILTERS_LABEL_BETWEEN": "Entre",
    ":REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Veuillez sp\u00e9cifier un r\u00e9pertoire de rapports",
    ":TEMPLATE_CONF_FALSE": "Faux",
    ":TRANSFORMS_WOY": "Semaine de l'ann\u00e9e",
    ":OPERATORS_GREATER_THAN": "Sup\u00e9rieur \u00e0",
    ":TEMPLATE_CONF_NOT_BETWEEN": "La valeur du champ n'est pas entre (s\u00e9paration par virgule) :",
    ":TRANSFORMS_MONTH_TRUNC": "Ann\u00e9e + Mois",
    ":TRANSFORMS_COUNT": "Comptage",
    ":OPERATORS_BETWEEN": "Entre",
    ":WIDGET_DAYS": "Jour(s)",
    ":FILTERS_LABEL_EQ_ANY": "\u00c9gale",
    ":TFORMS_LABEL_QOY": "Trimestre",
    ":TFORMS_LABEL_ROUND": "Arrondir",
    ":TEMPLATE_CONF_PROMPT_CHANGE": "Changer l'en-t\u00eate de la colonne \u00e0 : ${0}"
}