{
    ":CAPTURE_BRESV_DATES": "Tempo de reserva",
    ":AUTHOR": "Autor",
    ":PRINTED_BY": "Impresso por",
    ":TITLE": "T\u00ed\u00adtulo",
    ":CAPTURE_CAUSES_TRANSIT": "Este item est\u00e1 em tr\u00e2nsito!",
    ":AUTO_ATTR_VALUE_capture": "Capturar",
    ":CAPTURE_TRANSIT_SOURCE": "De:",
    ":BARCODE": "C\u00f3digo de Barras",
    ":TRANSIT": "*** TRANSITO ***",
    ":SUCCESS": "Captura sucedida",
    ":CAPTURE_BRESV_PICKUP_LIB": "Biblioteca de retirada",
    ":DURATION": "Reservado de",
    ":HERES_WHAT_WE_KNOW": "A informa\u00e7\u00e3o a seguir esta dispon\u00edvel sobre a falha de captura:",
    ":AUTO_resource_barcode": "Digite o c\u00f3digo de barras:",
    ":NEEDS_ROUTED_TO": "Esta item precisa ser encaminhado para",
    ":RESERVATION_SHELF": "PRATELEIRA DE RESERVA",
    ":PRINT": "<u>I</u>mprimir",
    ":CAPTURE_INFO": "Capturar Informa\u00e7\u00e3o",
    ":NO_PAYLOAD": "N\u00f3s n\u00e3o recebemos mais informa\u00e7\u00f5es do servidor sobre essa tentativa de captura.",
    ":CAPTURE_TRANSIT_DEST": "Para:",
    ":SLIP_DATE": "Data do comprovante",
    ":AT": "em",
    ":CAPTURED_NOTHING": "N\u00e3o capturou nada.",
    ":RESERVED": "Reservado para patrono",
    ":CAPTURE_BRESV_BRSRC": "C\u00f3digo de barras de recursos:",
    ":PRINT_ACCESSKEY": "P",
    ":AUTO_capture_heading": "Captar Recursos Reservados",
    ":REQUEST": "Hora da solicita\u00e7\u00e3o",
    ":UNKNOWN_PROBLEM": "Um problema desconhecido ocorreu durante a tentativa de captura.",
    ":FAILURE": "Captura falhou",
    ":AUTO_pickup_lib_selector": "Biblioteca de retirada"
}