{
    ":SELECT_A_BRSRC_THEN": "You have clicked 'Reserve Selected', but nothing is selected!\n\nYou must select a resource from the large box above.\n\n***  If resources that you would select are highlighted in RED, ***\nthese items are not available during the requested time; if\npossible, choose another resource or change the reservation time.",
    ":ACTOR_CARD_NOT_FOUND": "C\u00f3digo de barra do cliente n\u00e3o encontrado. Por favor, tente novamente.",
    ":NO_EXISTING_BRESV": "Esse usu\u00e1rio n\u00e3o tem reservas existentes neste momento.",
    ":AUTO_bresv_grid_resource": "Recurso",
    ":ON_FLY_NO_RESPONSE": "No response from server attempting to make item a bookable resource.",
    ":CXL_BRESV_FAILURE": "Error canceling reservations; server silent.",
    ":AUTO_i_need_this_resource": "Eu preciso desse recurso...",
    ":AUTO_bresv_grid_type": "Type",
    ":HERE_ARE_EXISTING_BRESV": "Existing reservations for",
    ":BRSRC_RETRIVE_ERROR": "Erro ao recuperar recurso: ",
    ":AUTO_ATTR_VALUE_reserve_brsrc": "Reserva selecionada",
    ":NO_BRA_RESULTS": "Couldn't retrieve booking resource attributes.",
    ":AUTO_ATTR_VALUE_button_edit_existing": "Edit selected",
    ":GET_BRESV_LIST_ERR": "Erro ao recuperar lista de reservas: ",
    ":CREATE_BRESV_OK_MISSING_TARGET_BLOCKED_BY_CIRC": "The desired reservation(s) are blocked by circulation(s) with the following due date(s):\n${0}",
    ":CREATE_BRESV_OK_MISSING_TARGET": "Created ${0} reservation(s), but ${1} of these could not target any resources.\n\nThis means that it won't be possible to fulfill some of these\nreservations until a suitable resource becomes available.",
    ":AUTO_ending_at": "e",
    ":GET_BRESV_LIST_NO_RESULT": "No results from server retrieving reservation list.",
    ":AUTO_arbitrary_resource": "Enter the barcode of a cataloged, bookable resource:",
    ":CXL_BRESV_SUCCESS": "Criada(s) ${0} reserva(s)",
    ":AUTO_choose_a_brt": "Choose a Bookable Resource Type",
    ":AUTO_starting_at": "Entre",
    ":NO_USABLE_BRSRC": "N\u00e3o h\u00e1 recursos para reserva. Ajuste a hora de in\u00edcio de de t\u00e9rmino\nat\u00e9 que um recurso esteja dispon\u00edvel para reserva.",
    ":COULD_NOT_RETRIEVE_BRT_PASSED_IN": "Error retrieving booking resource type",
    ":CREATE_BRESV_SERVER_ERROR": "Erro do servidor ao tentar criar reserva: ",
    ":AUTO_brt_noncat_only": "Show only non-cataloged bookable resource types",
    ":INVALID_TS_RANGE": "You must choose a valid start and end time for the reservation.",
    ":ON_FLY_ERROR": "Error attempting to make item a bookable resource:",
    ":CREATE_BRESV_OK_MISSING_TARGET_WILL_CANCEL": "Since the requested resource could not be targeted, this\nreservation will now be canceled.",
    ":WHERES_THE_BARCODE": "Enter a patron's barcode to make a reservation.",
    ":CREATE_BRESV_SERVER_NO_RESPONSE": "Nenhuma resposta do servidor depois de tentar criar reserva.",
    ":ERROR_FETCHING_AOUS": "N\u00e3o foi poss\u00edvel recuperar as configura\u00e7\u00f5es da unidade organizacional.\nEste n\u00e3o \u00e9 um erro fatal, mas voc\u00ea pode entrar\nem contado administrador do sistema.",
    ":AUTO_bresv_grid_end_time": "End time",
    ":AUTO_email_notify": "Send email notification when resource is available for pickup.",
    ":AUTO_bresv_grid_start_time": "Start time",
    ":ANY": "ANY",
    ":OUTSTANDING_BRESV": "Outstanding reservations for patron",
    ":CREATE_BRESV_OK": "Criada(s) ${0} reserva(s)",
    ":NEED_EXACTLY_ONE_BRT_PASSED_IN": "N\u00e3o \u00e9 poss\u00edvel reservar m\u00faltiplos tipos de recursos de uma s\u00f3 vez",
    ":AUTO_ATTR_VALUE_next": "Pr\u00f3ximo",
    ":CXL_BRESV_SELECT_SOMETHING": "Voc\u00ea n\u00e3o selecionou nenhuma reserva para cancelar.",
    ":NO_TARG_DIV": "Could not find target div",
    ":AUTO_explain_bookable": "To reserve an item that is not yet registered as a bookable resource, find it in the catalog or under <em>Display Item</em>, and select <em>Make Item Bookable</em> or <em>Book Item Now</em> there.",
    ":AUTO_with_these_attr": "Com esses atributos:",
    ":NO_BRT_RESULTS": "There are no bookable resource types registered.",
    ":CREATE_BRESV_LOCAL_ERROR": "Exce\u00e7\u00e3o ao tentar criar reserva: ",
    ":AUTO_ATTR_VALUE_button_cancel_existing": "Cancel selected",
    ":UNTARGETED": "None targeted",
    ":AUTO_ATTR_VALUE_reserve_brt": "Reserve Any",
    ":BRSRC_NOT_FOUND": "N\u00e3o foi poss\u00edvel localizar esse recurso.",
    ":AUTO_or": "- Or -",
    ":GET_PATRON_NO_RESULT": "No server response after attempting to look up patron by barcode.",
    ":AUTO_pickup_lib_selector": "Choose the pickup library for this reservation:",
    ":CXL_BRESV_FAILURE2": "Erro ao cancelar reservas:\n",
    ":AUTO_patron_barcode": "Reservar para c\u00f3digo de barra do cliente."
}