{
    ":TFORMS_LABEL_SUM": "Summa",
    ":TEMPLATE_CONF_SELECT_CANCEL": "Valitse arvo tai peruuta:",
    ":TRANSFORMS_SUM": "Summa",
    ":TFORMS_LABEL_FIRST5": "Ensimm\u00e4iset 5 merkki\u00e4 (postinumerosta)",
    ":TEMPLATE_CONF_DEFAULT": "Arvo ${0}:",
    ":TRANSFORMS_MIN": "V\u00e4h.",
    ":TRANSFORMS_DATE": "P\u00e4iv\u00e4ys",
    ":OPERATORS_GT_EQUAL": "Suurempi tai yht\u00e4 suuri kuin",
    ":FILTERS_LABEL_EQUALS": "Vastaa",
    ":TFORMS_LABEL_MIN": "V\u00e4h.",
    ":OPERATORS_LTE_TIME": "Ajankohtana tai ennen (p\u00e4iv\u00e4ys/aika)",
    ":TFORMS_LABEL_DOY": "Vuoden p\u00e4iv\u00e4",
    ":TRANSFORMS_AGE": "Ik\u00e4",
    ":FILTERS_LABEL_NE_ANY": "Ei vastaa yht\u00e4\u00e4n",
    ":TFORMS_LABEL_DOW": "Viikonp\u00e4iv\u00e4",
    ":FILTERS_LABEL_LT_TIME": "Ennen (p\u00e4iv\u00e4ys/aika)",
    ":OPERATORS_EQ_ANY": "Vastaa mit\u00e4 tahansa",
    ":FOLDER_WINDOW_COLNAME_ALL": "Kaikki",
    ":LINK_NULLABLE_NONE": "Ei yht\u00e4\u00e4n",
    ":FILTERS_LABEL_GT_EQUAL": "Suurempi tai yht\u00e4 suuri kuin",
    ":RPT_BUILDER_CONFIRM_SAVE": "Nimi : ${0}\nKuvaus: ${1}\nTallennetaanko pohja?",
    ":TRANSFORMS_ROUND": "Py\u00f6rist\u00e4",
    ":TFORMS_LABEL_RAW_DATA": "Raakadata",
    ":OPERATORS_NULL_BLANK": "On NULL tai tyhj\u00e4",
    ":OPERATORS_EQUALS": "Vastaa",
    ":FOLDER_WINDOW_REPORT_OUTPUT": "Raportin tuloste: ${0}",
    ":TEMPLATE_CONF_CONFIRM_STATE": "Napsauta OK = TOSI tai Peruuta = EP\u00c4TOSI.",
    ":TFORMS_LABEL_AGE": "Ik\u00e4",
    ":TEMPLATE_CONF_EQUALS": "Vastaa",
    ":TRANSFORMS_DAY_NAME": "P\u00e4iv\u00e4n nimi",
    ":REPORT_EDITOR_REPORT_FOLDERS": "Raporttikansiot",
    ":FILTERS_LABEL_LSE_TIME": "Ajankohtana tai ennen (p\u00e4iv\u00e4ys/aika)",
    ":FILTERS_LABEL_NOT_BETWEEN": "Ei v\u00e4lill\u00e4",
    ":TRANSFORMS_MAX": "Enint.",
    ":TFORMS_LABEL_HOD": "P\u00e4iv\u00e4n tunti",
    ":TRANSFORMS_YEAR_TRUNC": "Vuosi",
    ":TFORMS_LABEL_COUNT_DISTINCT": "Laske erikseen",
    ":TFORMS_LABEL_DAY_NAME": "P\u00e4iv\u00e4n nimi",
    ":TEMPLATE_CONF_CONFIRM_SAVE": "Nimi : ${0}\nKuvaus: ${1}\nTallennetaanko pohja?",
    ":TEMPLATE_CONF_NO_MATCH": "Kentt\u00e4 ei vastaa arvoa luettelossa (pilkulla erotettu):",
    ":OPERATORS_LESS_THAN": "Pienempi kuin",
    ":FOLDERS_TEMPLATES": "Raporttipohjat",
    ":OPERATORS_NOT_BETWEEN": "Ei v\u00e4lill\u00e4",
    ":TFORMS_LABEL_MAX": "Enint.",
    ":FILTERS_LABEL_GTE_TIME": "Ajankohtana tai j\u00e4lkeen (p\u00e4iv\u00e4ys/aika)",
    ":TFORMS_LABEL_MONTH_TRUNC": "Vuosi + kuukausi",
    ":TRANSFORMS_DOM": "Kuukauden p\u00e4iv\u00e4",
    ":WIDGET_YEARS": "Vuosi/vuodet",
    ":OPERATORS_GT_TIME": "J\u00e4lkeen (p\u00e4iv\u00e4ys/aika)",
    ":TFORMS_LABEL_QUARTERS_AGO": "Nelj\u00e4nnest\u00e4 sitten",
    ":TRANSFORMS_DOW": "Viikonp\u00e4iv\u00e4",
    ":TEMPLATE_CONF_IN": "Kentt\u00e4 vastaa yht\u00e4 arvoa luettelosta (pilkuilla erotettu):",
    ":LINK_NULLABLE_DEFAULT": "Oletus",
    ":OPERATORS_NOT_NULL_BLANK": "Ei ole NULL tai tyhj\u00e4",
    ":WIDGET_QUARTERS": "Nelj\u00e4nnes/nelj\u00e4nnekset",
    ":TRANSFORMS_DOY": "Vuoden p\u00e4iv\u00e4",
    ":FILTERS_LABEL_NOT_IN": "Ei luettelossa",
    ":TRANSFORMS_QOY": "Vuosinelj\u00e4nnes",
    ":FOLDER_WINDOW_COLNAME_SELECT": "Valitse",
    ":OPERATORS_IS_NOT_NULL": "Ei ole NULL",
    ":TFORMS_LABEL_LAST": "Viimeisin arvo",
    ":SOURCE_BROWSE_AGGREGATE": "Yhteenkokouma",
    ":TRANSFORMS_LAST": "Viimeisin arvo",
    ":TFORMS_LABEL_WOY": "Vuoden viikko",
    ":TEMPLATE_CONF_BARE": "Pelkk\u00e4",
    ":FOLDER_WINDOW_CHANGE_FOLDERS": "Muuta kansioita",
    ":FILTERS_LABEL_NULL_BLANK": "On NULL tai tyhj\u00e4",
    ":OPERATORS_NE_ANY": "Ei vastaa yht\u00e4\u00e4n",
    ":REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Sy\u00f6t\u00e4 tulostekansio",
    ":SOURCE_BROWSE_NON_AGGREGATE": "Ei-yhteenkokouma",
    ":TRANSFORMS_COUNT_DISTINCT": "Laske erikseen",
    ":TRANSFORMS_FIRST": "Ensimm\u00e4inen arvo",
    ":TEMPLATE_CONF_SUCCESS_SAVE": "Raporttipohja ${0} tallennettiin onnistuneesti.",
    ":FILTERS_LABEL_GT_TIME": "J\u00e4lkeen (p\u00e4iv\u00e4ys/aika)",
    ":TRANSFORMS_QUARTERS_AGO": "Nelj\u00e4nnest\u00e4 sitten",
    ":OPERATORS_LT_TIME": "Ennen (p\u00e4iv\u00e4ys/aika)",
    ":TFORMS_LABEL_MONTH_NAME": "Kuukauden nimi'",
    ":TRANSFORMS_INT": "J\u00e4t\u00e4 ylim\u00e4\u00e4r\u00e4iset desimaalit pois",
    ":OPERATORS_LT_EQUAL": "Pienempi tai yht\u00e4 suuri kuin",
    ":FILTERS_LABEL_ILIKE": "Sis\u00e4lt\u00e4\u00e4 osuvan alijonon (kirjainten koosta riippumatta)",
    ":TRANSFORMS_MOY": "Vuoden kuukausi",
    ":FILTERS_LABEL_LESS_THAN": "Pienempi kuin",
    ":FOLDERS_TEMPLATE": "Raporttipohja",
    ":FILTERS_LABEL_LIKE": "Sis\u00e4lt\u00e4\u00e4 osuvan alijonon",
    ":TFORMS_LABEL_FIRST_WORD": "Ensimm\u00e4inen yht\u00e4jaksoinen merkkijono ilman v\u00e4lily\u00f6ntej\u00e4",
    ":OPERATORS_ILIKE": "Sis\u00e4lt\u00e4\u00e4 osuvan alijonon (kirjainten koosta riippumatta)",
    ":LINK_NULLABLE_RIGHT": "Emoelementti",
    ":FILTERS_LABEL_LT_EQUAL": "Pienempi tai yht\u00e4 suuri kuin",
    ":TRANSFORMS_SUBSTRING": "Alijono",
    ":TRANSFORMS_MONTH_NAME": "Kuukauden nimi",
    ":OPERATORS_IN_LIST": "Luettelossa",
    ":TFORMS_LABEL_AVERAGE": "Keskim\u00e4\u00e4rin",
    ":TRANSFORMS_LOWER": "Pienet kirjaimet",
    ":FOLDERS_REPORT": "Raportti",
    ":TFORMS_LABEL_DOM": "Kuukauden p\u00e4iv\u00e4",
    ":FILTERS_LABEL_IN": "Luettelossa",
    ":TEMPLATE_CONF_RAW_DATA": "Raakadata",
    ":TFORMS_LABEL_DATE": "P\u00e4iv\u00e4ys",
    ":TFORMS_LABEL_FIRST": "Ensimm\u00e4inen arvo",
    ":TFORMS_LABEL_INT": "J\u00e4t\u00e4 ylim\u00e4\u00e4r\u00e4iset desimaalit pois",
    ":TFORMS_LABEL_UPPER": "Isot kirjaimet",
    ":TEMPLATE_CONF_TRUE": "Tosi",
    ":TRANSFORMS_FIRST5": "Ensimm\u00e4iset 5 merkki\u00e4 (postinumerosta)",
    ":TRANSFORMS_HOUR_TRUNC": "Tunti",
    ":LINK_NULLABLE_LEFT": "Lapsi",
    ":FILTERS_LABEL_NOT_NULL_BLANK": "Ei ole NULL tai tyhj\u00e4",
    ":TRANSFORMS_MONTHS_AGO": "Kuukautta sitten",
    ":TRANSFORMS_HOD": "P\u00e4iv\u00e4n tunti",
    ":SOURCE_SETUP_CORE_SOURCES": "Ydinl\u00e4hteet",
    ":REPORT_EDITOR_INVALID_DATE_ALERT": "virheellinen aloitusp\u00e4iv\u00e4 - VVVV-KK-PP",
    ":FOLDER_WINDOW_SELECT_ITEM": "Valitse kohde luettelosta",
    ":TRANSFORMS_AVERAGE": "Keskim\u00e4\u00e4rin",
    ":TFORMS_LABEL_LOWER": "Pienet kirjaimet",
    ":OPERATORS_NOT_IN_LIST": "Ei luettelossa",
    ":TEMPLATE_CONF_NOT_IN": "Kentt\u00e4 ei vastaa arvoa luettelossa (pilkulla erotettu):",
    ":TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Change the field hint to:",
    ":OPERATORS_LIKE": "Sis\u00e4lt\u00e4\u00e4 osuvan alijonon",
    ":FOLDER_WINDOW_COLNAME_NONE": "Ei yht\u00e4\u00e4n",
    ":TFORMS_LABEL_MONTHS_AGO": "Kuukautta sitten",
    ":TFORMS_LABEL_YEAR_TRUNC": "Vuosi",
    ":TRANSFORMS_UPPER": "Isot kirjaimet",
    ":OPERATORS_IS_NULL": "On NULL",
    ":TFORMS_LABEL_COUNT": "Lukum\u00e4\u00e4r\u00e4",
    ":FILTERS_LABEL_NOT_NULL": "Ei ole NULL",
    ":WIDGET_MONTHS": "Kuukausi/kuukaudet",
    ":TRANSFORMS_BARE": "Raakadata",
    ":WIDGET_REAL_DATE": "Todellinen p\u00e4iv\u00e4ys",
    ":SOURCE_SETUP_ALL_AVAIL_SOURCES": "Kaikki lainattavissa olevat l\u00e4hteet",
    ":OPERATORS_GTE_TIME": "Ajankohtana tai j\u00e4lkeen (p\u00e4iv\u00e4ys/aika)",
    ":REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Please change the report name",
    ":FILTERS_LABEL_GREATER_THAN": "Suurempi kuin",
    ":TFORMS_LABEL_MOY": "Vuoden kuukausi",
    ":FOLDERS_OUTPUT": "Tuloste",
    ":REPORT_EDITOR_OUTPUT_FOLDERS": "Tulostekansiot",
    ":TEMPLATE_CONF_CONFIRM_RESET": "Olet jo lis\u00e4nnyt kent\u00e4n [${0}]\n l\u00e4hteest\u00e4 [${1}]. Napsauta OK, jos\nhaluat tyhjent\u00e4\u00e4 kent\u00e4n.",
    ":TRANSFORMS_FIRST_WORD": "Ensimm\u00e4inen yht\u00e4jaksoinen merkkijono ilman v\u00e4lily\u00f6ntej\u00e4",
    ":FILTERS_LABEL_NULL": "On NULL",
    ":REPORT_EDITOR_ENTER_NAME_ALERT": "Sy\u00f6t\u00e4 raportin nimi",
    ":WIDGET_RELATIVE_DATE": "Suhteellinen p\u00e4iv\u00e4",
    ":TEMPLATE_CONF_BOOLEAN_VALUE": "Boolean-arvo",
    ":TEMPLATE_CONF_BETWEEN": "Kent\u00e4n arvo on v\u00e4lill\u00e4 (pilkuilla erotettu):",
    ":SOURCE_SETUP_CONFIRM_EXIT": "Olet aloittanut raporttipohjan luomisen!\nUudet aloitusl\u00e4hteen valinta tuhoaa nykyisen raporttipohjan ja aloittaa alusta. OK?",
    ":FOLDERS_REPORTS": "Raportit",
    ":TFORMS_LABEL_HOUR_TRUNC": "Tunti",
    ":FILTERS_LABEL_BETWEEN": "V\u00e4lill\u00e4",
    ":REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Sy\u00f6t\u00e4 raporttikansio",
    ":TEMPLATE_CONF_FALSE": "Ep\u00e4tosi",
    ":TRANSFORMS_WOY": "Vuoden viikko",
    ":OPERATORS_GREATER_THAN": "Suurempi kuin",
    ":TEMPLATE_CONF_NOT_BETWEEN": "Kent\u00e4n arvo ei ole v\u00e4lill\u00e4 (pilkuilla erotettu):",
    ":TRANSFORMS_MONTH_TRUNC": "Vuosi + kuukausi",
    ":TRANSFORMS_COUNT": "Lukum\u00e4\u00e4r\u00e4",
    ":OPERATORS_BETWEEN": "V\u00e4lill\u00e4",
    ":WIDGET_DAYS": "P\u00e4iv\u00e4(\u00e4)",
    ":FILTERS_LABEL_EQ_ANY": "Vastaa mit\u00e4 tahansa",
    ":TFORMS_LABEL_QOY": "Vuosinelj\u00e4nnes",
    ":TFORMS_LABEL_ROUND": "Py\u00f6rist\u00e4",
    ":TEMPLATE_CONF_PROMPT_CHANGE": "Muuta sarakkeen otsikoksi: ${0}"
}