{
    ":OPERATOR_GTE": "es mayor que o igual a",
    ":ADD_ROW": "A\u00f1adir fila",
    ":DEFAULT_DIALOG_TITLE": "Filtrar los resultados",
    ":CANCEL": "Cancelar",
    ":OPERATOR_EQ": "es",
    ":OPERATOR_GT": "es mayor que",
    ":OPERATOR_IN": "est\u00e1 en el conjunto",
    ":NEED_NAME": "Debe introducir un nombre para los filtros guardados",
    ":OPERATOR_NOT_LIKE": "no es como",
    ":OPERATOR_LTE": "es menos que o igual a",
    ":CHOOSE_FILTER_TO_LOAD": "Elegir conjuntos de filtros para cargar",
    ":EMPTY_CASE_COMPACT": "A\u00f1adir filas para filtrar resultados",
    ":OPERATOR_IS_NULL": "es nulo",
    ":OPERATOR_LIKE": "es como",
    ":OPERATOR_BETWEEN": "est\u00e1 entre",
    ":EMPTY_CASE": "A\u00f1adir filas para filtrar los resultados, o simplemente haga clic en aplicar para ver los resultados sin filtrar.",
    ":APPLY": "Aplicar",
    ":OPERATOR_NOT_IN": "no est\u00e1 en el conjunto",
    ":OPERATOR_IS_NOT_NULL": "no es nulo",
    ":LOAD_FILTERS": "Filtros de carga",
    ":NAME_SAVED_FILTER_SET": "Introduzca un nombre para el conjunto de filtro guardado:",
    ":OPERATOR_NE": "no es",
    ":EMPTY_LIST": "No se puede compilar busqueda de filtro.",
    ":SAVE_FILTERS": "Guardar Filtros",
    ":OPERATOR_NOT_BETWEEN": "no est\u00e1 entre",
    ":OPERATOR_LT": "Es menos que"
}