{
    ":modifier_default": "- Seleccionar un Modificador -",
    ":metabib": "Metarecord Buscar",
    ":site": "Sitio",
    ":depth": "Profundidad de b\u00fasqueda",
    ":new_modifier": "Nuevo Modificador",
    ":filter_default": "- Seleccione un filtro -",
    ":item_form": "Forma",
    ":during": "En publicaci\u00f3n",
    ":more": "M\u00e1s..",
    ":filters": "Filtros",
    ":new_filter": "Nuevo filtro",
    ":advanced": "Avanzado",
    ":faceted_searches": "Facetas",
    ":contains": "Contiene",
    ":basic": "B\u00e1sico",
    ":lit_form": "Forma literaria",
    ":format": "Tipo y Forma",
    ":classed_searches": "B\u00fasquedas clasificadas",
    ":ascending": "Ordenaci\u00f3n Ascendente",
    ":notcontains": "No contiene",
    ":or": "O",
    ":vr_format": "Formato de Grabaci\u00f3n de video",
    ":new_facet": "Nueva Faceta",
    ":bib_level": "Nivel bibliogr\u00e1fico",
    ":item_type": "Tipo",
    ":remove": "Eliminar",
    ":staff": "B\u00fasqueda de personal",
    ":modifiers": "Modificadores",
    ":perform_search": "\u00a1Adelante!",
    ":audience": "Audiencia",
    ":exact": "Coincidencias exactas",
    ":and": "Y",
    ":available": "Disponible",
    ":between": "Publicado entre",
    ":before": "Publicado anteriormente",
    ":statuses": "Estatus",
    ":less": "...Menos",
    ":after": "Publicado posteriormente",
    ":sort": "Ordenar Axis",
    ":descending": "Ordenaci\u00f3n Descendente"
}