{
    ":CLONE_SESSION_NAME": "Copy of ${0}",
    ":EDIT": "Edit",
    ":SELECT_MORE": "Click here to review all session URLs and/or select other URLs to verify",
    ":MARC_EDITOR_LINK": "Click to open MARC Editor for this record",
    ":NEED_UVUS": "You must add some tag and subfield combinations.",
    ":REDIRECTING": "Loading next interface ...",
    ":VERIFY_ALL": "Click 'OK' to verify ALL the URLs that belong to this session and match all your search terms.  Click 'Cancel' if the selected, visible URLs are the only ones you want verified.",
    ":XPATH": "XPath",
    ":REREVIEW": "Open",
    ":REVIEW_ATTEMPT": "Review this verification attempt",
    ":INTERFACE_SETUP": "Aray\u00fcz ayarlan\u0131yor ...",
    ":VERIFICATION_DIALOG": "Verifying URLs ...",
    ":CLONING": "Cloning existing session ...",
    ":CREATING": "Creating session ...",
    ":VERIFICATION_ATTEMPT_ID": "Verification attempt ID: ${0}",
    ":SESSION_NAME": "Session '${0}'",
    ":CLONE_SESSION": "Clone",
    ":EXTRACTING_URLS": "Extracting URLs ...",
    ":SAVING_TAGS": "Saving tag/subfield selectors ...",
    ":MARC_EDITOR_TITLE": "Record ID #${0}",
    ":MARC_EDITOR_SAVE_RECORD": "Save Record",
    ":NOTHING_SELECTED": "Hi\u00e7bir sat\u0131r se\u00e7ilmez, bu nedenle herhangi bir i\u015flem yap\u0131lmaz.",
    ":PERFORMING_SEARCH": "Performing search ..."
}