{
    ":OPERATOR_GTE": "on enemm\u00e4n tai yht\u00e4 paljon kuin",
    ":ADD_ROW": "Lis\u00e4\u00e4 rivi",
    ":DEFAULT_DIALOG_TITLE": "Suodantulokset",
    ":CANCEL": "Peruuta",
    ":OPERATOR_EQ": "on",
    ":OPERATOR_GT": "on enemm\u00e4n kuin",
    ":OPERATOR_IN": "kuuluu joukkoon",
    ":NEED_NAME": "Sinun t\u00e4ytyy antaa suodatinjoukolle nimi.",
    ":OPERATOR_NOT_LIKE": "ei ole kuten",
    ":OPERATOR_LTE": "on v\u00e4hemm\u00e4n tai yht\u00e4 paljon kuin",
    ":CHOOSE_FILTER_TO_LOAD": "Valitse ladattava suodatinjoukko",
    ":EMPTY_CASE_COMPACT": "Lis\u00e4\u00e4 rivej\u00e4 suodatintuloksiin.",
    ":OPERATOR_IS_NULL": "on m\u00e4\u00e4ritt\u00e4m\u00e4t\u00f6n",
    ":OPERATOR_LIKE": "on kuten",
    ":OPERATOR_BETWEEN": "on v\u00e4lill\u00e4",
    ":EMPTY_CASE": "Lis\u00e4\u00e4 rivej\u00e4 suodatintuloksiin, tai valitse Suodata n\u00e4hd\u00e4ksesi kaikki tulokset.",
    ":APPLY": "Suodata",
    ":OPERATOR_NOT_IN": "ei kuulu joukkoon",
    ":OPERATOR_IS_NOT_NULL": "ei ole m\u00e4\u00e4ritt\u00e4m\u00e4t\u00f6n",
    ":LOAD_FILTERS": "Lataa suodatin",
    ":NAME_SAVED_FILTER_SET": "Sy\u00f6t\u00e4 tallennetun suodattimen nimi:",
    ":OPERATOR_NE": "ei ole",
    ":EMPTY_LIST": "Suodattimen luonti ep\u00e4onnistui. Tyhj\u00e4 lista ei ole sallitty.",
    ":SAVE_FILTERS": "Tallenna suodatin",
    ":OPERATOR_NOT_BETWEEN": "ei ole v\u00e4lill\u00e4",
    ":OPERATOR_LT": "on v\u00e4hemm\u00e4n kuin"
}