{
    ":modifier_default": "-- Valitse m\u00e4\u00e4rite --",
    ":metabib": "Haku metatietueesta",
    ":site": "Sivusto",
    ":depth": "Hakusyvyys",
    ":new_modifier": "Uusi m\u00e4\u00e4rite",
    ":filter_default": "-- Valitse suodatin --",
    ":item_form": "Muoto",
    ":during": "Julkaistu",
    ":more": "Lis\u00e4\u00e4...",
    ":filters": "Suodattimet",
    ":new_filter": "Uusi suodatin",
    ":advanced": "Edistynyt",
    ":faceted_searches": "Fasetit",
    ":contains": "Sis\u00e4lt\u00e4\u00e4",
    ":basic": "Perus",
    ":lit_form": "Kirjallisuudenlaji",
    ":format": "Tyyppi ja muoto",
    ":classed_searches": "Luokitetut haut",
    ":ascending": "Nouseva lajittelu",
    ":notcontains": "Ei sis\u00e4ll\u00e4",
    ":or": "TAI",
    ":vr_format": "Videotallenteen muoto",
    ":new_facet": "Uusi fasetti",
    ":bib_level": "Bibliografinen taso",
    ":item_type": "Tyyppi",
    ":remove": "Poista",
    ":staff": "Virkailijahaku",
    ":modifiers": "M\u00e4\u00e4ritteet",
    ":perform_search": "Hae!",
    ":audience": "Yleis\u00f6",
    ":exact": "Vastaa t\u00e4ysin",
    ":and": "JA",
    ":available": "Lainattavissa",
    ":between": "Julkaistu v\u00e4lisen\u00e4 aikana",
    ":before": "Julkaistu ennen",
    ":statuses": "Statukset",
    ":less": "...V\u00e4hemm\u00e4n",
    ":after": "Julkaistu j\u00e4lkeen",
    ":sort": "Lajitteluakseli",
    ":descending": "Laskeva lajittelu"
}