{
    ":FUND_XFER_SAME_SOURCE_AND_DEST": "Siirto ei onnistu. L\u00e4hde- ja kohdetili on sama.",
    ":FUND_XFER_CONFIRM": "Haluatko varmasti suorittaa t\u00e4m\u00e4n siirron?",
    ":CANCEL": "Peruuta",
    ":PO_WARNING_NO_BLOCK_ACTIVATION": "Kyll\u00e4; sidottu summa ${0} (${1}) ylitt\u00e4isi varoitusrajan.",
    ":FINALIZE_PO": "Finalize this blanket PO?\nThis will disencumber all blanket charges and mark the PO as received",
    ":NO_FIND_INVOICE": "Laskua ei l\u00f6ydy.\nHuomaa, ett\u00e4 Laskun #-kentt\u00e4 erottelee isot ja pienet kirjaimet.",
    ":PO_ACTIVATING": "Activating purchase order...",
    ":EXPORT_EMPTY_LIST": "M\u00e4\u00e4ritteen '${0}' arvoja ei l\u00f6ytynyt.",
    ":NO_PO_RESULTS": "Ei tuloksia",
    ":LI_EXISTING_COPIES": "There are ${0} existing copies for this bibliographic record at this location",
    ":DELETE_LI_COPIES_CONFIRM": "Taulukosta poistetaan viimeiset ${0} kappaletta. Jatketaanko?",
    ":XUL_RECORD_DETAIL_PAGE": "Tietueen tiedot",
    ":COULD_NOT_CREATE_MAPPING": "Tilin merkitseminen avainsanalla ep\u00e4onnistui.",
    ":FUND_LIST_ROLLOVER_SUMMARY_FUNDS": "${1} varoja karttunut valituista toimipisteist\u00e4 tilivuonna ${0}",
    ":OUT_OF_COPIES": "Olet ottanut jakelukaavat k\u00e4ytt\u00f6\u00f6n kaikille niteille.",
    ":CANCELED": "Peruttu",
    ":VENDOR_PUBLIC": "MYYJ\u00c4 JULKINEN",
    ":ROLLBACK_PO_RECEIVE_CONFIRM": "Kaikkien t\u00e4m\u00e4n tilauksen niteiden vastaanotto perutaan.\n\nJatketaanko?",
    ":PO_NAME_OPTIONAL": "${0} (optional)",
    ":CREATE_PO_INVALID": "Tilauksessa on oltava tilaaja ja toimittaja.",
    ":INVOICE_IDENT_COLLIDE": "Jollain toisella laskulla on sama toimittaja ja laskutunnus.",
    ":PREPAYMENT_REQUIRED_REMINDER": "T\u00e4m\u00e4 tilaus edellytt\u00e4\u00e4 ennakkomaksua. Haluatko varmasti aktivoida sen?",
    ":SELECT_SEARCH_FIELD": "Valitse hakukentt\u00e4",
    ":LID_CANCEL_CONFIRM": "Haluatko VARMASTI perua t\u00e4m\u00e4n niteen?",
    ":PO_HEADING_ERROR": "Virtuaalisen yhdistetyn tilauksen luomisessa ilmeni odottamaton ongelma",
    ":CONFIRM_SPLIT_PO": "Haluatko varmasti jakaa kaikki t\u00e4ss\u00e4 tilauksessa\nolevat nimekkeet erillisiksi tilauksiksi?",
    ":ONE_LI_ATTR_SEARCH_AT_A_TIME": "Et voi sy\u00f6tt\u00e4\u00e4 ominaisuushakua ja etsi\u00e4 samanaikaisesti ladattua termitiedostoa.",
    ":DUPE_PO_NAME_MSG": "This name is already in use by another PO",
    ":PO_COULD_ACTIVATE": "Kyll\u00e4.",
    ":YES": "Kyll\u00e4",
    ":CREATE_PO_ASSETS_CONFIRM": "T\u00e4m\u00e4 luo kirjastoj\u00e4rjestelm\u00e4\u00e4n bibliografisen tietueen sek\u00e4 hyllypaikka- ja nidetietueen t\u00e4lle tilaukselle.\n\nJatketaanko?",
    ":NEW_INVOICE": "Uusi lasku",
    ":PO_CANCEL_CONFIRM": "Haluatko VARMASTI perua t\u00e4m\u00e4n tilauksen?",
    ":LI_CREATING_ASSETS": "Creating bib, call number, and copy records...",
    ":PO_CHECKING": "[Hetkinen...]",
    ":CANCEL_REASON": "Perumissyy",
    ":ACQ_SEARCH_CLASS_ABBR_jub": "LI",
    ":PO_ALREADY_ACTIVATED": "Aktivoitu",
    ":UR_FILTER_USER": "Sy\u00f6t\u00e4 asiakastunnus (tai j\u00e4t\u00e4 tyhj\u00e4ksi, jos et halua k\u00e4ytt\u00e4\u00e4 suodatinta):",
    ":DUPE_PO_NAME_LINK": "View PO",
    ":NO_LI_TO_CLAIM": "Et ole valinnut yht\u00e4\u00e4n nimikett\u00e4 reklamointia varten.",
    ":ACTIVATE_DEBITS_ACCRUED_PROCESSED": "Debits Encumbered: ${0}",
    ":UR_CANCEL_CONFIRM": "Haluatko VARMASTI perua t\u00e4m\u00e4n hankintatoiveen?",
    ":FUND_LIST_ROLLOVER_SUMMARY": "Varojen karttuminen ja aiemmin k\u00e4ytt\u00e4m\u00e4tt\u00f6mien varojen yhteenveto tilivuodelle ${0}",
    ":PRINT": "Tulosta",
    ":UNRECEIVE_LID": "Haluatko varmasti merkit\u00e4 t\u00e4m\u00e4n kopion EI-vastaanotetuksi?",
    ":LI_ATTR_SEARCH_CHOOSE_FILE": "Valitse tiedosto hakuehdoilla",
    ":INVOICE_CONFIRM_PRORATE": "Jaetaanko maksut suhteellisesti?\n\nMy\u00f6hemm\u00e4t muutokset laskuun, jotka vaikuttaisivat suhteellisesti jaettuihin osuuksiin, tulee ratkaista manuaalisesti.",
    ":INVOICE_ITEM_PO_DETAILS": "<b>${0}</b><br/><a href='${1}/acq/po/view/${2}'>PO #${3} ${4}</a><br/>Yhteenlaskettu kustannusarvio: $${5}",
    ":COULD_NOT_DELETE_MAPPING": "Avainsanan poistaminen tilist\u00e4 ep\u00e4onnistui.",
    ":ACTIVATE_LI_PROCESSED": "Lineitems Processed: ${0}",
    ":ITS_YOU": "Sin\u00e4",
    ":ACTIVATE_COPIES_PROCESSED": "Real Copies Processed: ${0}",
    ":LIBRARY_INITIATED": "Kirjaston aloitteesta",
    ":DFA_TIP": "<strong>K\u00e4ytt\u00f6\u00f6nottaja</strong>: ${0}<br /><strong>Aika</strong>: ${1}",
    ":PO_STOP_BLOCKS_ACTIVATION": "Ei; sidottu summa ${0} (${1}) ylitt\u00e4isi pys\u00e4ytysrajan.",
    ":FUND_LIST_ROLLOVER_SUMMARY_ROLLOVER_AMOUNT": "<b>$${1}</b> k\u00e4ytt\u00e4m\u00e4t\u00f6nt\u00e4 rahaa siirretty tilivuodelle ${0} valittuihin toimipisteisiin",
    ":ADD_LI_TO_PO_BAD_LI_STATE": "Valittu nimeke ei ole sellaisessa tilassa, ett\u00e4 sen voisi lis\u00e4t\u00e4 tilaukseen",
    ":INVOICE_NUMBER": "Lasku #${0}",
    ":EXPORT_SAVE_DIALOG_TITLE": "Tallenna kenttien arvot tiedostoon",
    ":INVOICE_EXTRA_COPIES": "Yrit\u00e4t luoda laskua <b>${0}</b> useammasta kappaleesta kuin alkuper\u00e4isess\u00e4 tilauksessa. <br/><br/>Jos haluat lis\u00e4t\u00e4 n\u00e4m\u00e4 nimekkeet alkuper\u00e4iseen tilaukseen, valitse tili ja sen j\u00e4lkeen 'Lis\u00e4\u00e4 uusia nimekkeit\u00e4' alla. <br/>Kun olet tallentanut laskun, voit muokata ja tuoda uudet kappaleet nimikkeiden tietosivulta.",
    ":UNNAMED": "Nime\u00e4m\u00e4t\u00f6n",
    ":VENDOR_SAYS_PREPAY_NEEDED": "Tietueiden mukaan valittu myyj\u00e4 vaatii ennakkomaksun.\nJatketaanko t\u00e4t\u00e4 tilausta ilman vaadittua ennakkomaksua siit\u00e4 huolimatta?",
    ":LI_CANCEL_CONFIRM": "Haluatko VARMASTI perua t\u00e4m\u00e4n nimikkeen?",
    ":RESET_FORMULAE": "Nollaa kaavat",
    ":DEL_LI_FROM_PO": "Nide on jo tilattu! Jos poistat sen nyt, sill\u00e4 ei ole mit\u00e4\u00e4n vaikutusta myyj\u00e4lle l\u00e4hteneeseen tilaukseen. Jos poistat niteen, j\u00e4rjestelm\u00e4\u00e4n tallentuvat tilauksen tiedot eiv\u00e4t v\u00e4ltt\u00e4m\u00e4tt\u00e4 vastaa todellisuutta. Haluatko varmasti tehd\u00e4 t\u00e4m\u00e4n?",
    ":EXPORT_SHORT_LIST": "Kaikilla valituilla niteill\u00e4 ei ollut m\u00e4\u00e4ritett\u00e4 '${0}'.\nValitse OK, jos haluat tallentaa arvot, jotka l\u00f6ydettiin.",
    ":ACQ_SEARCH_CLASS_ABBR_acqlia": "LIA",
    ":CONFIRM_FUNDS_AT_STOP": "Yhden tai useamman tilin saldo on alle pys\u00e4ytysrajan.\nEt ehk\u00e4 pysty aktivoimaan n\u00e4it\u00e4 tilauksia.\nJatketaanko?",
    ":EXPLAIN_DFA_MGMT": "Poistetaanko t\u00e4m\u00e4n jakelukaavan k\u00e4yt\u00f6n tietue?",
    ":ACQ_SEARCH_CLASS_ABBR_acqlid": "LID",
    ":APPLY": "Hyv\u00e4ksy",
    ":ACTIVATE_VQBR_PROCESSED": "Vandelay Records Processed: ${0}",
    ":ACTIVATE_BIBS_PROCESSED": "Bib Records Merged/Imported: ${0}",
    ":DFA_NOT_ALL": "Kaikkia jakelukaavojen sovelluksia ei voitu tallentaa.",
    ":FUND_NOT_YET_LOADED": "Tili\u00e4 ei viel\u00e4 ole ladattu. Yrit\u00e4 tulla my\u00f6hemmin takaisin t\u00e4h\u00e4n n\u00e4ytt\u00f6\u00f6n.",
    ":NO_RESULTS": "Ei tuloksia.",
    ":NO_LI_GENERAL": "Et ole valinnut yht\u00e4\u00e4n (sopivaa) tilausnimekett\u00e4.",
    ":NUM_CLAIMS_EXISTING": "Reklamoidut (yhteens\u00e4 ${0})",
    ":COPIES_TO_RECEIVE": "Vastaanotettavien niteiden lukum\u00e4\u00e4r\u00e4: ",
    ":LI_ATTR_SEARCH_TOO_LARGE": "Tiedosto on liian suuri t\u00e4lle toiminnolle.",
    ":NOT_RECVD": "Ei vastaanotettu",
    ":ACTIVATE_LID_PROCESSED": "ACQ Copies Processed: ${0}",
    ":NO_LI_TO_UPDATE": "Et ole valinnut yht\u00e4\u00e4n tilausnimekett\u00e4 p\u00e4ivityst\u00e4 varten.",
    ":LI_FORMAT_ERROR": "Muotoiltujen nimiketietojen hakemisessa ilmeni odottamaton virhe.",
    ":NO": "Ei",
    ":UR_FILTER_LINEITEM": "Sy\u00f6t\u00e4 nimikkeen tunnus (tai j\u00e4t\u00e4 tyhj\u00e4ksi, jos et halua k\u00e4ytt\u00e4\u00e4 suodatinta):",
    ":RECVD": "Vastaanotettu",
    ":JUST_NOW": "Juuri nyt",
    ":LOAD_TERMS_FIRST": "Et voi hakea tietueita, ennen kuin olet ladannut CSV-tiedoston,\njoka sis\u00e4lt\u00e4\u00e4 bibliografiset tunnukset ensimm\u00e4isess\u00e4 sarakkeessa.",
    ":VENDOR_SAYS_PREPAY_NOT_NEEDED": "Tietueiden mukaan valittu myyj\u00e4 ei v\u00e4ltt\u00e4m\u00e4tt\u00e4 vaadi ennakkomaksua.\nVaaditaanko ennakkomaksu siit\u00e4 huolimatta?",
    ":PO_ACTIVATED_ON": "Aktivoitu ${0}",
    ":CONFIRM_DELETE_MAPPING": "Haluatko varmasti poistaa t\u00e4m\u00e4n avainsanan t\u00e4st\u00e4 tilist\u00e4?",
    ":UNRECEIVE_LI": "Haluatko varmasti merkit\u00e4 t\u00e4m\u00e4n nimikkeen EI-vastaanotetuksi?",
    ":LI_BATCH_UPDATE": "Tilausnimekkeiden er\u00e4p\u00e4ivitys",
    ":INVOICE_ITEM_PO_LABEL": "<b>${0}</b><br/><a href='${1}/acq/po/view/${2}'>PO #${3} ${4}</a><br/>Yhteenlaskettu kustannusarvio: $${5}",
    ":CONFIRM_LI_ALERT": "Nimikkeelle \"${0}\" on asetettu huomautus:\n\n${1}\n${2}\n${3}\nValitse OK, jos haluat huomioida t\u00e4m\u00e4n varoituksen.",
    ":CHANGE_CLAIM_POLICY": "Muuta reklamaatiok\u00e4yt\u00e4nt\u00f6j\u00e4",
    ":PO_FUND_WARNING_CONFIRM": "Oletko varma? Huomasitko varoituksen: Sidottu summa ylitt\u00e4\u00e4 saldon?",
    ":INVOICE_CONFIRM_ENTRY_DETACH": "Poistetaanko laskulta $${0} veloitus niteest\u00e4 '${1}, ${2} [${3}]?",
    ":ADD_LI_TO_PO_BAD_PO_STATE": "Valittu tilaus on jo aktivoitu",
    ":INVOICE_COPY_COUNT_INFO": "T\u00e4ll\u00e4 laskulla olevista niteist\u00e4 vastaanotettu: ${0} / ${1}.",
    ":LINEITEM_SUMMARY": "<div class='acq-lineitem-summary'><a href='${19}?focus_li=${10}&source=${22}'>${0}</a>, by ${1} (${2})</div>\n<div class='acq-lineitem-summary-extra'>\n${3} Ordered, ${4} Received, ${7} Invoiced, ${8} Claimed, ${9} Cancelled, ${23} Delayed</div>\n<div class='acq-lineitem-summary-extra'>Estimated $${6}, Encumbered $${16}, Paid $${17}</div>\n<div class='acq-lineitem-summary-extra'>\n# ${10} <a style='padding-right: 10px;' class='hidden${20}'  href='${11}/acq/po/view/${12}?focus_li=${10}&source=${22}'>&#x2318; ${13} ${18}</a>\n<a style='padding-right: 10px;' class='hidden${21}' href='${11}/acq/picklist/view/${14}?focus_li=${10}&source=${22}'>&#x2756; ${15}</a></div>",
    ":CONFIRM_FUNDS_AT_WARNING": "Yhden tai useamman valitun tilin saldo on alle varoitusrajan.\nJatketaanko?",
    ":ROLLBACK_LI_RECEIVE_CONFIRM": "Kaikkien t\u00e4m\u00e4n tilauksen nimekkeiden vastaanotto perutaan.\n\nJatketaanko?",
    ":ACQ_SEARCH_CLASS_ABBR_acqpo": "PO",
    ":ACQ_SEARCH_CLASS_ABBR_acqpl": "SL",
    ":INVOICE_CONFIRM_ITEM_DELETE": "Poistetaanko t\u00e4m\u00e4 $${0} '${1}' veloitus laskulta?",
    ":ALERT_UNSELECTED": "Sinun on valittava varoituskoodi.",
    ":NO_LID_TO_CLAIM": "Et ole valinnut yhdenk\u00e4\u00e4n tilausnimekkeen tietoja reklamointia varten.",
    ":INVOICES": "Laskut",
    ":INVOICE_ITEM_DETAILS": "${0} <br/> ${1} <br/> ${2}. <br/> Arvioitu hinta: $${3}. <br/> Nimikkeen ID: ${4} <br/> Tilaus: ${5} <br/> Tilausp\u00e4iv\u00e4: ${6}",
    ":ACQ_SEARCH_CLASS_ABBR_acqinv": "I",
    ":SELECT_AN_LI_ATTRIBUTE": "Sinun on valittava LI-m\u00e4\u00e4rite."
}