{
    ":DUPE_USERNAME": "Nom d\u2019utilizaire ja utilizat",
    ":SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    ":ALL_CARDS_ACTIVE": "Activa",
    ":REQUESTING_USER": "Account requested by ${0} ${1}",
    ":RESET_PASSWORD": "Generate Password",
    ":SHOW_REQUIRED": "Far veire sonque los camps obligat\u00f2ris",
    ":DUPE_PATRON_EMAIL": "Trobat ${0} client(s) amb lo meteis corri\u00e8l",
    ":HOLD_NOTIFY_SMS": "SMS : ",
    ":DUPE_PATRON_PHONE": "Trobat ${0} client(s) amb lo meteis num\u00e8ro de telef\u00f2n",
    ":DUPE_PATRON_ADDR": "Trobat ${0} client(s) amb la meteissa adre\u00e7a",
    ":SHOW_ALL": "Far veire totes los camps",
    ":VERIFY_PASSWORD": "Verificar lo senhal",
    ":EXAMPLE": "Exemple : ",
    ":USER_SETTINGS": "Param\u00e8tres de l'utilizaire",
    ":ADDRESS_MAILING": "Mandad\u00eds",
    ":INVALID_FORM": "Lo formulari es pas valid. Merc\u00e9 de lo modificar e ensajatz tornarmai.",
    ":ADDRESS_BILLING": "Facturacion",
    ":PARENT_OR_GUARDIAN": "Parent/tutor",
    ":SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    ":INVALIDATE": "Invalidar",
    ":UPDATE_EXPIRE_DATE": "Update Expire Date",
    ":DUPE_PATRON_NAME": "Trobat ${0} client(s) amb lo meteis nom",
    ":SEE_ALL": "Veire tot",
    ":ADDRESS_PENDING": "S\u2019ag\u00eds d\u2019una adre\u00e7a en esp\u00e8ra : ",
    ":SAVE_CLONE": "Salvar &amp; Clonar",
    ":ADDRESS_HEADER": "Adre\u00e7a",
    ":DELETE": "Delete",
    ":STAT_CATS": "Categorias estatisticas",
    ":ALL_CARDS_BARCODE": "C\u00f2de de barras",
    ":HOLD_NOTIFY_EMAIL": "Adre\u00e7a electronica\u00a0: ",
    ":ADDRESS_OWNED": "Aquesta adre\u00e7a aparten a un autre utilizaire : ",
    ":HOLD_NOTIFY_PHONE": "Telef\u00f2n\u00a0: ",
    ":REPLACE_BARCODE": "Rempla\u00e7ar lo c\u00f2de de barras",
    ":SHOW_SUGGESTED": "Far veire los camps suggerits",
    ":ADD": "Add",
    ":SAVE": "Enregistrar",
    ":REPLACED_ADDRESS": "<div>Rempla\u00e7a l'adre\u00e7a <b>${0}</b><br/> ${1} ${2}<br/> ${3}, ${4} ${5}</div>",
    ":BARCODE_IN_USE": "Lo c\u00f2de de barras es ja utilizat",
    ":SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    ":DEFAULT_ADDRESS_TYPE": "DIFUSION",
    ":NEED_ADDRESS": "Una adre\u00e7a es requesida al moment de l'inscripcion.",
    ":SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    ":DUPE_PATRON_IDENT": "Trobat ${0} client(s) amb la meteissa identificacion",
    ":ALL_CARDS_APPLY": "Aplicar los cambiaments",
    ":ALL_CARDS_CLOSE": "Tampar",
    ":ADDRESS_APPROVE": "Adre\u00e7a aprovada",
    ":DELETE_ADDRESS": "Suprimir l'adre\u00e7a ${0}?",
    ":ALL_CARDS_PRIMARY": "Principal",
    ":ADDRESS_NEW": "Adre\u00e7a nov\u00e8la"
}