{
    ":DUPE_USERNAME": "Benutzername wird bereits benutzt",
    ":SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    ":ALL_CARDS_ACTIVE": "Active",
    ":REQUESTING_USER": "Account requested by ${0} ${1}",
    ":RESET_PASSWORD": "Generate Password",
    ":SHOW_REQUIRED": "Nur ben\u00f6tigte Felder anzeigen",
    ":DUPE_PATRON_EMAIL": "${0} Bibliotheksnutzer mit der selben E-Mail Adresse gefunden",
    ":HOLD_NOTIFY_SMS": "SMS: ",
    ":DUPE_PATRON_PHONE": "${0} Bibliotheksnutzer mit der selben Telefonnummer gefunden.",
    ":DUPE_PATRON_ADDR": "${0} Bibliotheksnutzer mit der selben Adresse gefunden",
    ":SHOW_ALL": "Alle Felder anzeigen",
    ":VERIFY_PASSWORD": "Passwort best\u00e4tigen",
    ":EXAMPLE": "Beispiel: ",
    ":USER_SETTINGS": "Benutzereinstellungen",
    ":ADDRESS_MAILING": "Mailversand",
    ":INVALID_FORM": "Form ist ung\u00fcltigt. Bitte bearbeiten und neu versuchen.",
    ":ADDRESS_BILLING": "Abrechnung",
    ":PARENT_OR_GUARDIAN": "Eltern/Vormund",
    ":SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    ":INVALIDATE": "Invalidate",
    ":UPDATE_EXPIRE_DATE": "Update Expire Date",
    ":DUPE_PATRON_NAME": "${0} Bibliotheksnutzer mit dem selben Namen gefunden",
    ":SEE_ALL": "Alles anzeigen",
    ":ADDRESS_PENDING": "Dies ist eine unbest\u00e4tigte Adresse: ",
    ":SAVE_CLONE": "Speichere &amp; Klon",
    ":ADDRESS_HEADER": "Adresse",
    ":DELETE": "Delete",
    ":STAT_CATS": "Statistische Kategorien",
    ":ALL_CARDS_BARCODE": "Barcode",
    ":HOLD_NOTIFY_EMAIL": "Email: ",
    ":ADDRESS_OWNED": "Diese Adresse geh\u00f6rt einem anderen Benutzer: ",
    ":HOLD_NOTIFY_PHONE": "Phone: ",
    ":REPLACE_BARCODE": "Barcode ersetzen",
    ":SHOW_SUGGESTED": "Vorgeschlagene Felder anzeigen",
    ":ADD": "Add",
    ":SAVE": "Speichern",
    ":REPLACED_ADDRESS": "<div>Ersetzt Adresse <b>${0}</b><br/> ${1} ${2}<br/> ${3}, ${4} ${5}</div>",
    ":BARCODE_IN_USE": "Barcode wird bereits benutzt",
    ":SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    ":DEFAULT_ADDRESS_TYPE": "MITTEILEN",
    ":NEED_ADDRESS": "Eine Adresse ist w\u00e4hrend der Registrierung erforderlich.",
    ":SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    ":DUPE_PATRON_IDENT": "Fand $(0) Patrone(n) mit derselben Identifikation",
    ":ALL_CARDS_APPLY": "\u00c4nderungen anwenden",
    ":ALL_CARDS_CLOSE": "Close",
    ":ADDRESS_APPROVE": "Gepr\u00fcfte Adresse",
    ":DELETE_ADDRESS": "L\u00f6schen Adresse ${0}?",
    ":ALL_CARDS_PRIMARY": "Primary",
    ":ADDRESS_NEW": "Neue Adresse"
}