{
    ":DUPE_USERNAME": "El nombre de usuario ya est\u00e1 en uso",
    ":SECONDARY_GROUP_IS_PROFILE": "Esto ya es el grupo de perfil principal de este patr\u00f3n.",
    ":ALL_CARDS_ACTIVE": "Activo",
    ":REQUESTING_USER": "Cuenta solicitada por ${0} ${1}",
    ":RESET_PASSWORD": "Generar contrase\u00f1a",
    ":SHOW_REQUIRED": "Solo mostrar los campos requeridos",
    ":DUPE_PATRON_EMAIL": "Encontrados ${0} patron(es) con la misma direcci\u00f3n de correo electr\u00f3nico",
    ":HOLD_NOTIFY_SMS": "SMS: ",
    ":DUPE_PATRON_PHONE": "Encontrados ${0} patron(es) con el mismo n\u00famero de tel\u00e9fono",
    ":DUPE_PATRON_ADDR": "Encontrados ${0} patron(es) con la misma direcci\u00f3n",
    ":SHOW_ALL": "Mostrar todos los campos",
    ":VERIFY_PASSWORD": "Verificar contrase\u00f1a",
    ":EXAMPLE": "Ejemplo: ",
    ":USER_SETTINGS": "Configuraci\u00f3n del usuario",
    ":ADDRESS_MAILING": "Env\u00edo de correo",
    ":INVALID_FORM": "El formulario es inv\u00e1lido. Por favor, ed\u00edtelo e int\u00e9ntelo de nuevo.",
    ":ADDRESS_BILLING": "Facturaci\u00f3n",
    ":PARENT_OR_GUARDIAN": "Padre / Tutor",
    ":SECONDARY_GROUP_NOT_ALLOWED": "Usted no tiene permiso para agregar este grupo.",
    ":INVALIDATE": "Invalidar",
    ":UPDATE_EXPIRE_DATE": "Actualizar Fecha de Vencimiento",
    ":DUPE_PATRON_NAME": "Encontrados ${0} patron(es) con el mismo nombre",
    ":SEE_ALL": "Ver todos",
    ":ADDRESS_PENDING": "Esta es una direcci\u00f3n pendiente: ",
    ":SAVE_CLONE": "Guardar y clonar",
    ":ADDRESS_HEADER": "Direcci\u00f3n",
    ":DELETE": "Eliminar",
    ":STAT_CATS": "Categor\u00edas Estad\u00edsticas",
    ":ALL_CARDS_BARCODE": "C\u00f3digo de barras",
    ":HOLD_NOTIFY_EMAIL": "Correo electr\u00f3nico: ",
    ":ADDRESS_OWNED": "Esta direcci\u00f3n pertenece a otro usuario: ",
    ":HOLD_NOTIFY_PHONE": "Tel\u00e9fono: ",
    ":REPLACE_BARCODE": "Reemplazar c\u00f3digo de barras",
    ":SHOW_SUGGESTED": "Mostrar campos sugeridos",
    ":ADD": "A\u00f1adir",
    ":SAVE": "Guardar",
    ":REPLACED_ADDRESS": "Reemplaza la direcci\u00f3n ${0}<br/> ${1} ${2}<br/> ${3}, ${4} ${5}",
    ":BARCODE_IN_USE": "El c\u00f3digo de barras est\u00e1 en uso",
    ":SECONDARY_GROUP_EXISTS": "Este grupo ya esta en la lista.",
    ":DEFAULT_ADDRESS_TYPE": "Direcci\u00f3n",
    ":NEED_ADDRESS": "Se requiere una direcci\u00f3n durante el registro.",
    ":SECONDARY_GROUP_ERROR": "Error salvando grupos secundarios.",
    ":DUPE_PATRON_IDENT": "Encontrados ${0} patron(es) con la misma identificaci\u00f3n",
    ":ALL_CARDS_APPLY": "Aplicar los cambios",
    ":ALL_CARDS_CLOSE": "Cerrar",
    ":ADDRESS_APPROVE": "Aprobar direcci\u00f3n",
    ":DELETE_ADDRESS": "Eliminar direcci\u00f3n ${0}?",
    ":ALL_CARDS_PRIMARY": "Primario",
    ":ADDRESS_NEW": "Direcci\u00f3n nueva"
}