{
    ":FAIL_PART_no_item": "The system could not find this item",
    ":PAYMENT_INVALID_USER_XACT_ID": "We cannot proceed with the payment, because your account was updated from another location.  Please refresh the interface or log out and back in to retrieve the latest account information",
    ":TOTAL_FINES_SELECTED": "Selected total: $${0}",
    ":TOTAL_ITEMS_SESSION": "Total items this session: <b>${0}</b>.",
    ":UNKNOWN_ERROR": "An unhandled exception occurred with error code ${0}",
    ":ITEM_NOT_CATALOGED": "Item ${0} was not found in the system.  Try re-scanning the item.",
    ":TOTAL_HOLDS": "You have <b>${0}</b> total holds.",
    ":TOTAL_FINES_ACCOUNT": "Total fines on account: <b>$${0}</b>.",
    ":FAIL_PART_actor_usr_barred": "The patron is barred",
    ":OPEN_CIRCULATION_EXISTS": "Item ${0} is already checked out to another user",
    ":WORKSTATION_EXISTS": "This workstation has already been registered.  Would you like to use it for this self-check station?",
    ":HOLD_STATUS_READY": "Ready for pickup",
    ":FAIL_PART_no_ultimate_items": "The system could not find any items to match this hold request",
    ":FAIL_PART_no_user": "The system could not find this patron",
    ":ALREADY_OUT": "Item ${0} is already checked out",
    ":TOTAL_ITEMS_ACCOUNT": "Total items on account:  <b>${0}</b>.",
    ":FAIL_PART_config_circ_matrix_test_circulate": "Circulation rules reject this item as non-circulatable",
    ":CHECKOUT_SUCCESS": "Checkout of item ${0} succeeded",
    ":FAIL_PART_no_matchpoint": "System rules do not define how to handle this item",
    ":FAIL_PART_asset_copy_location_circulate": "Items from this shelving location do not circulate",
    ":FAIL_PART_transit_range": "The item cannot transit this far",
    ":CC_PAYABLE_BALANCE": "Total amount to pay: $${0}",
    ":FAIL_PART_config_rule_age_hold_protect_prox": "The item is too new to transit this far",
    ":FAIL_PART_circ_holds_target_skip_me": "The item's circulation library does not fulfill holds",
    ":RENEW_SUCCESS": "Renewal of item ${0} succeeded",
    ":FAIL_PART_config_circ_matrix_circ_mod_test": "The patron has too many items of this type checked out",
    ":FAIL_PART_item.holdable": "The item is not holdable",
    ":MISCELLANEOUS": "Miscellaneous",
    ":HOLDS_READY_FOR_PICKUP": "You have <b>${0}</b> item(s) ready for pickup.",
    ":FAIL_PART_config_hold_matrix_test_holdable": "Hold rules reject this item as unholdable",
    ":WELCOME_BANNER": "Welcome, ${0}",
    ":FAIL_PART_config_hold_matrix_test_max_holds": "The patron has reached the maximum number of holds",
    ":FAIL_PART_config_circ_matrix_test_total_copy_hold_ratio": "The total item-to-hold ratio is too low",
    ":FAIL_PART_location.holdable": "The item's location is not holdable",
    ":FAIL_PART_status.holdable": "The item is not in a holdable status",
    ":PLEASE_LOGIN": "Please log in with your username or library barcode.",
    ":WORKSTATION_REQUIRED": "A workstation is required to log in to selfcheck.  You can set the  workstation name with URL param 'ws'.  \n\nWould you like to register a new workstation for this self-check interface?",
    ":HOLD_STATUS_WAITING": "#${0} in line with ${1} copies",
    ":ENTER_BARCODE": "Please enter an item barcode",
    ":LOGIN_FAILED": "Login for ${0} failed",
    ":GENERIC_CIRC_FAILURE": "Unable to check out item ${0}.  Please see staff.",
    ":FAIL_PART_config_circ_matrix_test_available_copy_hold_ratio": "The available item-to-hold ratio is too low",
    ":FAIL_PART_asset_copy_status": "The item cannot circulate at this time",
    ":ENTER_PASSWORD": "Please enter your password",
    ":MAX_RENEWALS": "No more renewals allowed for item ${0}",
    ":FAIL_PART_asset_copy_circulate": "The item does not circulate"
}