{
    ":CAPTURE_BRESV_DATES": "Temp de r\u00e9servation:",
    ":AUTHOR": "Auteur",
    ":PRINTED_BY": "Imprim\u00e9 par",
    ":TITLE": "Titre",
    ":CAPTURE_CAUSES_TRANSIT": "Cet article est actuellement en transport!",
    ":AUTO_ATTR_VALUE_capture": "Saisie",
    ":CAPTURE_TRANSIT_SOURCE": "De:",
    ":BARCODE": "Code \u00e0 barres",
    ":TRANSIT": "*** TRANSPORT ***",
    ":SUCCESS": "Saisie r\u00e9ussie",
    ":CAPTURE_BRESV_PICKUP_LIB": "Biblioth\u00e8que de collecte:",
    ":DURATION": "R\u00e9serv\u00e9s \u00e0 partir de",
    ":HERES_WHAT_WE_KNOW": "L'information suivante est accessible au sujet de la capture \u00e9chou\u00e9e:",
    ":AUTO_resource_barcode": "Entrez le Code \u00e0 Barres :",
    ":NEEDS_ROUTED_TO": "Cet article doit \u00eatre achemin\u00e9 vers",
    ":RESERVATION_SHELF": "TABLETTE DE R\u00c9SERVATION",
    ":PRINT": "<u>I</u>mprimer",
    ":CAPTURE_INFO": "Information de Capture",
    ":NO_PAYLOAD": "Nous n'avons pas re\u00e7u de plus amples informations depuis le serveur a propos de cette tentative de saisie.",
    ":CAPTURE_TRANSIT_DEST": "Pour:",
    ":SLIP_DATE": "Glissement de date",
    ":AT": "\u00e0",
    ":CAPTURED_NOTHING": "N'a pas pu capturer quoique ce soit.",
    ":RESERVED": "R\u00e9serv\u00e9 pour client",
    ":CAPTURE_BRESV_BRSRC": "Code barre des ressources:",
    ":PRINT_ACCESSKEY": "I",
    ":AUTO_capture_heading": "Saisie des ressources r\u00e9serv\u00e9es",
    ":REQUEST": "Temps n\u00e9cessaire",
    ":UNKNOWN_PROBLEM": "Un probl\u00e8me inconnu s'est produit lors de la tentative de capture.",
    ":FAILURE": "Saisie \u00e9chou\u00e9e",
    ":AUTO_pickup_lib_selector": "Biblioth\u00e8que de collecte:"
}