{
    ":COPY_ALERT": "${0}:\n${1}\n\nVoulez-vous le traiter de toute fa\u00e7on?",
    ":AUTO_patron": "Client",
    ":NO_PATRON_BARCODE": "Veuillez entrer le code \u00e0 barres d\u2019un client",
    ":RETURN_NO_RESPONSE": "Aucune r\u00e9ponse du serveur \u00e0 la tentative de restitution.",
    ":ADDRESS": "${0}\n${1}\n${2}, ${3} ${4}",
    ":AUTO_no_in_bresv": "Le client n\u2019a pas restitu\u00e9 de ressources aujourd\u2019hui :",
    ":AUTO_ready_bresv": "Ces r\u00e9servations du client sont pr\u00eates \u00e0 \u00eatre prises en livraison :",
    ":AUTO_ATTR_VALUE_pickup": "Prendre en livraison",
    ":AUTO_resource": "Ressource",
    ":AUTO_in_bresv": "Le client a restitu\u00e9 ces ressources aujourd\u2019hui",
    ":RETURN_SUCCESS": "Restitution r\u00e9ussie.",
    ":RESERVATIONS_ERROR": "Erreur de communication avec le serveur (demande de r\u00e9servations) :",
    ":AUTO_out_bresv": "Le client a sorti ces r\u00e9servations :",
    ":NO_SUCH_RETURNABLE_RESOURCE": "Aucune ressource retournable de la sorte.",
    ":AUTO_no_ready_bresv": "Le client n\u2019a pas de r\u00e9servations qui sont pr\u00eates \u00e0 \u00eatre prises en livraison pour le moment.",
    ":AUTO_patron_barcode": "Entrer le code \u00e0 barres du client :",
    ":AUTO_return_h1": "Restitution d\u2019articles r\u00e9serv\u00e9s",
    ":AUTO_ATTR_VALUE_return": "Restitution",
    ":PICKUP_NO_RESPONSE": "Aucune r\u00e9ponse du serveur \u00e0 la tentative de prise en livraison.",
    ":RETURN_ERROR": "Erreur de communication avec le serveur (tentative de restitution) :",
    ":PICKUP_ERROR": "Erreur de communication avec le serveur (tentative de prise de livraison) :",
    ":RETURNABLE_RESOURCE_ERROR": "Erreur \u00e0 la recherche d\u2019une ressource retournable :",
    ":RESERVATIONS_NO_RESPONSE": "Aucune r\u00e9ponse du serveur aux demandes sur les r\u00e9servations",
    ":AUTO_ATTR_VALUE_reset": "Effacer/nouveau client",
    ":SELECT_SOMETHING": "Vous n\u2019avez s\u00e9lectionn\u00e9 aucune r\u00e9servation.",
    ":AUTO_barcode_type": "Restitu\u00e9 avec le code \u00e0 barres suivant :",
    ":AUTO_ATTR_VALUE_go": "Aller",
    ":NOTICE_CHANGE_OF_PATRON": "Prenez note que la ressources scann\u00e9e emprunt\u00e9e \u00e0 titre de r\u00e9servation par un client diff\u00e8re de la derni\u00e8re ressource que vous avez scann\u00e9e. Si cela vous surprend, arr\u00eatez-vous \u00e0 examiner les r\u00e9servations en suspens pour votre client ou relatives \u00e0 la ressource.",
    ":AUTO_no_out_bresv": "Le client n\u2019a plus de r\u00e9servations sorties pour le moment.",
    ":AUTO_h1": "Prise en livraison de r\u00e9servations"
}