{
    ":SELECT_A_BRSRC_THEN": "Vous avez cliqu\u00e9 sur \u00ab R\u00e9serve s\u00e9lectionn\u00e9e \u00bb, mais aucun \u00e9l\u00e9ment n\u2019est s\u00e9lectionn\u00e9!\n\nVous devez s\u00e9lectionner une ressource dans la bo\u00eete ci-dessus.\n\n*** Si les ressources que vous voulez s\u00e9lectionner sont surlign\u00e9es en ROUGE,***\nces ressources ne sont pas disponibles au temps voulu; si\npossible, choisissez une autre ressource ou changez le temps de r\u00e9servation.",
    ":ACTOR_CARD_NOT_FOUND": "Code \u00e0 barres du client introuvable. Veuillez r\u00e9essayer.",
    ":NO_EXISTING_BRESV": "Cet utilisateur n\u2019a aucune r\u00e9servation pour le moment.",
    ":AUTO_bresv_grid_resource": "Ressource",
    ":ON_FLY_NO_RESPONSE": "Pas de r\u00e9ponse du serveur lors de la conversion d\u2019un document en ressource r\u00e9servable.",
    ":CXL_BRESV_FAILURE": "Erreur lors de l\u2019annulation des r\u00e9servations; pas de r\u00e9ponse du serveur",
    ":AUTO_i_need_this_resource": "J\u2019ai besoin de cette ressource\u2026",
    ":AUTO_bresv_grid_type": "Type",
    ":HERE_ARE_EXISTING_BRESV": "R\u00e9servations existantes pour",
    ":BRSRC_RETRIVE_ERROR": "Erreur lors de la localisation de la ressource ",
    ":AUTO_ATTR_VALUE_reserve_brsrc": "R\u00e9serve s\u00e9lectionn\u00e9e",
    ":NO_BRA_RESULTS": "Impossible de trouver les caract\u00e9ristiques de la ressource r\u00e9servable.",
    ":AUTO_ATTR_VALUE_button_edit_existing": "Modifier l\u2019\u00e9l\u00e9ment s\u00e9lectionn\u00e9",
    ":GET_BRESV_LIST_ERR": "Erreur lors de l\u2019extraction de la liste de r\u00e9servation ",
    ":CREATE_BRESV_OK_MISSING_TARGET_BLOCKED_BY_CIRC": "The desired reservation(s) are blocked by circulation(s) with the following due date(s):\n${0}",
    ":CREATE_BRESV_OK_MISSING_TARGET": "${0} r\u00e9servation(s) cr\u00e9\u00e9e(s), mais la ressource n\u2019a pas \u00e9t\u00e9 trouv\u00e9e pour ${1} r\u00e9servation(s).\n\nIl ne sera donc pas possible d\u2019effectuer certaines de ces\nr\u00e9servations jusqu\u2019\u00e0 ce qu\u2019une ressource appropri\u00e9e soit disponible.",
    ":AUTO_ending_at": "et",
    ":GET_BRESV_LIST_NO_RESULT": "Le serveur n\u2019a obtenu aucun r\u00e9sultat pour la liste de r\u00e9servation.",
    ":AUTO_arbitrary_resource": "Entrer le code \u00e0 barres d\u2019une ressource r\u00e9servable catalogu\u00e9e",
    ":CXL_BRESV_SUCCESS": "${0} r\u00e9servation(s) annul\u00e9e(s)",
    ":AUTO_choose_a_brt": "Choisir un type de ressource r\u00e9servable",
    ":AUTO_starting_at": "Entre",
    ":NO_USABLE_BRSRC": "Aucune ressource r\u00e9servable. Ajuster les dates de d\u00e9but et de fin\njusqu\u2019\u00e0 ce qu\u2019une ressource soit disponible pour r\u00e9servation.",
    ":COULD_NOT_RETRIEVE_BRT_PASSED_IN": "Error retrieving booking resource type",
    ":CREATE_BRESV_SERVER_ERROR": "Erreur du serveur lors de la cr\u00e9ation de la r\u00e9servation. ",
    ":AUTO_brt_noncat_only": "N\u2019afficher que les types de ressource r\u00e9servable non catalogu\u00e9e",
    ":INVALID_TS_RANGE": "Vous devez choisir des dates valides de d\u00e9but et de fin pour la r\u00e9servation",
    ":ON_FLY_ERROR": "Erreur lors de la conversion d\u2019un document en ressource r\u00e9servable",
    ":CREATE_BRESV_OK_MISSING_TARGET_WILL_CANCEL": "La ressource demand\u00e9e n\u2019ayant pas \u00e9t\u00e9 trouv\u00e9e, cette \nr\u00e9servation sera annul\u00e9e.",
    ":WHERES_THE_BARCODE": "Entrer le code \u00e0 barres du client pour faire une r\u00e9servation",
    ":CREATE_BRESV_SERVER_NO_RESPONSE": "Pas de r\u00e9ponse du serveur lors de la cr\u00e9ation de la r\u00e9servation.",
    ":ERROR_FETCHING_AOUS": "Impossible de trouver les param\u00e8tres de l\u2019unit\u00e9 organisationnelle.\nIl ne s\u2019agit pas d\u2019une erreur fatale, mais il est recommand\u00e9 de\ncommuniquer avec votre gestionnaire syst\u00e8me.",
    ":AUTO_bresv_grid_end_time": "Date de fin",
    ":AUTO_email_notify": "Send email notification when resource is available for pickup.",
    ":AUTO_bresv_grid_start_time": "Date de d\u00e9but",
    ":ANY": "ANY",
    ":OUTSTANDING_BRESV": "R\u00e9servations en suspens pour un client",
    ":CREATE_BRESV_OK": "${0} r\u00e9servation(s) cr\u00e9\u00e9e(s)",
    ":NEED_EXACTLY_ONE_BRT_PASSED_IN": "Vous ne pouvez pas r\u00e9server plusieurs types de ressource \u00e0 la fois.",
    ":AUTO_ATTR_VALUE_next": "Suivant",
    ":CXL_BRESV_SELECT_SOMETHING": "Vous n\u2019avez s\u00e9lectionn\u00e9 aucune r\u00e9servation \u00e0 annuler.",
    ":NO_TARG_DIV": "Impossible de trouver le div cible",
    ":AUTO_explain_bookable": "Pour r\u00e9server un document qui n\u2019est pas enregistr\u00e9 comme une ressource r\u00e9servable, veuillez consulter le dans le catalogue ou aller sous <em>Afficher le document</em>, et s\u00e9lectionnez <em>Rendre le document r\u00e9servable</em> ou <em>R\u00e9server le document maintenant</em>.",
    ":AUTO_with_these_attr": "Avec ces attributs :",
    ":NO_BRT_RESULTS": "Aucun type de ressource r\u00e9servable enregistr\u00e9e.",
    ":CREATE_BRESV_LOCAL_ERROR": "Exception lors de la cr\u00e9ation d\u2019une r\u00e9servation ",
    ":AUTO_ATTR_VALUE_button_cancel_existing": "Cancel selected",
    ":UNTARGETED": "Aucun cibl\u00e9es",
    ":AUTO_ATTR_VALUE_reserve_brt": "Reserve Any",
    ":BRSRC_NOT_FOUND": "Impossible de trouver cette ressource.",
    ":AUTO_or": "- ou -",
    ":GET_PATRON_NO_RESULT": "Aucune r\u00e9ponse du serveur lors de la v\u00e9rification du client par code \u00e0 barres",
    ":AUTO_pickup_lib_selector": "Choose the pickup library for this reservation:",
    ":CXL_BRESV_FAILURE2": "Erreur lors de l\u2019annulation des r\u00e9servations:\n",
    ":AUTO_patron_barcode": "R\u00e9server avec le code \u00e0 barres du client"
}