{
    ":CANCEL": "Cancelar",
    ":MASTER_RECORD": "Principal",
    ":CONFIRM_DELETE_RESULT": "Eliminar registro de autoridad # ${0}.",
    ":NONE_LINK": "[Ninguno]",
    ":LINKED_BIBS": "Numero de registros bibliogr\u00e1ficos ligados: ${0}",
    ":AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    ":AUTHORITY_FIELDS": "Campos de Autoridad (${0})",
    ":VIEW_MARC": "Ver MARC",
    ":CONFIRM_DELETE_PROMPT": "Confirmar eliminaci\u00f3n del registro # ${0}",
    ":MENU_MERGE": "Marcar para mezclar",
    ":ACTIONS": "Acciones",
    ":MENU_DELETE": "Eliminar",
    ":DELETE": "Eliminar",
    ":CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    ":MERGE_RESULT_SUCCESS": "Uni\u00f3n de registros completa",
    ":SAVE_RESULT_SUCCESS": "El registro se ha guardado",
    ":SAVE": "Guardar",
    ":HIDE_MARC": "Ocultar MARC",
    ":CONFIRM_DELETE_TITLE": "\u00bfDesea eliminar el registro de autoridad: \"${0}\"?",
    ":THESAURI": "Tesauro (${0})",
    ":MENU_EDIT": "Editar",
    ":TARGET_RECORD": "Objetivo"
}