{
    ":CANCEL": "Cancelar",
    ":MASTER_RECORD": "Mestre",
    ":CONFIRM_DELETE_RESULT": "Registro de autoridade exclu\u00eddo # ${0}.",
    ":NONE_LINK": "[Nenhum]",
    ":LINKED_BIBS": "N\u00famero de registros bibliogr\u00e1ficos relacionados: ${0}",
    ":AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    ":AUTHORITY_FIELDS": "Campos de Autoridade (${0})",
    ":VIEW_MARC": "Ver MARC",
    ":CONFIRM_DELETE_PROMPT": "Confirmar a exclus\u00e3o de registro # ${0}",
    ":MENU_MERGE": "Marcar para mesclagem",
    ":ACTIONS": "A\u00e7\u00f5es",
    ":MENU_DELETE": "Excluir",
    ":DELETE": "Excluir",
    ":CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    ":MERGE_RESULT_SUCCESS": "Mesclagem de registro esta conclu\u00edda.",
    ":SAVE_RESULT_SUCCESS": "O registo foi gravado.",
    ":SAVE": "Salvar",
    ":HIDE_MARC": "Esconder MARC",
    ":CONFIRM_DELETE_TITLE": "Excluir o registro de autoridade: \"${0}\"?",
    ":THESAURI": "Tesauro  (${0})",
    ":MENU_EDIT": "Editar",
    ":TARGET_RECORD": "Destino"
}