{
    ":CANCEL": "Abbrechen",
    ":MASTER_RECORD": "Master",
    ":CONFIRM_DELETE_RESULT": "Deleted authority record # ${0}.",
    ":NONE_LINK": "[None]",
    ":LINKED_BIBS": "Number of linked bibliographic records: ${0}",
    ":AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    ":AUTHORITY_FIELDS": "Authority Fields (${0})",
    ":VIEW_MARC": "MARC anzeigen",
    ":CONFIRM_DELETE_PROMPT": "Confirm deletion of record # ${0}",
    ":MENU_MERGE": "Mark for Merge",
    ":ACTIONS": "Aktionen",
    ":MENU_DELETE": "L\u00f6schen",
    ":DELETE": "L\u00f6schen",
    ":CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    ":MERGE_RESULT_SUCCESS": "Record merge is complete.",
    ":SAVE_RESULT_SUCCESS": "Record was saved.",
    ":SAVE": "Speichern",
    ":HIDE_MARC": "MARC ausblenden",
    ":CONFIRM_DELETE_TITLE": "Delete the authority record: \"${0}\"?",
    ":THESAURI": "Thesauri (${0})",
    ":MENU_EDIT": "Bearbeiten",
    ":TARGET_RECORD": "Ziel"
}