{
    ":FUND_XFER_SAME_SOURCE_AND_DEST": "No se puede transferir. Los fondos de origen y de destino son el mismo.",
    ":FUND_XFER_CONFIRM": "\u00bfEst\u00e1s seguro que esta listo para cometer esta transferencia?",
    ":CANCEL": "Cancelar",
    ":PO_WARNING_NO_BLOCK_ACTIVATION": "S\u00ed; fondo ${0} (${1}) ser\u00eda sobrecargado m\u00e1s all\u00e1 de su nivel de alerta.",
    ":FINALIZE_PO": "Finalizar este correo general?\n\nEsto facilitara todos los cargos generales y marcara el correo como recibido.",
    ":NO_FIND_INVOICE": "No se pudo encontrar la factura.",
    ":PO_ACTIVATING": "Activando orden de compra...",
    ":EXPORT_EMPTY_LIST": "Ningun valor para el atributo '${0}' encontrado.",
    ":NO_PO_RESULTS": "No hay resultados",
    ":LI_EXISTING_COPIES": "Hay ${ 0 } copias existentes para este registro bibliogr\u00e1fico en esta ubicaci\u00f3n",
    ":DELETE_LI_COPIES_CONFIRM": "Esto borrara las \u00faltimas ${0} copias en la tabla.\u00bfContinuar?",
    ":XUL_RECORD_DETAIL_PAGE": "Detalles del Registro",
    ":COULD_NOT_CREATE_MAPPING": "Error etiquetando el fondo.",
    ":FUND_LIST_ROLLOVER_SUMMARY_FUNDS": "${1} propagadas fondos para el a\u00f1o fiscal ${0} para las ubicaciones seleccionadas",
    ":OUT_OF_COPIES": "Ha aplicado f\u00f3rmulas de distribuci\u00f3n ha cada copia.",
    ":CANCELED": "Cancelado",
    ":VENDOR_PUBLIC": "VENDEDOR P\u00daBLICO",
    ":ROLLBACK_PO_RECEIVE_CONFIRM": "Esto reversionara el recibo de todas las copias para esta orden de compra.\n\nContinuar?",
    ":PO_NAME_OPTIONAL": "${0} (optional)",
    ":CREATE_PO_INVALID": "Una orden de compra debe tener una agencia solicitante y un proveedor.",
    ":INVOICE_IDENT_COLLIDE": "Ya existe una factura en el sistema con la combinaci\u00f3n ofrecida para'N\u00ba de factura' y 'Proveedor', lo cual no se permite",
    ":PREPAYMENT_REQUIRED_REMINDER": "Este PO requiere pago por adelantado.\u00bfEst\u00e1s seguro de que esta listo para activarlo?",
    ":SELECT_SEARCH_FIELD": "Eliga Campo de Busqueda",
    ":LID_CANCEL_CONFIRM": "\u00bfEst\u00e1s seguro de que desea cancelar esta copia?",
    ":PO_HEADING_ERROR": "Problema inesperado creando el PO combinado virtual",
    ":CONFIRM_SPLIT_PO": "\u00bfEst\u00e1s seguro de que desea separar la orden de compra entre\nuna orden de compra por cada art\u00edculo de l\u00ednea constituyente?",
    ":ONE_LI_ATTR_SEARCH_AT_A_TIME": "No puede escribir una busqueda por un valor de atributo y una busqueda por un archivo subido de t\u00e9rminos a la misma vez.",
    ":DUPE_PO_NAME_MSG": "Este nombre ya est\u00e1 en uso por otro correo",
    ":PO_COULD_ACTIVATE": "S\u00ed.",
    ":YES": "S\u00ed",
    ":CREATE_PO_ASSETS_CONFIRM": "Esto creara un bibliogr\u00e1fico, un numero de llamada, y una copia del registro de esta compra en ILS.\n\nContinuar?",
    ":NEW_INVOICE": "Nueva factura",
    ":PO_CANCEL_CONFIRM": "\u00bfEst\u00e1s SEGURO de que desea cancelar su orden de compra?",
    ":LI_CREATING_ASSETS": "Creando bib, numero de llamada, y copiar archivos...",
    ":PO_CHECKING": "[Un momento...]",
    ":CANCEL_REASON": "Raz\u00f3n para cancelar",
    ":ACQ_SEARCH_CLASS_ABBR_jub": "Ll",
    ":PO_ALREADY_ACTIVATED": "Activado",
    ":UR_FILTER_USER": "Introduce el c\u00f3digo de barras para el usuario (o dejar en blanco para desarmar el filtro) :",
    ":DUPE_PO_NAME_LINK": "Ver PO",
    ":NO_LI_TO_CLAIM": "Usted no ha seleccionado ning\u00fan \u00edtem para reclamar",
    ":ACTIVATE_DEBITS_ACCRUED_PROCESSED": "D\u00e9bitos Gravados: ${0}",
    ":UR_CANCEL_CONFIRM": "\u00bfEst\u00e1s SEGURO de que desea cancelar este pedido del usuario?",
    ":FUND_LIST_ROLLOVER_SUMMARY": "Propagaci\u00f3n del Fondo &amp; Resumen del a\u00f1o fiscal ${0}",
    ":PRINT": "Imprimir",
    ":UNRECEIVE_LID": "\u00bfEst\u00e1s seguro de que desea marcar esta copia como no recebida?",
    ":LI_ATTR_SEARCH_CHOOSE_FILE": "Eliga archivo con los terminos de busqueda",
    ":INVOICE_CONFIRM_PRORATE": "\u00bfProrratear cambions?\n\nCualquier cambio subsiguiente a la factura que afectar\u00eda la cantidad prorrateada debe ser resuelta manualmente.",
    ":INVOICE_ITEM_PO_DETAILS": "<b>${0}</b><br/><a href='${1}/acq/po/view/${2}'>PO #${3} ${4}</a><br/>Costo Total Estimado: $${5}",
    ":COULD_NOT_DELETE_MAPPING": "Error removiendo la etiqueta del fondo.",
    ":ACTIVATE_LI_PROCESSED": "Articulos de linea procesado: ${0}",
    ":ITS_YOU": "Usted",
    ":ACTIVATE_COPIES_PROCESSED": "copias reales procesados: ${0}",
    ":LIBRARY_INITIATED": "Librer\u00eda Iniciada",
    ":DFA_TIP": "<strong>Aplicado por</strong>: ${0}<br /><strong>Cuando</strong>: ${1}",
    ":PO_STOP_BLOCKS_ACTIVATION": "No; fondo ${0} (${1}) ser\u00eda sobrecardago m\u00e1s all\u00e1 de su nivel de parada.",
    ":FUND_LIST_ROLLOVER_SUMMARY_ROLLOVER_AMOUNT": "<b>$${1}</b> dinero no gastado fue pasado al a\u00f1o fiscal ${0} para los lugares seleccionados",
    ":ADD_LI_TO_PO_BAD_LI_STATE": "El \u00edtem seleccionado est\u00e1 en un estado que no permite ser a\u00f1adido a una orden de compra",
    ":INVOICE_NUMBER": "Factura #$(0)",
    ":EXPORT_SAVE_DIALOG_TITLE": "Guardar las casillas a un archivo",
    ":INVOICE_EXTRA_COPIES": "Esta intentando de hacer una factura <b>${0}</b> mas copias que originalmente ordenadas. <br/><br/> Para agregar estos art\u00edculos a su orden, seleccione un fondo y eliga 'Agregar Nuevos Art\u00edculos' debajo. <br/>Despu\u00e9s de guardar su factura, puede terminar de editar y importar las copias nuevas de la pagina de detalles en lineitem",
    ":UNNAMED": "Sin nombre",
    ":VENDOR_SAYS_PREPAY_NEEDED": "El vendedor seleccionado requiere pago por adelantado, de acuerdo a nuestros registros.\n\u00bfContinuar sin el pago por adelantado requerido en este PO?",
    ":LI_CANCEL_CONFIRM": "\u00bfEst\u00e1s SEGURO de que desea cancelar este art\u00edculo de l\u00ednea?",
    ":RESET_FORMULAE": "Restablecer f\u00f3rmulas",
    ":DEL_LI_FROM_PO": "Ya se orden\u00f3 el \u00edtem seleccionado! El borrarlo ahora no cancelar\u00e1 ni modificar\u00e1 cualquier pedido que haya sido realizado a un proveedor. El borrar el \u00edtem puede provocar una idea incorrecta del estado de la orden de compra en el sistema lo que es una inconsistencia con la realidad. Est\u00e1 seguro que quiere realizar esto?",
    ":EXPORT_SHORT_LIST": "No todos los art\u00edculos seleccionados tienen el atributo '${0}'.\nEliga aceptar para grabar esos valores que no fueron encontrados.",
    ":ACQ_SEARCH_CLASS_ABBR_acqlia": "LIA",
    ":CONFIRM_FUNDS_AT_STOP": "Uno o m\u00e1s de sus fondos seleccionados tiene un balance por debajo se su nivel de parada.\nPuede que usted no pueda activar ordenes de compra incorporando estas copias.\nContinuar?",
    ":EXPLAIN_DFA_MGMT": "\u00bfRemover registro del uso de esta f\u00f3rmula de distribuci\u00f3n?",
    ":ACQ_SEARCH_CLASS_ABBR_acqlid": "LID",
    ":APPLY": "Aplicar",
    ":ACTIVATE_VQBR_PROCESSED": "Vandelay Registros Procesados: ${0}",
    ":ACTIVATE_BIBS_PROCESSED": "Archivos Bib Fusionado/Importado: ${0}",
    ":DFA_NOT_ALL": "No se pudo grabar toda su solicitud de formulas para distribuci\u00f3n",
    ":FUND_NOT_YET_LOADED": "Fondo todav\u00eda no cargado. Intente regresando a esta pantalla m\u00e1s tarde.",
    ":NO_RESULTS": "No hay resultados.",
    ":NO_LI_GENERAL": "No ha seleccionado ning\u00fan art\u00edculo en l\u00ednea ( adecuado) .",
    ":NUM_CLAIMS_EXISTING": "Reclamaciones (${0} existentes)",
    ":COPIES_TO_RECEIVE": "Numero de copias a recibir: ",
    ":LI_ATTR_SEARCH_TOO_LARGE": "Ese archivo es muy grande para esta operaci\u00f3n.",
    ":NOT_RECVD": "No fue recibido",
    ":ACTIVATE_LID_PROCESSED": "ACQ Copias Procesadas: ${0}",
    ":NO_LI_TO_UPDATE": "No ha seleccionado ning\u00fan art\u00edculo en l\u00ednea para actualizar .",
    ":LI_FORMAT_ERROR": "Error inesperado recuperando la informaci\u00f3n formato lineitem.",
    ":NO": "No",
    ":UR_FILTER_LINEITEM": "Introduzca el ID de l\u00ednea de pedido (o dejar en blanco para desarmar el filtro)",
    ":RECVD": "Recibido",
    ":JUST_NOW": "Ahora mismo",
    ":LOAD_TERMS_FIRST": "No puede recuperar registros hasta que alla cargado un archivo CSV\ncon identificaci\u00f3n bibliogr\u00e1fico en la primera columna.",
    ":VENDOR_SAYS_PREPAY_NOT_NEEDED": "El vendedor seleccionado no necesariamente requiere pago por adelantado, de acuerdo\ncon nuestros registros. \u00bfRequiere pago por adelantado en este PO siempre?",
    ":PO_ACTIVATED_ON": "Activado ${0}",
    ":CONFIRM_DELETE_MAPPING": "\u00bfEst\u00e1s seguro de que desea remover la etiqueta de este fondo?",
    ":UNRECEIVE_LI": "\u00bfEst\u00e1s seguro de que desea marcar este art\u00edculo de l\u00ednea como no recibido?",
    ":LI_BATCH_UPDATE": "actualizaci\u00f3n de posici\u00f3n de lote line",
    ":INVOICE_ITEM_PO_LABEL": "<a href='${0}/acq/po/view/${1}'>PO #${2} ${3}</a><br/>Total Estimated Cost: $${4}",
    ":CONFIRM_LI_ALERT": "Una alerta ha sido puesta en el lineitem titulado,\n\"${0}\":\n\n${1}\n${2}\n${3}\nEliga aceptar si desea reconocer esta alerta.",
    ":CHANGE_CLAIM_POLICY": "Cambiar la forma de petici\u00f3n",
    ":PO_FUND_WARNING_CONFIRM": "\u00bfEst\u00e1s seguro?\u00bfVieno la alerta sobre sobrecargar su fondo?",
    ":INVOICE_CONFIRM_ENTRY_DETACH": "\u00bfRemover $${0} cargo por el art\u00edculo ${1}, ${2} [${3}] de la factura?",
    ":ADD_LI_TO_PO_BAD_PO_STATE": "La OC seleccionada ha sido previamente activada",
    ":INVOICE_COPY_COUNT_INFO": "Copias recibidas en esta factura: ${0} de ${1}.",
    ":LINEITEM_SUMMARY": "<div class='acq-lineitem-summary'><a href='${19}?focus_li=${10}&source=${22}'>${0}</a>, by ${1} (${2})</div>\n<div class='acq-lineitem-summary-extra'>\n${3} Ordered, ${4} Recibido, ${7} Facturado, ${8} Reclamado, ${9} Cancelado, ${23} Retrasado</div>\n<div class='acq-lineitem-summary-extra'>Estimado$${6}, Gravado $${16}, Pagado $${17}</div>\n<div class='acq-lineitem-summary-extra'>\n# ${10} <a style='padding-right: 10px;' class='hidden${20}' href='${11}/acq/po/view/${12}?focus_li=${10}&source=${22}'>&#x2318; ${13} ${18}</a>\n<a style='padding-right: 10px;' class='hidden${21}' href='${11}/acq/picklist/view/${14}?focus_li=${10}&source=${22}'>&#x2756; ${15}</a></div>",
    ":CONFIRM_FUNDS_AT_WARNING": "Uno o m\u00e1s de sus fondos seleccionados tiene un balance por debajo de su nivel de alerta.\nContinuar?",
    ":ROLLBACK_LI_RECEIVE_CONFIRM": "Esto deshacera recibo de los items seleccionados de esta orden de compra.\nContinuar?",
    ":ACQ_SEARCH_CLASS_ABBR_acqpo": "OC",
    ":ACQ_SEARCH_CLASS_ABBR_acqpl": "SL",
    ":INVOICE_CONFIRM_ITEM_DELETE": "\u00bfRemover este $${0} '${1}' cargo de la factura?",
    ":ALERT_UNSELECTED": "Debe de eligir un c\u00f3digo de alerta",
    ":NO_LID_TO_CLAIM": "usted no ha seleccionado ning\u00fan detalles de la l\u00ednea con la reivindicaci\u00f3n",
    ":INVOICES": "Facturas",
    ":INVOICE_ITEM_DETAILS": "${0} <br/> ${1} <br/> ${2}. <br/> Precio Estimado: $${3}. <br/> Identificaci\u00f3n del art\u00edculo de l\u00ednea: ${4} <br/> PO: ${5} <br/> Fecha de la orden: ${6}",
    ":ACQ_SEARCH_CLASS_ABBR_acqinv": "I",
    ":SELECT_AN_LI_ATTRIBUTE": "Debe seleccionar un atributo LI."
}