{
    ":CAPTURE_BRESV_DATES": "Reservation time:",
    ":AUTHOR": "Author",
    ":PRINTED_BY": "Printed by",
    ":TITLE": "Title",
    ":CAPTURE_CAUSES_TRANSIT": "This item is now in transit!",
    ":AUTO_ATTR_VALUE_capture": "Capture",
    ":CAPTURE_TRANSIT_SOURCE": "From:",
    ":BARCODE": "Barcode",
    ":TRANSIT": "*** TRANSIT ***",
    ":SUCCESS": "Capture succeeded",
    ":CAPTURE_BRESV_PICKUP_LIB": "Pickup library:",
    ":DURATION": "Reserved from",
    ":HERES_WHAT_WE_KNOW": "The following information is available about the failed capture:",
    ":AUTO_resource_barcode": "Enter barcode:",
    ":NEEDS_ROUTED_TO": "This item need to be routed to",
    ":RESERVATION_SHELF": "RESERVATION SHELF",
    ":PRINT": "<u>P</u>rint",
    ":CAPTURE_INFO": "Capture Information",
    ":NO_PAYLOAD": "We did not receive further information from the server about this attempt to capture.",
    ":CAPTURE_TRANSIT_DEST": "To:",
    ":SLIP_DATE": "Slip date",
    ":AT": "at",
    ":CAPTURED_NOTHING": "Didn't capture anything.",
    ":RESERVED": "Reserved for patron",
    ":CAPTURE_BRESV_BRSRC": "Resource barcode:",
    ":PRINT_ACCESSKEY": "P",
    ":AUTO_capture_heading": "Capture Reserved Resources",
    ":REQUEST": "Request time",
    ":UNKNOWN_PROBLEM": "An unknown problem occurred during capture attempt.",
    ":FAILURE": "Capture failed",
    ":AUTO_pickup_lib_selector": "Pickup library:"
}