{
    ":DUPE_USERNAME": "Kullan\u0131c\u0131 ad\u0131 zaten kullan\u0131mda",
    ":SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    ":ALL_CARDS_ACTIVE": "Etkin",
    ":REQUESTING_USER": "Account requested by ${0} ${1}",
    ":RESET_PASSWORD": "Generate Password",
    ":SHOW_REQUIRED": "Sadece Gerekli Alanlar\u0131 G\u00f6ster",
    ":DUPE_PATRON_EMAIL": "Found ${0} patron(s) with the same email address",
    ":HOLD_NOTIFY_SMS": "SMS: ",
    ":DUPE_PATRON_PHONE": "Found ${0} patron(s) with the same phone number",
    ":DUPE_PATRON_ADDR": "Found ${0} patron(s) with the same address",
    ":SHOW_ALL": "T\u00fcm Alanlar\u0131 G\u00f6ster",
    ":VERIFY_PASSWORD": "Parolay\u0131 Do\u011frula",
    ":EXAMPLE": "\u00d6rnek: ",
    ":USER_SETTINGS": "Kullan\u0131c\u0131 Ayarlar\u0131",
    ":ADDRESS_MAILING": "Mailing",
    ":INVALID_FORM": "Form hatal\u0131. L\u00fctfen d\u00fczenleyip tekrar deneyin.",
    ":ADDRESS_BILLING": "\u00dccretlendirme",
    ":PARENT_OR_GUARDIAN": "Parent/Guardian",
    ":SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    ":INVALIDATE": "Ge\u00e7ersiz",
    ":UPDATE_EXPIRE_DATE": "Update Expire Date",
    ":DUPE_PATRON_NAME": "Found ${0} patron(s) with the same name",
    ":SEE_ALL": "Hepsini G\u00f6ster",
    ":ADDRESS_PENDING": "bu beklemedeki bir adres: ",
    ":SAVE_CLONE": "Save &amp; Clone",
    ":ADDRESS_HEADER": "Adres",
    ":DELETE": "Delete",
    ":STAT_CATS": "\u0130statistiksel Kategoriler",
    ":ALL_CARDS_BARCODE": "Barkod",
    ":HOLD_NOTIFY_EMAIL": "Eposta: ",
    ":ADDRESS_OWNED": "Bu adres ba\u015fka bir kullan\u0131c\u0131ya ait: ",
    ":HOLD_NOTIFY_PHONE": "Telefon: ",
    ":REPLACE_BARCODE": "Barkodu Yenile",
    ":SHOW_SUGGESTED": "Show Suggested Fields",
    ":ADD": "Add",
    ":SAVE": "Kaydet",
    ":REPLACED_ADDRESS": "Replaces address ${0}<br/> ${1} ${2}<br/> ${3}, ${4} ${5}",
    ":BARCODE_IN_USE": "Barkod zaten kullan\u0131mda",
    ":SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    ":DEFAULT_ADDRESS_TYPE": "MAILING",
    ":NEED_ADDRESS": "An address is required during registration.",
    ":SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    ":DUPE_PATRON_IDENT": "Found ${0} patron(s) with the same identification",
    ":ALL_CARDS_APPLY": "De\u011fi\u015fiklikleri Uygula",
    ":ALL_CARDS_CLOSE": "Kapat",
    ":ADDRESS_APPROVE": "Approve Address",
    ":DELETE_ADDRESS": "${0} adresinii siliyorsun?",
    ":ALL_CARDS_PRIMARY": "Birincil",
    ":ADDRESS_NEW": "Yeni Adres"
}