{
    ":LABEL_NEW_BRANCH": "New Branch",
    ":CONFIRM_DELETE": "Are you sure you want to delete ${0}?",
    ":CBHO_NEEDS_NAME": "You need to enter a name for the best-hold order.",
    ":ACQ_DISTRIB_FORMULA_NAME_CLONE": "${0} (Clone)",
    ":CONFIRM_EXIT_PPL": "There are unsaved modified permissions. Click OK to save these changes, or Cancel to abandon them.",
    ":ERROR_FETCHING_HOURS": "Problem fetching hours of operation for ${0}",
    ":CONFIRM_EXIT_AOU": "There are unsaved changes to one or more organizational units. Click OK to save these changes, or Cancel to abandon them.",
    ":ERROR_FETCHING_TYPES_AOUT": "Problem fetching organizational unit types",
    ":SUCCESS_SAVING_PHYSICAL": "Saved changes to the Physical Address of ${0}",
    ":SUCCESS_CREATING_CHILD_AOUT": "New child Organization Type created for ${0}",
    ":ERROR_SAVING_ILL": "Problem saving ILL Address data for ${0}",
    ":ACQ_DISTRIB_FORMULA_NAME_PROMPT": "Enter new formula name",
    ":CONFIRM_EXIT_PGT": "There are unsaved modified permission maps. Click OK to save these changes, or Cancel to abandon them.",
    ":ERROR_SAVING_HOLDS": "Problem saving Holds Address data for ${0}",
    ":NAME": "\u0130sim",
    ":ERROR_FETCHING_ORGS": "Problem fetching organizational unit data",
    ":ERROR_FETCHING_PERM_MAPS": "Problem fetching perm maps",
    ":ERROR_CALLING_METHOD_PERM_MAP": "Problem calling method to create new permission map",
    ":ERROR_FETCHING_ILL": "Problem fetching ILL Address for ${0}",
    ":LABEL_DESCRIPTION": "Tan\u0131m",
    ":SURVEY_QUESTION": "Soru:",
    ":ERROR_FETCHING_PHYSICAL": "Problem fetching Physical Address for ${0}",
    ":SUCCESS_NEW_CHILD_GROUP": "New child Group created for ${0}",
    ":HOLDABLE": "Holdable",
    ":ERROR_FETCHING_PERMS": "Problem fetching perms",
    ":LABEL_VALUE": "De\u011fer",
    ":ERROR_CALLING_METHOD_AOUT": "Problem calling method to create child organization type",
    ":ERROR_SAVING_PHYSICAL": "Problem saving Physical Address data for ${0}",
    ":SUCCESS_SAVING_ILL": "Saved changes to the ILL Address of ${0}",
    ":ERROR_FETCHING_HOLDS": "Problem fetching Holds Address for ${0}",
    ":ID": "Kimlik",
    ":ERROR_FETCHING_STATUSES": "Problem fetching statuses",
    ":ERROR_CALLING_METHOD_PPL": "Problem calling method to create new permission",
    ":ERROR_CALLING_METHOD_CCS": "Problem calling method to create new copy status",
    ":IS_AVAILABLE": "Is Available",
    ":SURVEY_ADD_ANSWER": "Add Answer",
    ":SURVEY_DELETE_QUESTION": "Soru & Cevaplar\u0131 Sil",
    ":LABEL_DEPTH": "Derinlik",
    ":LABEL_NEW_TYPE": "Yeni T\u00fcr",
    ":LABEL_NEW_GROUP": "New Group",
    ":STATUS_DELETED": "${0} silindi",
    ":SUCCESS_DELETED_PERM_MAP": "Permission mapping deleted",
    ":ERROR_CREATING_CHILD_AOUT": "Problem creating child organization type",
    ":STATUS_EDITING": "${0} \u015fimdi d\u00fczenleniyor",
    ":SUCCESS_CREATING_PERMISSION": "Yeni ${0} izni olu\u015fturuldu",
    ":SUCCESS_CREATING_STATUS": "New ${0} status created",
    ":ERROR_SAVING_DATA_CAM": "${0} ${1} i\u00e7in veri kaydetmede sorun",
    ":CBHO_EDITING_EXISTING": "You are editing best-hold order #${0}: ${1}.",
    ":OPAC_VISIBLE": "OPAC Visible",
    ":SURVEY_SAVE_ADD": "Soruyu Kaydet & Cevap Ekle",
    ":ERROR_CREATING_PERM_MAP": "Problem creating new Permission Map",
    ":SUCCESS_SAVING_HOLDS": "Saved changes to the Holds Address of ${0}",
    ":ERROR_SAVING_PERM_DATA": "Problem saving permission data for ${0}",
    ":LABEL_GRANTABLE": "Grantable",
    ":ERROR_ORPHANS": "Cannot delete ${0}, ${1} subordinates still exist.",
    ":ERROR_CREATING_STATUS": "Yeni Durum olu\u015fturmada sorun",
    ":ERROR_CALLING_METHOD_CAM": "Problem calling method to create new ${0}",
    ":ERROR_CALLING_METHOD_PGT": "Problem calling method to create child Group",
    ":ERROR_FETCHING_GROUPS": "Problem fetching groups",
    ":SURVEY_SAVE_CHANGES": "De\u011fi\u015fiklikleri Kaydet",
    ":LABEL_CODE": "Kod",
    ":SURVEY_DELETE_ANSWER": "Delete Answer",
    ":SUCCESS_SAVE_PERM": "Saved permission changes to ${0}",
    ":SURVEY_FOOT_LABEL": "Sorular & Cevaplar",
    ":COPY_ACTIVE": "Sets copy active",
    ":SUCCESS_CREATING_CHILD_AOU": "New child Organizational Unit created for ${0}",
    ":SUCCESS_SAVING_DATA": "${0} \u00fczerine yap\u0131lan de\u011fi\u015fiklikler kaydedildi",
    ":TRANSLATION": "\u00c7eviri",
    ":ERROR_DELETING_PERM_MAPPING": "Problem deleting permission mapping ${0}",
    ":CBHO_NO_LOAD": "Unable to load selected item.",
    ":SUCCESS_SAVING_HOO": "Hours of Operation updated for ${0}",
    ":ERROR_CREATING_CHILD_GROUP": "Problem creating child Group",
    ":ERROR_SAVING_MAILING": "Problem saving Mailing Address data for ${0}",
    ":ERROR_CREATING_PERMISSION": "Problem creating new Permission",
    ":CONFIRM_EXIT_CAM": "There are unsaved changes to one or more ${0} codes. Click OK to save these changes, or Cancel to abandon them.",
    ":LABEL_TRANSLATION": "\u00c7eviri",
    ":CBHO_EDITING_NEW": "You are editing a new best-hold order.",
    ":SURVEY_ANSWER": "Cevap:",
    ":ERROR_SAVING_HOO": "Problem saving Hours of Operation data for ${0}",
    ":ERROR_DELETING_LAST_AOUT": "Cannot delete ${0}. You need at least one organization type.",
    ":CBHO_FIELD_DISPLAY": "${0}: ${1}",
    ":CONFIRM_UNSAVED_CHANGES": "There are unsaved changes to one or more organization types. Click OK to save these changes, or Cancel to abandon them.",
    ":END_SURVEY": "End Survey Now",
    ":SUCCESS_NEW_PERM_MAP": "New permission map created",
    ":SURVEY_WARN_TEXT": "No questions can be modified or added at this time. The survey Start Date must be set for the future to add new questions or modify existing questions.",
    ":SUCCESS_SAVING_MAILING": "Saved changes to the Mailing Address of ${0}",
    ":ERROR_FETCHING_MAILING": "Problem fetching Mailing Address for ${0}",
    ":SUCCESS_CREATING_CODE": "Yeni ${0} ${1} olu\u015fturuldu",
    ":ERROR_DELETING": "${0} silmede sorun",
    ":ERROR_CREATING_CHILD_AOU": "Problem creating child organizational unit",
    ":ERROR_DELETING_LAST_AOU": "Cannot delete ${0}, you need at least one organization unit.",
    ":EVENT_DEF_LABEL": "${0}: ${1}",
    ":SURVEY_ID": "Survey ID # ${0}",
    ":ERROR_SAVING_STATUS": "${0} kaydedilmesinde sorun",
    ":SUCCESS_SAVE": "${0} \u00fczerine yap\u0131lan de\u011fi\u015fiklikler kaydedildi",
    ":CONFIRM_EXIT_CCS": "There are unsaved changes to one or more copy statuses. Click OK to save these changes, or Cancel to abandon them.",
    ":ERROR_SAVING_DATA": "${0} i\u00e7in veri kaydetmesinde sorun"
}