{
    ":CANCEL": "Peruuta",
    ":MASTER_RECORD": "Master",
    ":CONFIRM_DELETE_RESULT": "Auktoriteettitietue # ${0} tuhottu.",
    ":NONE_LINK": "[Ei mit\u00e4\u00e4n]",
    ":LINKED_BIBS": "Linkitettyjen bibliografisten tietueiden lukum\u00e4\u00e4r\u00e4: ${0}",
    ":AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    ":AUTHORITY_FIELDS": "Auktoriteettikent\u00e4t (${0})",
    ":VIEW_MARC": "N\u00e4yt\u00e4 MARC",
    ":CONFIRM_DELETE_PROMPT": "Vahvista tietueen # ${0} poisto",
    ":MENU_MERGE": "Merkitse yhdistett\u00e4v\u00e4ksi",
    ":ACTIONS": "Toiminnot",
    ":MENU_DELETE": "Tuhoa",
    ":DELETE": "Tuhoa",
    ":CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    ":MERGE_RESULT_SUCCESS": "Tietueet yhdistetty.",
    ":SAVE_RESULT_SUCCESS": "Tietue tallennettiin.",
    ":SAVE": "Tallenna",
    ":HIDE_MARC": "Piilota MARC",
    ":CONFIRM_DELETE_TITLE": "Tuhotaanko auktoriteettitietue: \"${0}\"?",
    ":THESAURI": "Synonyymisanakirjat (${0})",
    ":MENU_EDIT": "Muokkaa",
    ":TARGET_RECORD": "Kohde"
}