{
    ":modifier_default": "-- Selecione um Modificador --",
    ":metabib": "Pesquisa por Metaregistro",
    ":site": "P\u00e1gina",
    ":depth": "Profundidade da Busca",
    ":new_modifier": "Novo Modificador",
    ":filter_default": "-- Selecionar um filtro --",
    ":item_form": "Forma",
    ":during": "Em Publica\u00e7\u00e3o",
    ":more": "Mais ...",
    ":filters": "Filtros",
    ":new_filter": "Novo Filtro",
    ":advanced": "Avan\u00e7ado",
    ":faceted_searches": "Facetas",
    ":contains": "Cont\u00e9m",
    ":basic": "B\u00e1sico",
    ":lit_form": "Forma Liter\u00e1ria",
    ":format": "Tipo e Forma",
    ":classed_searches": "Pesquisas Classificadas",
    ":ascending": "Ordenar em Ordem Crescente",
    ":notcontains": "N\u00e3o Cont\u00e9m",
    ":or": "OU",
    ":vr_format": "Formato da Grava\u00e7\u00e3o em V\u00eddeo",
    ":new_facet": "Nova Faceta",
    ":bib_level": "N\u00edvel Catalogr\u00e1fico",
    ":item_type": "Tipo",
    ":remove": "Remover",
    ":staff": "Pesquisa de Funcion\u00e1rio",
    ":modifiers": "Modificadores",
    ":perform_search": "Ir!",
    ":audience": "P\u00fablico",
    ":exact": "Corresponde Exatamente",
    ":and": "E",
    ":available": "Dispon\u00edvel",
    ":between": "Publicador Entre",
    ":before": "Publicado antes",
    ":statuses": "Estados",
    ":less": "...Menos",
    ":after": "Publicado depois",
    ":sort": "Ordenar Axis",
    ":descending": "Ordenar em Ordem Decrescente"
}