{
    ":TFORMS_LABEL_SUM": "Suma",
    ":TEMPLATE_CONF_SELECT_CANCEL": "Seleccione el valor, o cancelar:",
    ":TRANSFORMS_SUM": "Suma",
    ":TFORMS_LABEL_FIRST5": "Primeros 5 caracteres (para c\u00f3digos postales de EEUU)",
    ":TEMPLATE_CONF_DEFAULT": "Valor ${0}:",
    ":TRANSFORMS_MIN": "M\u00edn",
    ":TRANSFORMS_DATE": "Fecha",
    ":OPERATORS_GT_EQUAL": "Mayor o igual a",
    ":FILTERS_LABEL_EQUALS": "Igual a",
    ":TFORMS_LABEL_MIN": "M\u00edn",
    ":OPERATORS_LTE_TIME": "En o Antes (Fecha/Hora)",
    ":TFORMS_LABEL_DOY": "D\u00eda del a\u00f1o",
    ":TRANSFORMS_AGE": "Edad",
    ":FILTERS_LABEL_NE_ANY": "Es distinto de",
    ":TFORMS_LABEL_DOW": "D\u00eda de la semana",
    ":FILTERS_LABEL_LT_TIME": "Antes de (Fecha/Hora)",
    ":OPERATORS_EQ_ANY": "Igual a cualquiera",
    ":FOLDER_WINDOW_COLNAME_ALL": "Todos",
    ":LINK_NULLABLE_NONE": "Ninguno",
    ":FILTERS_LABEL_GT_EQUAL": "Mayor o igual a",
    ":RPT_BUILDER_CONFIRM_SAVE": "Nombre : ${0}\nDescripci\u00f3n: ${1}\n\u00bfGuardar plantilla?",
    ":TRANSFORMS_ROUND": "Redondear",
    ":TFORMS_LABEL_RAW_DATA": "Datos en crudo",
    ":OPERATORS_NULL_BLANK": "Es NULL \u00f3 vac\u00edo",
    ":OPERATORS_EQUALS": "Igual a",
    ":FOLDER_WINDOW_REPORT_OUTPUT": "Informe de salida: ${0}",
    ":TEMPLATE_CONF_CONFIRM_STATE": "Click en OK para VERDADERO o en Cancelar para FALSO.",
    ":TFORMS_LABEL_AGE": "Edad",
    ":TEMPLATE_CONF_EQUALS": "Igual a",
    ":TRANSFORMS_DAY_NAME": "Nombre del d\u00eda",
    ":REPORT_EDITOR_REPORT_FOLDERS": "Carpetas de informes",
    ":FILTERS_LABEL_LSE_TIME": "En o Antes (Fecha/Hora)",
    ":FILTERS_LABEL_NOT_BETWEEN": "No est\u00e9 entre",
    ":TRANSFORMS_MAX": "M\u00e1x",
    ":TFORMS_LABEL_HOD": "Hora del d\u00eda",
    ":TRANSFORMS_YEAR_TRUNC": "A\u00f1o",
    ":TFORMS_LABEL_COUNT_DISTINCT": "Recuento distintivo",
    ":TFORMS_LABEL_DAY_NAME": "Nombre del d\u00eda",
    ":TEMPLATE_CONF_CONFIRM_SAVE": "Nombre : ${0}\nDescripci\u00f3n: ${1}\n\u00bfGuardar plantilla?",
    ":TEMPLATE_CONF_NO_MATCH": "Campo no coincide con ninguno de la lista (separados por coma):",
    ":OPERATORS_LESS_THAN": "Menor que",
    ":FOLDERS_TEMPLATES": "Plantillas",
    ":OPERATORS_NOT_BETWEEN": "No est\u00e9 entre",
    ":TFORMS_LABEL_MAX": "M\u00e1x",
    ":FILTERS_LABEL_GTE_TIME": "En o Despu\u00e9s (Fecha/Hora)",
    ":TFORMS_LABEL_MONTH_TRUNC": "A\u00f1o + Mes",
    ":TRANSFORMS_DOM": "D\u00eda del mes",
    ":WIDGET_YEARS": "A\u00f1o(s)",
    ":OPERATORS_GT_TIME": "Despu\u00e9s de (Fecha/Hora)",
    ":TFORMS_LABEL_QUARTERS_AGO": "trimestres atr\u00e1s",
    ":TRANSFORMS_DOW": "D\u00eda de la semana",
    ":TEMPLATE_CONF_IN": "Campo coincide con uno de la lista (separados por coma):",
    ":LINK_NULLABLE_DEFAULT": "Predeterminado",
    ":OPERATORS_NOT_NULL_BLANK": "No es NULL o vac\u00edo",
    ":WIDGET_QUARTERS": "Cuarto(s)",
    ":TRANSFORMS_DOY": "D\u00eda del a\u00f1o",
    ":FILTERS_LABEL_NOT_IN": "No est\u00e1 en la lista",
    ":TRANSFORMS_QOY": "Cuarto de a\u00f1o",
    ":FOLDER_WINDOW_COLNAME_SELECT": "Seleccionar",
    ":OPERATORS_IS_NOT_NULL": "No es NULL",
    ":TFORMS_LABEL_LAST": "\u00daltimo valor",
    ":SOURCE_BROWSE_AGGREGATE": "Agregar",
    ":TRANSFORMS_LAST": "\u00daltimo valor",
    ":TFORMS_LABEL_WOY": "Semana del a\u00f1o",
    ":TEMPLATE_CONF_BARE": "Simple",
    ":FOLDER_WINDOW_CHANGE_FOLDERS": "Cambiar carpetas",
    ":FILTERS_LABEL_NULL_BLANK": "Es NULL \u00f3 vac\u00edo",
    ":OPERATORS_NE_ANY": "Es distinto de",
    ":REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Por favor provea una carpeta de salida",
    ":SOURCE_BROWSE_NON_AGGREGATE": "No Agregados",
    ":TRANSFORMS_COUNT_DISTINCT": "Recuento distintivo",
    ":TRANSFORMS_FIRST": "Primer valor",
    ":TEMPLATE_CONF_SUCCESS_SAVE": "La plantilla ${0} fue guardada correctamente.",
    ":FILTERS_LABEL_GT_TIME": "Despu\u00e9s de (Fecha/Hora)",
    ":TRANSFORMS_QUARTERS_AGO": "trimestres atr\u00e1s",
    ":OPERATORS_LT_TIME": "Antes de (Fecha/Hora)",
    ":TFORMS_LABEL_MONTH_NAME": "Nombre del mes'",
    ":TRANSFORMS_INT": "Descartar decimales",
    ":OPERATORS_LT_EQUAL": "Menor o igual a",
    ":FILTERS_LABEL_ILIKE": "Contiene subcadena coincidente (ignorar may\u00fasculas)",
    ":TRANSFORMS_MOY": "Mes del a\u00f1o",
    ":FILTERS_LABEL_LESS_THAN": "Menor que",
    ":FOLDERS_TEMPLATE": "Plantilla",
    ":FILTERS_LABEL_LIKE": "Contiene subcadena coincidente",
    ":TFORMS_LABEL_FIRST_WORD": "Primera cadena contigua sin espacios",
    ":OPERATORS_ILIKE": "Contiene subcadena coincidente (ignorar may\u00fasculas)",
    ":LINK_NULLABLE_RIGHT": "Padres",
    ":FILTERS_LABEL_LT_EQUAL": "Menor o igual a",
    ":TRANSFORMS_SUBSTRING": "Subcadena",
    ":TRANSFORMS_MONTH_NAME": "Nombre del mes",
    ":OPERATORS_IN_LIST": "En la lista",
    ":TFORMS_LABEL_AVERAGE": "Promedio",
    ":TRANSFORMS_LOWER": "Min\u00fasculas",
    ":FOLDERS_REPORT": "Informe",
    ":TFORMS_LABEL_DOM": "D\u00eda del mes",
    ":FILTERS_LABEL_IN": "En la lista",
    ":TEMPLATE_CONF_RAW_DATA": "Datos en crudo",
    ":TFORMS_LABEL_DATE": "Fecha",
    ":TFORMS_LABEL_FIRST": "Primer valor",
    ":TFORMS_LABEL_INT": "Descartar decimales",
    ":TFORMS_LABEL_UPPER": "May\u00fasculas",
    ":TEMPLATE_CONF_TRUE": "Verdadero",
    ":TRANSFORMS_FIRST5": "Primeros 5 caracteres (para c\u00f3digos postales de EEUU)",
    ":TRANSFORMS_HOUR_TRUNC": "Hora",
    ":LINK_NULLABLE_LEFT": "Hijo",
    ":FILTERS_LABEL_NOT_NULL_BLANK": "No es NULL o vac\u00edo",
    ":TRANSFORMS_MONTHS_AGO": "Hace meses",
    ":TRANSFORMS_HOD": "Hora del d\u00eda",
    ":SOURCE_SETUP_CORE_SOURCES": "Fuentes centrales",
    ":REPORT_EDITOR_INVALID_DATE_ALERT": "fecha inicia inv\u00e1lida -  YYYY-MM-DD",
    ":FOLDER_WINDOW_SELECT_ITEM": "Por favor seleccione un elemento de la lista",
    ":TRANSFORMS_AVERAGE": "Promedio",
    ":TFORMS_LABEL_LOWER": "Min\u00fasculas",
    ":OPERATORS_NOT_IN_LIST": "No est\u00e1 en la lista",
    ":TEMPLATE_CONF_NOT_IN": "Campo no coincide con ninguno de la lista (separados por coma):",
    ":TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Cambiar la pista de campo a:",
    ":OPERATORS_LIKE": "Contiene subcadena coincidente",
    ":FOLDER_WINDOW_COLNAME_NONE": "Ninguno",
    ":TFORMS_LABEL_MONTHS_AGO": "Hace meses",
    ":TFORMS_LABEL_YEAR_TRUNC": "A\u00f1o",
    ":TRANSFORMS_UPPER": "May\u00fasculas",
    ":OPERATORS_IS_NULL": "Es NULL",
    ":TFORMS_LABEL_COUNT": "Contar",
    ":FILTERS_LABEL_NOT_NULL": "No es NULL",
    ":WIDGET_MONTHS": "Mes(es)",
    ":TRANSFORMS_BARE": "Datos en crudo",
    ":WIDGET_REAL_DATE": "Fecha real",
    ":SOURCE_SETUP_ALL_AVAIL_SOURCES": "Todas las fuentes disponibles",
    ":OPERATORS_GTE_TIME": "En o Despu\u00e9s (Fecha/Hora)",
    ":REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Por favor, cambie el nombre del informe",
    ":FILTERS_LABEL_GREATER_THAN": "Mayor que",
    ":TFORMS_LABEL_MOY": "Mes del a\u00f1o",
    ":FOLDERS_OUTPUT": "Salida",
    ":REPORT_EDITOR_OUTPUT_FOLDERS": "Carpetas de salida",
    ":TEMPLATE_CONF_CONFIRM_RESET": "Ya agreg\u00f3 el campo [${0}]\ndesde la fuente [${1}]. Click en\nOK s\u00ed desea reiniciar el campo.",
    ":TRANSFORMS_FIRST_WORD": "Primera cadena contigua sin espacios",
    ":FILTERS_LABEL_NULL": "Es NULL",
    ":REPORT_EDITOR_ENTER_NAME_ALERT": "Por favor ingrese un nombre de informe",
    ":WIDGET_RELATIVE_DATE": "Fecha relativa",
    ":TEMPLATE_CONF_BOOLEAN_VALUE": "Valor booleano",
    ":TEMPLATE_CONF_BETWEEN": "El valor del campo est\u00e1 entre (separados por comas):",
    ":SOURCE_SETUP_CONFIRM_EXIT": "\u00a1Usted ha comenzado a crear una plantilla!\n Seleccionar una nueva fuente de inicio destruir\u00e1 la plantilla actual y tendr\u00e1 que volver a empezar. \u00bfEst\u00e1 de acuerdo?",
    ":FOLDERS_REPORTS": "Informes",
    ":TFORMS_LABEL_HOUR_TRUNC": "Hora",
    ":FILTERS_LABEL_BETWEEN": "Entre",
    ":REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Por favor provea una carpeta de informe",
    ":TEMPLATE_CONF_FALSE": "Falso",
    ":TRANSFORMS_WOY": "Semana del a\u00f1o",
    ":OPERATORS_GREATER_THAN": "Mayor que",
    ":TEMPLATE_CONF_NOT_BETWEEN": "Valor de campo no est\u00e1 entre (separados por coma):",
    ":TRANSFORMS_MONTH_TRUNC": "A\u00f1o + Mes",
    ":TRANSFORMS_COUNT": "Contar",
    ":OPERATORS_BETWEEN": "Entre",
    ":WIDGET_DAYS": "D\u00eda(s)",
    ":FILTERS_LABEL_EQ_ANY": "Igual a cualquiera",
    ":TFORMS_LABEL_QOY": "Cuarto de a\u00f1o",
    ":TFORMS_LABEL_ROUND": "Redondear",
    ":TEMPLATE_CONF_PROMPT_CHANGE": "Cambiar el encabezado de la columna a: ${0}"
}