{
    ":modifier_default": "-- Select a Modifier --",
    ":metabib": "Metarecord Search",
    ":site": "Site",
    ":depth": "Search Depth",
    ":new_modifier": "New Modifier",
    ":filter_default": "-- Select a Filter --",
    ":item_form": "Form",
    ":during": "In Publication",
    ":more": "More...",
    ":filters": "Filters",
    ":new_filter": "New Filter",
    ":advanced": "Advanced",
    ":faceted_searches": "Facets",
    ":contains": "Contains",
    ":basic": "Basic",
    ":lit_form": "Literary Form",
    ":format": "Type and Form",
    ":classed_searches": "Classed Searches",
    ":ascending": "Sort Ascending",
    ":notcontains": "Does Not Contain",
    ":or": "OR",
    ":vr_format": "Videorecording Format",
    ":new_facet": "New Facet",
    ":bib_level": "Bibliographic Level",
    ":item_type": "Type",
    ":remove": "Remove",
    ":staff": "Staff Search",
    ":modifiers": "Modifiers",
    ":perform_search": "Go!",
    ":audience": "Audience",
    ":exact": "Exactly Matches",
    ":and": "AND",
    ":available": "Available",
    ":between": "Published Between",
    ":before": "Published Before",
    ":statuses": "Statuses",
    ":less": "...Less",
    ":after": "Published After",
    ":sort": "Sort Axis",
    ":descending": "Sort Descending"
}