{
    ":FUND_XFER_SAME_SOURCE_AND_DEST": "Cannot transfer. The source and destination funds are the same.",
    ":FUND_XFER_CONFIRM": "Are you sure you're ready to commit this transfer?",
    ":CANCEL": "Cancel",
    ":PO_WARNING_NO_BLOCK_ACTIVATION": "Yes; fund ${0} (${1}) would be encumbered beyond its warning level.",
    ":FINALIZE_PO": "Finalize this blanket PO?\nThis will disencumber all blanket charges and mark the PO as received",
    ":NO_FIND_INVOICE": "Could not find that invoice.\nNote that the Invoice # field is case-sensitive.",
    ":PO_ACTIVATING": "Activating purchase order...",
    ":EXPORT_EMPTY_LIST": "No values for attribute '${0}' found.",
    ":NO_PO_RESULTS": "No results",
    ":LI_EXISTING_COPIES": "There are ${0} existing copies for this bibliographic record at this location",
    ":DELETE_LI_COPIES_CONFIRM": "This will delete the last ${0} copies in the table.  Proceed?",
    ":XUL_RECORD_DETAIL_PAGE": "Record Details",
    ":COULD_NOT_CREATE_MAPPING": "Error tagging fund.",
    ":FUND_LIST_ROLLOVER_SUMMARY_FUNDS": "<b>${1}</b> funds propagated for fiscal year ${0} for the selected locations",
    ":OUT_OF_COPIES": "You have applied distribution formulas to every copy.",
    ":CANCELED": "Canceled",
    ":VENDOR_PUBLIC": "VENDOR PUBLIC",
    ":ROLLBACK_PO_RECEIVE_CONFIRM": "This will rollback receipt of all copies for this purchase order.\n\nContinue?",
    ":PO_NAME_OPTIONAL": "${0} (optional)",
    ":CREATE_PO_INVALID": "A purchase order must have an ordering agency and a provider.",
    ":INVOICE_IDENT_COLLIDE": "There is already an invoice in the system with the given combination of 'Vendor Invoice ID' and 'Provider,' which is not allowed.",
    ":PREPAYMENT_REQUIRED_REMINDER": "This PO requires prepayment.  Are you certain you're ready to activate it?",
    ":SELECT_SEARCH_FIELD": "Select Search Field",
    ":LID_CANCEL_CONFIRM": "Are you SURE you want to cancel this copy?",
    ":PO_HEADING_ERROR": "Unexpected problem building virtual combined PO",
    ":CONFIRM_SPLIT_PO": "Are you sure you want to split this purchase order into\none purchase order for every constituent line item?",
    ":ONE_LI_ATTR_SEARCH_AT_A_TIME": "You cannot both type in an attribute value search and search for an uploaded file of terms at the same time.",
    ":DUPE_PO_NAME_MSG": "This name is already in use by another PO",
    ":PO_COULD_ACTIVATE": "Yes.",
    ":YES": "Yes",
    ":CREATE_PO_ASSETS_CONFIRM": "This will create bibliographic, call number, and copy records for this purchase order in the ILS.\n\nContinue?",
    ":NEW_INVOICE": "New Invoice",
    ":PO_CANCEL_CONFIRM": "Are you SURE you want to cancel this purchase order?",
    ":LI_CREATING_ASSETS": "Creating bib, call number, and copy records...",
    ":PO_CHECKING": "[One moment...]",
    ":CANCEL_REASON": "Cancel reason",
    ":ACQ_SEARCH_CLASS_ABBR_jub": "LI",
    ":PO_ALREADY_ACTIVATED": "Activated",
    ":UR_FILTER_USER": "Enter barcode for user (or leave blank to unset the filter):",
    ":DUPE_PO_NAME_LINK": "View PO",
    ":NO_LI_TO_CLAIM": "You have not selected any lineitems to claim.",
    ":ACTIVATE_DEBITS_ACCRUED_PROCESSED": "Debits Encumbered: ${0}",
    ":UR_CANCEL_CONFIRM": "Are you SURE you want to cancel this user request?",
    ":FUND_LIST_ROLLOVER_SUMMARY": "Fund Propagation &amp; Rollover Summary for Fiscal Year ${0}",
    ":PRINT": "Print",
    ":UNRECEIVE_LID": "Are you sure you want to mark this copy as UN-received?",
    ":LI_ATTR_SEARCH_CHOOSE_FILE": "Select file with search terms",
    ":INVOICE_CONFIRM_PRORATE": "Prorate charges?\n\nAny subsequent changes to the invoice that would affect prorated amounts should be resolved manually.",
    ":INVOICE_ITEM_PO_DETAILS": "<b>${0}</b><br/><a href='${1}/acq/po/view/${2}'>PO #${3} ${4}</a><br/>Total Estimated Cost: $${5}",
    ":COULD_NOT_DELETE_MAPPING": "Error removing tag from fund.",
    ":ACTIVATE_LI_PROCESSED": "Lineitems Processed: ${0}",
    ":ITS_YOU": "You",
    ":ACTIVATE_COPIES_PROCESSED": "Real Copies Processed: ${0}",
    ":LIBRARY_INITIATED": "Library Initiated",
    ":DFA_TIP": "<strong>Applied by</strong>: ${0}<br /><strong>When</strong>: ${1}",
    ":PO_STOP_BLOCKS_ACTIVATION": "No; fund ${0} (${1}) would be encumbered beyond its stop level.",
    ":FUND_LIST_ROLLOVER_SUMMARY_ROLLOVER_AMOUNT": "<b>$${1}</b> unspent money rolled over to fiscal year ${0} for the selected locations",
    ":ADD_LI_TO_PO_BAD_LI_STATE": "The selected lineitem is not in a state that can be added to a purchase order",
    ":INVOICE_NUMBER": "Invoice #${0}",
    ":EXPORT_SAVE_DIALOG_TITLE": "Save field values to a file",
    ":INVOICE_EXTRA_COPIES": "You are attempting to invoice <b>${0}</b> more copies than originally ordered.  <br/><br/>To add these items to the original order, select a fund and choose 'Add New Items' below.  <br/>After saving the invoice, you may finish editing and importing the new copies from the lineitem details page.",
    ":UNNAMED": "Unnamed",
    ":VENDOR_SAYS_PREPAY_NEEDED": "The selected vendor requires prepayment, according to records.\nProceed anyway without required prepayment on this PO?",
    ":LI_CANCEL_CONFIRM": "Are you SURE you want to cancel this line item?",
    ":RESET_FORMULAE": "Reset Formulas",
    ":DEL_LI_FROM_PO": "That item has already been ordered!  Deleting it now will not revoke or modify any order that has been placed with a vendor.  Deleting the item may put the system's idea of your purchase order in a state that is inconsistent with reality.  Are you sure you mean to do this?",
    ":EXPORT_SHORT_LIST": "Not all of the selected items had the attribute '${0}'.\nChoose OK to save those values that could be found.",
    ":ACQ_SEARCH_CLASS_ABBR_acqlia": "LIA",
    ":CONFIRM_FUNDS_AT_STOP": "One or more of the selected funds has a balance below its stop level.\nYou may not be able to activate purchase orders incorporating these copies.\nContinue?",
    ":EXPLAIN_DFA_MGMT": "Remove record of this distribution formula usage?",
    ":ACQ_SEARCH_CLASS_ABBR_acqlid": "LID",
    ":APPLY": "Apply",
    ":ACTIVATE_VQBR_PROCESSED": "Vandelay Records Processed: ${0}",
    ":ACTIVATE_BIBS_PROCESSED": "Bib Records Merged/Imported: ${0}",
    ":DFA_NOT_ALL": "Could not record all of your applications of distribution formulas.",
    ":FUND_NOT_YET_LOADED": "Fund not yet loaded. Try coming back to this display later.",
    ":NO_RESULTS": "No results.",
    ":NO_LI_GENERAL": "You have not selected any (suitable) line items.",
    ":NUM_CLAIMS_EXISTING": "Claims (${0} existing)",
    ":COPIES_TO_RECEIVE": "Number of copies to receive: ",
    ":LI_ATTR_SEARCH_TOO_LARGE": "That file is too large for this operation.",
    ":NOT_RECVD": "Not recv'd",
    ":ACTIVATE_LID_PROCESSED": "ACQ Copies Processed: ${0}",
    ":NO_LI_TO_UPDATE": "You have not selected any lineitems to claim.",
    ":LI_FORMAT_ERROR": "Unexpected error retrieving formatted lineitem information.",
    ":NO": "No",
    ":UR_FILTER_LINEITEM": "Enter id for lineitem (or leave blank to unset the filter):",
    ":RECVD": "Recv'd",
    ":JUST_NOW": "Just now",
    ":LOAD_TERMS_FIRST": "You can't retrieve records until you've loaded a CSV file\nwith bibliographic IDs in the first column.",
    ":VENDOR_SAYS_PREPAY_NOT_NEEDED": "The selected vendor does not necessarily require prepayment, according\nto records. Require prepayment on this PO anyway?",
    ":PO_ACTIVATED_ON": "Activated ${0}",
    ":CONFIRM_DELETE_MAPPING": "Are you sure you want to remove this tag from this fund?",
    ":UNRECEIVE_LI": "Are you sure you want to mark this lineitem as UN-received?",
    ":LI_BATCH_UPDATE": "Line item batch update",
    ":INVOICE_ITEM_PO_LABEL": "<b>${0}</b><br/><a href='${1}/acq/po/view/${2}'>PO #${3} ${4}</a><br/>Total Estimated Cost: $${5}",
    ":CONFIRM_LI_ALERT": "An alert has been placed on the lineitem titled,\n\"${0}\":\n\n${1}\n${2}\n${3}\nChoose OK if you wish to acknowledge this alert.",
    ":CHANGE_CLAIM_POLICY": "Change claim policy",
    ":PO_FUND_WARNING_CONFIRM": "Are you sure? Did you see the warning about over-encumbering a fund?",
    ":INVOICE_CONFIRM_ENTRY_DETACH": "Remove $${0} charge for item '${1}, ${2} [${3}] from the invoice?",
    ":ADD_LI_TO_PO_BAD_PO_STATE": "The selected PO has already been activated",
    ":INVOICE_COPY_COUNT_INFO": "Copies received on this invoice: ${0} out of ${1}.",
    ":LINEITEM_SUMMARY": "<div class='acq-lineitem-summary'><a href='${19}'>${0}</a>, by ${1} (${2})</div>\n<div class='acq-lineitem-summary-extra'>\n${3} Ordered, ${4} Received, ${7} Invoiced, ${8} Claimed, ${9} Cancelled</div>\n<div class='acq-lineitem-summary-extra'>Estimated $${6}, Encumbered $${16}, Paid $${17}</div>\n<div class='acq-lineitem-summary-extra'>\n# ${10} <a style='padding-right: 10px;' class='hidden${20}'  href='${11}/acq/po/view/${12}'>&#x2318; ${13} ${18}</a>\n<a style='padding-right: 10px;' class='hidden${21}' href='${11}/acq/picklist/view/${14}'>&#x2756; ${15}</a></div>",
    ":CONFIRM_FUNDS_AT_WARNING": "One or more of the selected funds has a balance below its warning level.\nContinue?",
    ":ROLLBACK_LI_RECEIVE_CONFIRM": "This will rollback receipt of all copies for this purchase order.\n\nContinue?",
    ":ACQ_SEARCH_CLASS_ABBR_acqpo": "PO",
    ":ACQ_SEARCH_CLASS_ABBR_acqpl": "SL",
    ":INVOICE_CONFIRM_ITEM_DELETE": "Remove this $${0} '${1}' charge from the invoice?",
    ":ALERT_UNSELECTED": "You must choose an alert code.",
    ":NO_LID_TO_CLAIM": "You have not selected any lineitem details to claim.",
    ":INVOICES": "Invoices",
    ":INVOICE_ITEM_DETAILS": "${0} <br/> ${1} <br/> ${2}. <br/> Estimated Price: $${3}. <br/> Lineitem ID: ${4} <br/> PO: ${5} <br/> Order Date: ${6}",
    ":ACQ_SEARCH_CLASS_ABBR_acqinv": "I",
    ":SELECT_AN_LI_ATTRIBUTE": "You must select an LI attribute."
}