{
    ":CAPTURE_BRESV_DATES": "Datum der Vormerkung:",
    ":AUTHOR": "Autor",
    ":PRINTED_BY": "Gedruckt von",
    ":TITLE": "Titel",
    ":CAPTURE_CAUSES_TRANSIT": "This item is now in transit!",
    ":AUTO_ATTR_VALUE_capture": "Erfassen",
    ":CAPTURE_TRANSIT_SOURCE": "Von:",
    ":BARCODE": "Strichcode",
    ":TRANSIT": "*** TRANSIT ***",
    ":SUCCESS": "Aufnahme erfolgreich",
    ":CAPTURE_BRESV_PICKUP_LIB": "Pickup library:",
    ":DURATION": "Reserviert von",
    ":HERES_WHAT_WE_KNOW": "The following information is available about the failed capture:",
    ":AUTO_resource_barcode": "Barcode eingeben:",
    ":NEEDS_ROUTED_TO": "This item need to be routed to",
    ":RESERVATION_SHELF": "RESERVATION SHELF",
    ":PRINT": "<u>P</u>rint",
    ":CAPTURE_INFO": "Capture Information",
    ":NO_PAYLOAD": "We did not receive further information from the server about this attempt to capture.",
    ":CAPTURE_TRANSIT_DEST": "An:",
    ":SLIP_DATE": "Slip date",
    ":AT": "auf",
    ":CAPTURED_NOTHING": "Es wurde nichts erfasst.",
    ":RESERVED": "F\u00fcr Kunde Vorgemerkt",
    ":CAPTURE_BRESV_BRSRC": "Quelle f\u00fcr den Barcode",
    ":PRINT_ACCESSKEY": "P",
    ":AUTO_capture_heading": "Capture Reserved Resources",
    ":REQUEST": "Request time",
    ":UNKNOWN_PROBLEM": "An unknown problem occurred during capture attempt.",
    ":FAILURE": "Aufnahme fehlgeschlagen",
    ":AUTO_pickup_lib_selector": "Pickup library:"
}