{
    ":COPY_ALERT": "${0}:\n${1}\n\nDo you wish to process it anyway?",
    ":AUTO_patron": "Bibliotheksnutzer",
    ":NO_PATRON_BARCODE": "Please enter a patron barcode.",
    ":RETURN_NO_RESPONSE": "No response from server when attempting return.",
    ":ADDRESS": "${0}\n${1}\n${2}, ${3} ${4}",
    ":AUTO_no_in_bresv": "Patron has not returned any resources today.",
    ":AUTO_ready_bresv": "Es stehen folgende Reservierungen f\u00fcr den Bibliotheksnutzer zur Abholung bereit:",
    ":AUTO_ATTR_VALUE_pickup": "Abholen",
    ":AUTO_resource": "Quelle",
    ":AUTO_in_bresv": "Patron has returned these resources today:",
    ":RETURN_SUCCESS": "R\u00fcckgabe erfolgreich.",
    ":RESERVATIONS_ERROR": "Error communicating with server (asking for reservations):",
    ":AUTO_out_bresv": "Patron currently has these reservations out:",
    ":NO_SUCH_RETURNABLE_RESOURCE": "No such returnable resource.",
    ":AUTO_no_ready_bresv": "Es stehen derzeit keine Reservierungen f\u00fcr den Bibliotheksnutzer zur Abholung bereit.",
    ":AUTO_patron_barcode": "Enter patron barcode:",
    ":AUTO_return_h1": "Reservations Return",
    ":AUTO_ATTR_VALUE_return": "R\u00fcckgabe",
    ":PICKUP_NO_RESPONSE": "No response from server when attempting pickup.",
    ":RETURN_ERROR": "Error communicating with server (attempting return):",
    ":PICKUP_ERROR": "Error communicating with server (attempting pickup):",
    ":RETURNABLE_RESOURCE_ERROR": "Error looking up returnable resource:",
    ":RESERVATIONS_NO_RESPONSE": "No response from server when asking for reservations.",
    ":AUTO_ATTR_VALUE_reset": "Clear / New Patron",
    ":SELECT_SOMETHING": "Sie haben keine Reservierung ausgew\u00e4hlt.",
    ":AUTO_barcode_type": "Return by barcode of",
    ":AUTO_ATTR_VALUE_go": "Los",
    ":NOTICE_CHANGE_OF_PATRON": "Note that the resource scanned was out on reservation to a different\npatron than the last resource you scanned.  If this is not\nexpected, stop to examine outstanding reservations for your patron\nor on the resource.",
    ":AUTO_no_out_bresv": "Es stehen derzeit keine Reservierungen f\u00fcr den Bibliotheksnutzer aus.",
    ":AUTO_h1": "Reservations Pickup"
}