{
    ":CAPTURE_BRESV_DATES": "Erikoisvarauksen aika:",
    ":AUTHOR": "Tekij\u00e4",
    ":PRINTED_BY": "Tulostanut:",
    ":TITLE": "Nimeke",
    ":CAPTURE_CAUSES_TRANSIT": "T\u00e4m\u00e4 nide on kuljetettavana!",
    ":AUTO_ATTR_VALUE_capture": "Kiinnit\u00e4",
    ":CAPTURE_TRANSIT_SOURCE": "L\u00e4hett\u00e4j\u00e4:",
    ":BARCODE": "Tunnus",
    ":TRANSIT": "*** KULJETETTAVANA ***",
    ":SUCCESS": "Kiinnitys onnistui",
    ":CAPTURE_BRESV_PICKUP_LIB": "Noutokirjasto:",
    ":DURATION": "Varattu kohteesta",
    ":HERES_WHAT_WE_KNOW": "Ep\u00e4onnistuneesta kiinnityksest\u00e4 on saatavilla seuraavat tiedot:",
    ":AUTO_resource_barcode": "Sy\u00f6t\u00e4 tunnus:",
    ":NEEDS_ROUTED_TO": "T\u00e4m\u00e4 nide on kuljetettava kohteeseen",
    ":RESERVATION_SHELF": "VARAUSHYLLY",
    ":PRINT": "Tulosta (<u>P</u>)",
    ":CAPTURE_INFO": "Kiinnitystiedot",
    ":NO_PAYLOAD": "Palvelin ei antanut muita tietoja t\u00e4st\u00e4 kiinnitysyrityksest\u00e4.",
    ":CAPTURE_TRANSIT_DEST": "Vastaanottaja:",
    ":SLIP_DATE": "Liuskan p\u00e4iv\u00e4ys",
    ":AT": "kohteessa",
    ":CAPTURED_NOTHING": "Mit\u00e4\u00e4n ei kiinnitetty.",
    ":RESERVED": "Varattu asiakkaalle",
    ":CAPTURE_BRESV_BRSRC": "Aineiston tunnus:",
    ":PRINT_ACCESSKEY": "P",
    ":AUTO_capture_heading": "Kiinnit\u00e4 varatut aineistot",
    ":REQUEST": "Pyynt\u00f6aika",
    ":UNKNOWN_PROBLEM": "Kiinnitysyrityksess\u00e4 ilmeni tuntematon ongelma.",
    ":FAILURE": "Kiinnitys ep\u00e4onnistui",
    ":AUTO_pickup_lib_selector": "Noutokirjasto:"
}