{
    ":COPY_ALERT": "${0}:\n${1}\n\nHaluatko k\u00e4sitell\u00e4 sen t\u00e4st\u00e4 huolimatta?",
    ":AUTO_patron": "Asiakas",
    ":NO_PATRON_BARCODE": "Sy\u00f6t\u00e4 asiakastunnus.",
    ":RETURN_NO_RESPONSE": "Palvelin ei vastannut palautusta yritett\u00e4ess\u00e4.",
    ":ADDRESS": "${0}\n${1}\n${2}, ${3} ${4}",
    ":AUTO_no_in_bresv": "Asiakas ei ole t\u00e4n\u00e4\u00e4n palauttanut mit\u00e4\u00e4n aineistoja.",
    ":AUTO_ready_bresv": "Seuraavat erikoisvaraukset ovat noudettavissa:",
    ":AUTO_ATTR_VALUE_pickup": "Nouto",
    ":AUTO_resource": "Aineisto",
    ":AUTO_in_bresv": "Asiakas on t\u00e4n\u00e4\u00e4n palauttanut seuraavat aineistot:",
    ":RETURN_SUCCESS": "Palautus onnistui.",
    ":RESERVATIONS_ERROR": "Virhe palvelinyhteydess\u00e4 (erikoisvarauskysely):",
    ":AUTO_out_bresv": "Asiakkaalla on t\u00e4ll\u00e4 hetkell\u00e4 seuraavat varaukset:",
    ":NO_SUCH_RETURNABLE_RESOURCE": "Palautettavaa aineistoa ei ole.",
    ":AUTO_no_ready_bresv": "Asiakkaalla ei t\u00e4ll\u00e4 hetkell\u00e4 ole noudettavia erikoisvarauksia.",
    ":AUTO_patron_barcode": "Sy\u00f6t\u00e4 asiakastunnus:",
    ":AUTO_return_h1": "Erikoisvarausten palautus",
    ":AUTO_ATTR_VALUE_return": "Palaa",
    ":PICKUP_NO_RESPONSE": "Palvelin ei vastannut noutoa yritett\u00e4ess\u00e4.",
    ":RETURN_ERROR": "Virhe palvelinyhteydess\u00e4 (palautusyritys):",
    ":PICKUP_ERROR": "Virhe palvelinyhteydess\u00e4 (noutoyritys):",
    ":RETURNABLE_RESOURCE_ERROR": "Virhe palautettavan aineiston etsinn\u00e4ss\u00e4:",
    ":RESERVATIONS_NO_RESPONSE": "Palvelin ei vastannut varauksia kysytt\u00e4ess\u00e4.",
    ":AUTO_ATTR_VALUE_reset": "Tyhjenn\u00e4 / Uusi asiakas",
    ":SELECT_SOMETHING": "Et ole valinnut yht\u00e4\u00e4n varausta.",
    ":AUTO_barcode_type": "Palauta tunnuksen perusteella",
    ":AUTO_ATTR_VALUE_go": "Siirry",
    ":NOTICE_CHANGE_OF_PATRON": "Huomaa, ett\u00e4 skannattu aineisto oli varattuna eri asiakkaalle\nkuin viimeisin skannaamasi aineisto. Jos n\u00e4in ei pit\u00e4isi olla,\ntarkista asiakkaasi tai aineiston\nvoimassa olevat varaukset.",
    ":AUTO_no_out_bresv": "Asiakkaalla ei t\u00e4ll\u00e4 hetkell\u00e4 ole muita erikoisvarauksia.",
    ":AUTO_h1": "Erikoisvarausten nouto"
}