{
    ":AUTO_ATTR_VALUE_print": "Tulosta",
    ":AUTO_owning_lib_selector": "N\u00e4yt\u00e4 varauslista kirjastolle:",
    ":AUTO_th_resv_details": "Varaustiedot",
    ":COPY_LOOKUP_NO_RESPONSE": "Ei vastausta hakiessa niteit\u00e4 tunnuksella",
    ":COPY_LOOKUP_ERROR": "Virhe hakiessa niteit\u00e4 tunnuksella: ",
    ":AUTO_ATTR_VALUE_fetch": "Hae",
    ":AUTO_th_barcode": "Nidetunnus",
    ":PULL_LIST_ERROR": "Virhe haettaessa varauslistaa: ",
    ":AUTO_interval_in_days": "Luo luettelo n\u00e4in monta p\u00e4iv\u00e4\u00e4 eteenp\u00e4in: ",
    ":PULL_LIST_NO_RESPONSE": "Palvelin ei vastaa haettaessa varauslistaa!",
    ":COPY_MISSING": "Odottamaton virhe: Ei tietoja niteelle: ",
    ":AUTO_th_pickup_lib": "Noutokirjasto",
    ":FOR": "kohteelle",
    ":AUTO_th_copy_location": "Nidesijanti",
    ":AUTO_th_title_or_name": "Nimeke tai tekij\u00e4",
    ":AUTO_no_results": "Ei tuloksia.",
    ":AT": "kohteessa",
    ":AUTO_th_call_number": "Hyllypaikka",
    ":AUTO_pull_list_title": "Erikoisvarauslista"
}