{
    ":modifier_default": "-- Select a Modifier --",
    ":metabib": "Metarecord Search",
    ":site": "Site",
    ":depth": "Search Depth",
    ":new_modifier": "New Modifier",
    ":filter_default": "-- Select a Filter --",
    ":item_form": "Formulari",
    ":during": "In Publication",
    ":more": "Mai encara...",
    ":filters": "Filtratge",
    ":new_filter": "Filtre nov\u00e8l",
    ":advanced": "Detalhs avan\u00e7ats",
    ":faceted_searches": "Facets",
    ":contains": "Conten",
    ":basic": "Basic",
    ":lit_form": "Literary Form",
    ":format": "Type and Form",
    ":classed_searches": "Classed Searches",
    ":ascending": "Triar d'un biais ascendent",
    ":notcontains": "Conten pas",
    ":or": "O",
    ":vr_format": "Videorecording Format",
    ":new_facet": "New Facet",
    ":bib_level": "Bibliographic Level",
    ":item_type": "Tipe",
    ":remove": "Suprimir",
    ":staff": "Staff Search",
    ":modifiers": "Modificadors",
    ":perform_search": "Anem !",
    ":audience": "Public cibla",
    ":exact": "Exactly Matches",
    ":and": "E",
    ":available": "Disponible",
    ":between": "Published Between",
    ":before": "Published Before",
    ":statuses": "Estatuts",
    ":less": "...Less",
    ":after": "Published After",
    ":sort": "Sort Axis",
    ":descending": "Triar d'un biais descendent"
}