{
    ":CLONE_SESSION_NAME": "Kopie von ${0}",
    ":EDIT": "Bearbeiten",
    ":SELECT_MORE": "Click here to review all session URLs and/or select other URLs to verify",
    ":MARC_EDITOR_LINK": "Click to open MARC Editor for this record",
    ":NEED_UVUS": "You must add some tag and subfield combinations.",
    ":REDIRECTING": "Loading next interface ...",
    ":VERIFY_ALL": "Click 'OK' to verify ALL the URLs that belong to this session and match all your search terms.  Click 'Cancel' if the selected, visible URLs are the only ones you want verified.",
    ":XPATH": "XPath",
    ":REREVIEW": "\u00d6ffnen",
    ":REVIEW_ATTEMPT": "Review this verification attempt",
    ":INTERFACE_SETUP": "Interface wird eingestellt ...",
    ":VERIFICATION_DIALOG": "\u00dcberpr\u00fcfe URLs ...",
    ":CLONING": "Existierende Sitzung wird geklont ...",
    ":CREATING": "Sitzung wird erstellt",
    ":VERIFICATION_ATTEMPT_ID": "Verifikationsversuchs-ID: ${0}",
    ":SESSION_NAME": "Sitzung '${0}'",
    ":CLONE_SESSION": "Klonen",
    ":EXTRACTING_URLS": "Extracting URLs ...",
    ":SAVING_TAGS": "Saving tag/subfield selectors ...",
    ":MARC_EDITOR_TITLE": "Aufnahme-ID #${0}",
    ":MARC_EDITOR_SAVE_RECORD": "Aufnahme speichern",
    ":NOTHING_SELECTED": "Es wurden keine Zeilen ausgew\u00e4hlt, also wird auch keine Aktion ausgef\u00fchrt.",
    ":PERFORMING_SEARCH": "Suche wird aufgef\u00fchrt ..."
}