{
    ":OPERATOR_GTE": "ist gr\u00f6\u00dfer als oder gleich",
    ":ADD_ROW": "Zeile hinzuf\u00fcgen",
    ":DEFAULT_DIALOG_TITLE": "Ergebnisse filtern",
    ":CANCEL": "Abbrechen",
    ":OPERATOR_EQ": "ist",
    ":OPERATOR_GT": "ist gr\u00f6\u00dfer als",
    ":OPERATOR_IN": "ist in der Menge",
    ":NEED_NAME": "Sie m\u00fcssen einen Namen f\u00fcr die gespeicherten Filter eingeben.",
    ":OPERATOR_NOT_LIKE": "ist nicht wie",
    ":OPERATOR_LTE": "ist kleiner als oder gleich",
    ":CHOOSE_FILTER_TO_LOAD": "W\u00e4hlen Sie die zu ladenden Filters\u00e4tze",
    ":EMPTY_CASE_COMPACT": "F\u00fcgen Sie Zeilen hinzu, um Ergebnisse zu filtern.",
    ":OPERATOR_IS_NULL": "ist Null",
    ":OPERATOR_LIKE": "ist wie",
    ":OPERATOR_BETWEEN": "ist zwischen",
    ":EMPTY_CASE": "F\u00fcgen Sie Zeilen hinzu um Ergebnisse zu filtern, oder klicken Sie einfach auf Anwenden um ungefilterte Ergebnisse anzuzeigen.",
    ":APPLY": "Anwenden",
    ":OPERATOR_NOT_IN": "ist nicht in der Menge",
    ":OPERATOR_IS_NOT_NULL": "ist nicht null",
    ":LOAD_FILTERS": "Filter laden",
    ":NAME_SAVED_FILTER_SET": "Geben Sie einen Namen f\u00fcr den gespeicherten Filtersatz ein:",
    ":OPERATOR_NE": "ist nicht",
    ":EMPTY_LIST": "Suchfilter kann nicht erstellt werden. Leere Listen nicht erlaubt.",
    ":SAVE_FILTERS": "Filter speichern",
    ":OPERATOR_NOT_BETWEEN": "ist nicht zwischen",
    ":OPERATOR_LT": "ist weniger als"
}