{
    ":modifier_default": "-- Einen Modifikator ausw\u00e4hlen --",
    ":metabib": "Metarecord Search",
    ":site": "Seite",
    ":depth": "Search Depth",
    ":new_modifier": "Neuer Modifikator",
    ":filter_default": "-- W\u00e4hlen Sie einen Filter --",
    ":item_form": "Formular",
    ":during": "In Publication",
    ":more": "Mehr...",
    ":filters": "Filter",
    ":new_filter": "Neuer Filter",
    ":advanced": "Erweitert",
    ":faceted_searches": "Aspekte",
    ":contains": "Beinhaltet",
    ":basic": "Allgemein",
    ":lit_form": "Literaturform",
    ":format": "Type and Form",
    ":classed_searches": "Classed Searches",
    ":ascending": "Absteigend sortieren",
    ":notcontains": "Enth\u00e4lt nicht",
    ":or": "ODER",
    ":vr_format": "Videorecording Format",
    ":new_facet": "New Facet",
    ":bib_level": "Bibliographic Level",
    ":item_type": "Typ",
    ":remove": "Entfernen",
    ":staff": "Staff Search",
    ":modifiers": "Modifikatoren",
    ":perform_search": "Start!",
    ":audience": "Empf\u00e4nger",
    ":exact": "Genaue \u00dcbereinstimmungen",
    ":and": "UND",
    ":available": "Verf\u00fcgbar",
    ":between": "Ver\u00f6ffentlicht bevor dem",
    ":before": "Ver\u00f6ffentlicht bevor dem",
    ":statuses": "Status",
    ":less": "...Weniger",
    ":after": "Ver\u00f6ffentlicht nach dem",
    ":sort": "Sort Axis",
    ":descending": "Absteigend sortieren"
}