{
    ":LABEL_NEW_BRANCH": "New Branch",
    ":CONFIRM_DELETE": "Are you sure you want to delete ${0}?",
    ":CBHO_NEEDS_NAME": "You need to enter a name for the best-hold order.",
    ":ACQ_DISTRIB_FORMULA_NAME_CLONE": "${0} (Clone)",
    ":CONFIRM_EXIT_PPL": "There are unsaved modified permissions. Click OK to save these changes, or Cancel to abandon them.",
    ":ERROR_FETCHING_HOURS": "Problem fetching hours of operation for ${0}",
    ":CONFIRM_EXIT_AOU": "There are unsaved changes to one or more organisational units. Click OK to save these changes, or Cancel to abandon them.",
    ":ERROR_FETCHING_TYPES_AOUT": "Problem fetching organisational unit types",
    ":SUCCESS_SAVING_PHYSICAL": "Saved changes to the Physical Address of ${0}",
    ":SUCCESS_CREATING_CHILD_AOUT": "New child Organisation Type created for ${0}",
    ":ERROR_SAVING_ILL": "Problem saving ILL Address data for ${0}",
    ":ACQ_DISTRIB_FORMULA_NAME_PROMPT": "Enter new formula name",
    ":CONFIRM_EXIT_PGT": "There are unsaved modified permission maps. Click OK to save these changes, or Cancel to abandon them.",
    ":ERROR_SAVING_HOLDS": "Problem saving Holds Address data for ${0}",
    ":NAME": "Name",
    ":ERROR_FETCHING_ORGS": "Problem fetching organisational unit data",
    ":ERROR_FETCHING_PERM_MAPS": "Problem fetching perm maps",
    ":ERROR_CALLING_METHOD_PERM_MAP": "Problem calling method to create new permission map",
    ":ERROR_FETCHING_ILL": "Problem fetching ILL Address for ${0}",
    ":LABEL_DESCRIPTION": "Description",
    ":SURVEY_QUESTION": "Question:",
    ":ERROR_FETCHING_PHYSICAL": "Problem fetching Physical Address for ${0}",
    ":SUCCESS_NEW_CHILD_GROUP": "New child Group created for ${0}",
    ":HOLDABLE": "Holdable",
    ":ERROR_FETCHING_PERMS": "Problem fetching perms",
    ":LABEL_VALUE": "Value",
    ":ERROR_CALLING_METHOD_AOUT": "Problem calling method to create child organisation type",
    ":ERROR_SAVING_PHYSICAL": "Problem saving Physical Address data for ${0}",
    ":SUCCESS_SAVING_ILL": "Saved changes to the ILL Address of ${0}",
    ":ERROR_FETCHING_HOLDS": "Problem fetching Holds Address for ${0}",
    ":ID": "ID",
    ":ERROR_FETCHING_STATUSES": "Problem fetching statuses",
    ":ERROR_CALLING_METHOD_PPL": "Problem calling method to create new permission",
    ":ERROR_CALLING_METHOD_CCS": "Problem calling method to create new copy status",
    ":IS_AVAILABLE": "Is Available",
    ":SURVEY_ADD_ANSWER": "Add Answer",
    ":SURVEY_DELETE_QUESTION": "Delete Question & Answers",
    ":LABEL_DEPTH": "Depth",
    ":LABEL_NEW_TYPE": "New Type",
    ":LABEL_NEW_GROUP": "New Group",
    ":STATUS_DELETED": "${0} deleted",
    ":SUCCESS_DELETED_PERM_MAP": "Permission mapping deleted",
    ":ERROR_CREATING_CHILD_AOUT": "Problem creating child organisation type",
    ":STATUS_EDITING": "Now editing ${0}",
    ":SUCCESS_CREATING_PERMISSION": "New ${0} permission created",
    ":SUCCESS_CREATING_STATUS": "New ${0} status created",
    ":ERROR_SAVING_DATA_CAM": "Problem saving data for ${0} ${1}",
    ":CBHO_EDITING_EXISTING": "You are editing best-hold order #${0}: ${1}.",
    ":OPAC_VISIBLE": "OPAC Visible",
    ":SURVEY_SAVE_ADD": "Save Question & Add Answer",
    ":ERROR_CREATING_PERM_MAP": "Problem creating new Permission Map",
    ":SUCCESS_SAVING_HOLDS": "Saved changes to the Holds Address of ${0}",
    ":ERROR_SAVING_PERM_DATA": "Problem saving permission data for ${0}",
    ":LABEL_GRANTABLE": "Grantable",
    ":ERROR_ORPHANS": "Cannot delete ${0}, ${1} subordinates still exist.",
    ":ERROR_CREATING_STATUS": "Problem creating new Status",
    ":ERROR_CALLING_METHOD_CAM": "Problem calling method to create new ${0}",
    ":ERROR_CALLING_METHOD_PGT": "Problem calling method to create child Group",
    ":ERROR_FETCHING_GROUPS": "Problem fetching groups",
    ":SURVEY_SAVE_CHANGES": "Save Changes",
    ":LABEL_CODE": "Code",
    ":SURVEY_DELETE_ANSWER": "Delete Answer",
    ":SUCCESS_SAVE_PERM": "Saved permission changes to ${0}",
    ":SURVEY_FOOT_LABEL": "Questions & Answers",
    ":COPY_ACTIVE": "Sets copy active",
    ":SUCCESS_CREATING_CHILD_AOU": "New child Organisational Unit created for ${0}",
    ":SUCCESS_SAVING_DATA": "Saved changes to ${0}",
    ":TRANSLATION": "Translation",
    ":ERROR_DELETING_PERM_MAPPING": "Problem deleting permission mapping ${0}",
    ":CBHO_NO_LOAD": "Unable to load selected item.",
    ":SUCCESS_SAVING_HOO": "Hours of Operation updated for ${0}",
    ":ERROR_CREATING_CHILD_GROUP": "Problem creating child Group",
    ":ERROR_SAVING_MAILING": "Problem saving Mailing Address data for ${0}",
    ":ERROR_CREATING_PERMISSION": "Problem creating new Permission",
    ":CONFIRM_EXIT_CAM": "There are unsaved changes to one or more ${0} codes. Click OK to save these changes, or Cancel to abandon them.",
    ":LABEL_TRANSLATION": "Translation",
    ":CBHO_EDITING_NEW": "You are editing a new best-hold order.",
    ":SURVEY_ANSWER": "Answer:",
    ":ERROR_SAVING_HOO": "Problem saving Hours of Operation data for ${0}",
    ":ERROR_DELETING_LAST_AOUT": "Cannot delete ${0}. You need at least one organisation type.",
    ":CBHO_FIELD_DISPLAY": "[${0}] ${1}",
    ":CONFIRM_UNSAVED_CHANGES": "There are unsaved changes to one or more organisation types. Click OK to save these changes, or Cancel to abandon them.",
    ":END_SURVEY": "End Survey Now",
    ":SUCCESS_NEW_PERM_MAP": "New permission map created",
    ":SURVEY_WARN_TEXT": "No questions can be modified or added at this time. The survey Start Date must be set for the future to add new questions or modify existing questions.",
    ":SUCCESS_SAVING_MAILING": "Saved changes to the Mailing Address of ${0}",
    ":ERROR_FETCHING_MAILING": "Problem fetching Mailing Address for ${0}",
    ":SUCCESS_CREATING_CODE": "New ${0} ${1} created",
    ":ERROR_DELETING": "Problem deleting ${0}",
    ":ERROR_CREATING_CHILD_AOU": "Problem creating child organisational unit",
    ":ERROR_DELETING_LAST_AOU": "Cannot delete ${0}, you need at least one organisation unit.",
    ":EVENT_DEF_LABEL": "${0}: ${1}",
    ":SURVEY_ID": "Survey ID # ${0}",
    ":ERROR_SAVING_STATUS": "Problem saving ${0}",
    ":SUCCESS_SAVE": "Saved changes to ${0}",
    ":CONFIRM_EXIT_CCS": "There are unsaved changes to one or more copy statuses. Click OK to save these changes, or Cancel to abandon them.",
    ":ERROR_SAVING_DATA": "Problem saving data for ${0}"
}