{
    ":TFORMS_LABEL_SUM": "Summe",
    ":TEMPLATE_CONF_SELECT_CANCEL": "Select the value, or cancel:",
    ":TRANSFORMS_SUM": "Summe",
    ":TFORMS_LABEL_FIRST5": "Erste 5 Ziffern (f\u00fcr US Postleitzahl)",
    ":TEMPLATE_CONF_DEFAULT": "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435  ${0}:",
    ":TRANSFORMS_MIN": "Min",
    ":TRANSFORMS_DATE": "Datum",
    ":OPERATORS_GT_EQUAL": "Gr\u00f6\u00dfer als oder gleich",
    ":FILTERS_LABEL_EQUALS": "Equals",
    ":TFORMS_LABEL_MIN": "Min",
    ":OPERATORS_LTE_TIME": "Am oder vor dem (Datum/Zeit)",
    ":TFORMS_LABEL_DOY": "Tag des Jahres",
    ":TRANSFORMS_AGE": "Alter",
    ":FILTERS_LABEL_NE_ANY": "Does Not Equal Any",
    ":TFORMS_LABEL_DOW": "Wochentag",
    ":FILTERS_LABEL_LT_TIME": "Vor dem (Datum/Zeit)",
    ":OPERATORS_EQ_ANY": "Equals Any",
    ":FOLDER_WINDOW_COLNAME_ALL": "Alle",
    ":LINK_NULLABLE_NONE": "Kein",
    ":FILTERS_LABEL_GT_EQUAL": "Gr\u00f6\u00dfer als oder gleich",
    ":RPT_BUILDER_CONFIRM_SAVE": "Name: $ {0}\nBeschreibung: $ {1}\nVorlage speichern?",
    ":TRANSFORMS_ROUND": "Round",
    ":TFORMS_LABEL_RAW_DATA": "Raw Data",
    ":OPERATORS_NULL_BLANK": "Is NULL or Blank",
    ":OPERATORS_EQUALS": "Equals",
    ":FOLDER_WINDOW_REPORT_OUTPUT": "Report Output: ${0}",
    ":TEMPLATE_CONF_CONFIRM_STATE": "Click OK for TRUE and Cancel for FALSE.",
    ":TFORMS_LABEL_AGE": "Alter",
    ":TEMPLATE_CONF_EQUALS": "Equals",
    ":TRANSFORMS_DAY_NAME": "\u0414\u0435\u043d\u044c \u043d\u0435\u0434\u0435\u043b\u0438",
    ":REPORT_EDITOR_REPORT_FOLDERS": "Report Folders",
    ":FILTERS_LABEL_LSE_TIME": "Am oder vor dem (Datum/Zeit)",
    ":FILTERS_LABEL_NOT_BETWEEN": "Nicht zwischen",
    ":TRANSFORMS_MAX": "Max",
    ":TFORMS_LABEL_HOD": "Hour of day",
    ":TRANSFORMS_YEAR_TRUNC": "Jahr",
    ":TFORMS_LABEL_COUNT_DISTINCT": "Count Distinct",
    ":TFORMS_LABEL_DAY_NAME": "\u0414\u0435\u043d\u044c \u043d\u0435\u0434\u0435\u043b\u0438",
    ":TEMPLATE_CONF_CONFIRM_SAVE": "Name: $ {0}\nBeschreibung: $ {1}\nVorlage speichern?",
    ":TEMPLATE_CONF_NO_MATCH": "Field does not match one of list (comma separated):",
    ":OPERATORS_LESS_THAN": "kleiner als",
    ":FOLDERS_TEMPLATES": "Vorlagen",
    ":OPERATORS_NOT_BETWEEN": "Nicht zwischen",
    ":TFORMS_LABEL_MAX": "Max",
    ":FILTERS_LABEL_GTE_TIME": "Am oder nach dem (Datum/Zeit)",
    ":TFORMS_LABEL_MONTH_TRUNC": "Jahr + Monat",
    ":TRANSFORMS_DOM": "Tag des Monats",
    ":WIDGET_YEARS": "Jahr(e)",
    ":OPERATORS_GT_TIME": "Nach dem (Datum/Zeit)",
    ":TFORMS_LABEL_QUARTERS_AGO": "Quarters ago",
    ":TRANSFORMS_DOW": "Wochentag",
    ":TEMPLATE_CONF_IN": "Field matches one of list (comma separated):",
    ":LINK_NULLABLE_DEFAULT": "Voreinstellung",
    ":OPERATORS_NOT_NULL_BLANK": "Is not NULL or Blank",
    ":WIDGET_QUARTERS": "Quartal(e)",
    ":TRANSFORMS_DOY": "Tag des Jahres",
    ":FILTERS_LABEL_NOT_IN": "Not in list",
    ":TRANSFORMS_QOY": "Quartal",
    ":FOLDER_WINDOW_COLNAME_SELECT": "Ausw\u00e4hlen",
    ":OPERATORS_IS_NOT_NULL": "Ist nicht NULL",
    ":TFORMS_LABEL_LAST": "Letzter Wert",
    ":SOURCE_BROWSE_AGGREGATE": "Zusammenf\u00fchren",
    ":TRANSFORMS_LAST": "Letzter Wert",
    ":TFORMS_LABEL_WOY": "Woche eines Jahres",
    ":TEMPLATE_CONF_BARE": "Bare",
    ":FOLDER_WINDOW_CHANGE_FOLDERS": "Ordner \u00e4ndern",
    ":FILTERS_LABEL_NULL_BLANK": "Is NULL or Blank",
    ":OPERATORS_NE_ANY": "Does Not Equal Any",
    ":REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Please provide an output folder",
    ":SOURCE_BROWSE_NON_AGGREGATE": "Non-Aggregate",
    ":TRANSFORMS_COUNT_DISTINCT": "Count Distinct",
    ":TRANSFORMS_FIRST": "Erster Wert",
    ":TEMPLATE_CONF_SUCCESS_SAVE": "Vorlage ${0} wurde erfolgreich gespeichert.",
    ":FILTERS_LABEL_GT_TIME": "Nach dem (Datum/Zeit)",
    ":TRANSFORMS_QUARTERS_AGO": "Quarters ago",
    ":OPERATORS_LT_TIME": "Vor dem (Datum/Zeit)",
    ":TFORMS_LABEL_MONTH_NAME": "Monatsname'",
    ":TRANSFORMS_INT": "Drop trailing decimals",
    ":OPERATORS_LT_EQUAL": "kleiner oder gleich",
    ":FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)",
    ":TRANSFORMS_MOY": "Month of Year",
    ":FILTERS_LABEL_LESS_THAN": "kleiner als",
    ":FOLDERS_TEMPLATE": "Vorlage",
    ":FILTERS_LABEL_LIKE": "Contains Matching substring",
    ":TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string",
    ":OPERATORS_ILIKE": "Contains Matching substring (ignore case)",
    ":LINK_NULLABLE_RIGHT": "Oberbegriff",
    ":FILTERS_LABEL_LT_EQUAL": "kleiner oder gleich",
    ":TRANSFORMS_SUBSTRING": "Substring",
    ":TRANSFORMS_MONTH_NAME": "Monatsname",
    ":OPERATORS_IN_LIST": "in Liste",
    ":TFORMS_LABEL_AVERAGE": "Durchschnitt",
    ":TRANSFORMS_LOWER": "Lower case",
    ":FOLDERS_REPORT": "Bericht",
    ":TFORMS_LABEL_DOM": "Tag des Monats",
    ":FILTERS_LABEL_IN": "in Liste",
    ":TEMPLATE_CONF_RAW_DATA": "Raw Data",
    ":TFORMS_LABEL_DATE": "Datum",
    ":TFORMS_LABEL_FIRST": "Erster Wert",
    ":TFORMS_LABEL_INT": "Drop trailing decimals",
    ":TFORMS_LABEL_UPPER": "Upper case",
    ":TEMPLATE_CONF_TRUE": "Wahr",
    ":TRANSFORMS_FIRST5": "Erste 5 Ziffern (f\u00fcr US Postleitzahl)",
    ":TRANSFORMS_HOUR_TRUNC": "Stunde",
    ":LINK_NULLABLE_LEFT": "Child",
    ":FILTERS_LABEL_NOT_NULL_BLANK": "Is not NULL or Blank",
    ":TRANSFORMS_MONTHS_AGO": "Months ago",
    ":TRANSFORMS_HOD": "Hour of day",
    ":SOURCE_SETUP_CORE_SOURCES": "Core Sources",
    ":REPORT_EDITOR_INVALID_DATE_ALERT": "Ung\u00fcltiges Startdatum - YYYY-MM-DD",
    ":FOLDER_WINDOW_SELECT_ITEM": "Bitte einen Eintrag aus der Liste ausw\u00e4hlen",
    ":TRANSFORMS_AVERAGE": "Durchschnitt",
    ":TFORMS_LABEL_LOWER": "Lower case",
    ":OPERATORS_NOT_IN_LIST": "Not in list",
    ":TEMPLATE_CONF_NOT_IN": "Field does not match one of list (comma separated):",
    ":TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Change the field hint to:",
    ":OPERATORS_LIKE": "Contains Matching substring",
    ":FOLDER_WINDOW_COLNAME_NONE": "Kein",
    ":TFORMS_LABEL_MONTHS_AGO": "Months ago",
    ":TFORMS_LABEL_YEAR_TRUNC": "Jahr",
    ":TRANSFORMS_UPPER": "Upper case",
    ":OPERATORS_IS_NULL": "Ist NULL",
    ":TFORMS_LABEL_COUNT": "Anzahl",
    ":FILTERS_LABEL_NOT_NULL": "Ist nicht NULL",
    ":WIDGET_MONTHS": "Monat(e)",
    ":TRANSFORMS_BARE": "Raw Data",
    ":WIDGET_REAL_DATE": "echte Date",
    ":SOURCE_SETUP_ALL_AVAIL_SOURCES": "All Available Sources",
    ":OPERATORS_GTE_TIME": "Am oder nach dem (Datum/Zeit)",
    ":REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Please change the report name",
    ":FILTERS_LABEL_GREATER_THAN": "Gr\u00f6\u00dfer als",
    ":TFORMS_LABEL_MOY": "Month of Year",
    ":FOLDERS_OUTPUT": "Ausgabe",
    ":REPORT_EDITOR_OUTPUT_FOLDERS": "Ausgabeordner",
    ":TEMPLATE_CONF_CONFIRM_RESET": "You have already added the [${0}] field\nfrom the [${1}] source. Click OK if you\nwould like to reset this field.",
    ":TRANSFORMS_FIRST_WORD": "First contiguous non-space string",
    ":FILTERS_LABEL_NULL": "Ist NULL",
    ":REPORT_EDITOR_ENTER_NAME_ALERT": "Geben Sie einen Berichtnamen ein",
    ":WIDGET_RELATIVE_DATE": "Relative Date",
    ":TEMPLATE_CONF_BOOLEAN_VALUE": "Boolescher Wert",
    ":TEMPLATE_CONF_BETWEEN": "Feldwert ist zwischen (durch Komma getrennt):",
    ":SOURCE_SETUP_CONFIRM_EXIT": "Sie haben angefangen eine Vorlage zu erstellen!",
    ":FOLDERS_REPORTS": "Berichte",
    ":TFORMS_LABEL_HOUR_TRUNC": "Stunde",
    ":FILTERS_LABEL_BETWEEN": "zwischen",
    ":REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Please provide a report folder",
    ":TEMPLATE_CONF_FALSE": "Falsch",
    ":TRANSFORMS_WOY": "Woche eines Jahres",
    ":OPERATORS_GREATER_THAN": "Gr\u00f6\u00dfer als",
    ":TEMPLATE_CONF_NOT_BETWEEN": "Feldwert ist zwischen (durch Komma getrennt):",
    ":TRANSFORMS_MONTH_TRUNC": "Jahr + Monat",
    ":TRANSFORMS_COUNT": "Anzahl",
    ":OPERATORS_BETWEEN": "zwischen",
    ":WIDGET_DAYS": "Tag(e)",
    ":FILTERS_LABEL_EQ_ANY": "Equals Any",
    ":TFORMS_LABEL_QOY": "Quartal",
    ":TFORMS_LABEL_ROUND": "Round",
    ":TEMPLATE_CONF_PROMPT_CHANGE": "Spaltenkopf \u00e4ndern auf: ${0}"
}