{
    ":CREATE_MFHD": "Add MFHD Record",
    ":OK": "D'ac\u00f2rdi",
    ":DELETE_MFHD_CONFIRM": "Are you sure you want to delete this serial record?",
    ":CANCEL_BUTTON_LABEL": "Abandonar",
    ":SUBMIT_BUTTON_LABEL": "Validar",
    ":BASIC_HOLDINGS_ADD": "Informacion suplement\u00e0ria",
    ":PWD_RESET_SUBMIT_ERROR": "The system could not process your request for a password reset. Please try again, or contact circulation staff for assistance.",
    ":PWD_RESET_SUBMIT_SUCCESS": "Your request to begin the password reset process has been processed. If your account has a valid email address, you should soon receive an email containing further instructions for resetting your password.",
    ":SAVE_MFHD_LABEL": "Save MFHD",
    ":CURRENT_HOLDINGS": "Volum actual",
    ":MORE": "Mai",
    ":MORE_COPIES_FULL_RECORD": "... more copies listed in full record",
    ":CREATED_MFHD_RECORD": "Created MFHD record for ${0}",
    ":EDIT_MFHD_RECORD": "Modificar la not\u00edcia",
    ":HOLD_STATUS_SINGULAR": "hold # ${0} of ${1} total holds and ${2} potential item",
    ":EDIT_MFHD_MENU": "Edit Holdings",
    ":EDIT_PROPERTIES": "Edit Properties",
    ":PWD_RESET_FORGOT_PROMPT": "Senhal doblidat\u00a0?",
    ":MISSING_VOLUMES": "Volums mancants",
    ":PWD_RESET_SUBMIT_PROMPT": "To begin the password reset process, enter either your barcode or user name in the form below and click 'Submit'",
    ":HOLD_STATUS_PLURAL": "hold # ${0} of ${1} total holds and ${2} potential items",
    ":PWD_RESET_FORM_TITLE": "Request password reset",
    ":PLACE_HOLD": "Place hold",
    ":BARCODE_PROMPT": "Barcode: ",
    ":INCOMPLETE_VOLUMES": "Volums incomplets",
    ":INDEX_HOLDINGS": "Ind\u00e8xes",
    ":CURRENT_INDEXES": "ind\u00e8x corrent",
    ":SOURCE_CANNOT_HAVE_COPIES": "Records from ${0} cannot have copies.",
    ":DELETE_MFHD": "Suprimir la not\u00edcia",
    ":PWD_RESET_RESPONSE_TITLE": "Password reset response",
    ":CURRENT_SUPPLEMENTS": "Suplements actuals",
    ":INDEX_HOLDINGS_ADD": "Additional Index Information",
    ":USERNAME_PROMPT": "User name: ",
    ":SUPPLEMENT_HOLDINGS": "Suplements",
    ":ONLINE_VOLUMES": "Volums en linha",
    ":PWD_RESET_SUBMIT_STATUS": "Sending request...",
    ":SUPPLEMENT_HOLDINGS_ADD": "Informacion suplement\u00e0ria",
    ":BASIC_HOLDINGS": "Volums",
    ":DELETED_MFHD_RECORD": "Deleted MFHD record ${0}",
    ":HOLDINGS_TABLE_CAPTION": "Holdings summary (${0})"
}