{
    ":CREATE_MFHD": "A\u00f1adir registro MFFHD",
    ":OK": "Aceptar",
    ":DELETE_MFHD_CONFIRM": "\u00bfEsta seguro de que desea borrar el registro de serie?",
    ":CANCEL_BUTTON_LABEL": "Cancelar",
    ":SUBMIT_BUTTON_LABEL": "Presentar",
    ":BASIC_HOLDINGS_ADD": "Informaci\u00f3n adicional del volumen",
    ":PWD_RESET_SUBMIT_ERROR": "El sistema no pudo procesar su solicitud para el restablecimiento de su contrase\u00f1a. Por favor intente de nuevo, o contacte personal de circulaci\u00f3n por asistencia.",
    ":PWD_RESET_SUBMIT_SUCCESS": "Su solicitud para iniciar el proceso de reinicializacion de contrase\u00f1a a sido procesado. Si su cuenta tiene una direcci\u00f3n de correo electr\u00f3nico v\u00e1lida, usted debe recibir un correo electr\u00f3nico que contiene m\u00e1s instrucciones para reinicializar su contrase\u00f1a.",
    ":SAVE_MFHD_LABEL": "Guardar MFHD",
    ":CURRENT_HOLDINGS": "Volumen actual",
    ":MORE": "M\u00e1s",
    ":MORE_COPIES_FULL_RECORD": "... m\u00e1s copias que estan listadas en todo el registro",
    ":CREATED_MFHD_RECORD": "Se cre\u00f3 un registro MFHD para ${0}",
    ":EDIT_MFHD_RECORD": "Editar registro",
    ":HOLD_STATUS_SINGULAR": "apartado # $(0) de $(1) apartados totales y $(2) ejemplar potencial",
    ":EDIT_MFHD_MENU": "Editar Explotaciones",
    ":EDIT_PROPERTIES": "Editar Propiedades",
    ":PWD_RESET_FORGOT_PROMPT": "Se le olvido la contrase\u00f1a?",
    ":MISSING_VOLUMES": "Vol\u00famenes faltantes",
    ":PWD_RESET_SUBMIT_PROMPT": "Para empezar el proceso de restablecer la contrase\u00f1a, ingrese su c\u00f3digo de barras o su nombre de usuario en el formulario debajo y haga clic en 'presentar'",
    ":HOLD_STATUS_PLURAL": "apartado # $(0) de $(1) apartados totales y $(2) ejemplares potenciales",
    ":PWD_RESET_FORM_TITLE": "Solicite restablecer la contrase\u00f1a",
    ":PLACE_HOLD": "Reservar",
    ":BARCODE_PROMPT": "C\u00f3digo de barras: ",
    ":INCOMPLETE_VOLUMES": "Vol\u00famenes Incompletos",
    ":INDEX_HOLDINGS": "\u00cdndices",
    ":CURRENT_INDEXES": "\u00cdndices actuales",
    ":SOURCE_CANNOT_HAVE_COPIES": "Registros desde ${0} no tienen copias.",
    ":DELETE_MFHD": "Eliminar registro",
    ":PWD_RESET_RESPONSE_TITLE": "Respuesta para el restablecimiento de la contrase\u00f1a",
    ":CURRENT_SUPPLEMENTS": "Suplementos actuales",
    ":INDEX_HOLDINGS_ADD": "Informaci\u00f3n adicional del \u00edndice",
    ":USERNAME_PROMPT": "Nombre de usuario: ",
    ":SUPPLEMENT_HOLDINGS": "Suplementos",
    ":ONLINE_VOLUMES": "Vol\u00famenes en l\u00ednea",
    ":PWD_RESET_SUBMIT_STATUS": "Enviando solicitud...",
    ":SUPPLEMENT_HOLDINGS_ADD": "Informaci\u00f3n adicional de suplemento",
    ":BASIC_HOLDINGS": "Vol\u00famenes",
    ":DELETED_MFHD_RECORD": "Eliminar registro MFHD ${0}",
    ":HOLDINGS_TABLE_CAPTION": "Resumen de las explotaciones (${0})"
}