{
    ":TFORMS_LABEL_SUM": "Soma",
    ":TEMPLATE_CONF_SELECT_CANCEL": "Select the value, or cancel:",
    ":TRANSFORMS_SUM": "Soma",
    ":TFORMS_LABEL_FIRST5": "First 5 characters (for US ZIP code)",
    ":TEMPLATE_CONF_DEFAULT": "Valor ${0} :",
    ":TRANSFORMS_MIN": "Min.",
    ":TRANSFORMS_DATE": "Data",
    ":OPERATORS_GT_EQUAL": "Superior o egal a",
    ":FILTERS_LABEL_EQUALS": "Egal",
    ":TFORMS_LABEL_MIN": "Min.",
    ":OPERATORS_LTE_TIME": "Fins al (Data / ora)",
    ":TFORMS_LABEL_DOY": "Jorn de l'annada",
    ":TRANSFORMS_AGE": "Edat",
    ":FILTERS_LABEL_NE_ANY": "Correspond a cap",
    ":TFORMS_LABEL_DOW": "Jorn de la setmana",
    ":FILTERS_LABEL_LT_TIME": "Abans (Data/Ora)",
    ":OPERATORS_EQ_ANY": "Egala",
    ":FOLDER_WINDOW_COLNAME_ALL": "Totes",
    ":LINK_NULLABLE_NONE": "Pas cap",
    ":FILTERS_LABEL_GT_EQUAL": "Superior o egal a",
    ":RPT_BUILDER_CONFIRM_SAVE": "Nom : ${0}\nDescripcion: ${1}\nEnregistrar lo mod\u00e8l ?",
    ":TRANSFORMS_ROUND": "Arredondir",
    ":TFORMS_LABEL_RAW_DATA": "Donadas originalas",
    ":OPERATORS_NULL_BLANK": "Es NULL o void",
    ":OPERATORS_EQUALS": "Egal",
    ":FOLDER_WINDOW_REPORT_OUTPUT": "Sortida del rap\u00f2rt : ${0}",
    ":TEMPLATE_CONF_CONFIRM_STATE": "Click OK for TRUE and Cancel for FALSE.",
    ":TFORMS_LABEL_AGE": "Edat",
    ":TEMPLATE_CONF_EQUALS": "Egal",
    ":TRANSFORMS_DAY_NAME": "Nom del jorn",
    ":REPORT_EDITOR_REPORT_FOLDERS": "Report Folders",
    ":FILTERS_LABEL_LSE_TIME": "Fins al (Data / ora)",
    ":FILTERS_LABEL_NOT_BETWEEN": "Pas entre",
    ":TRANSFORMS_MAX": "Max.",
    ":TFORMS_LABEL_HOD": "Ora",
    ":TRANSFORMS_YEAR_TRUNC": "Annada",
    ":TFORMS_LABEL_COUNT_DISTINCT": "Calcul distincte",
    ":TFORMS_LABEL_DAY_NAME": "Nom del jorn",
    ":TEMPLATE_CONF_CONFIRM_SAVE": "Nom : ${0}\nDescripcion: ${1}\nEnregistrar lo mod\u00e8l ?",
    ":TEMPLATE_CONF_NO_MATCH": "Field does not match one of list (comma separated):",
    ":OPERATORS_LESS_THAN": "Inferior a",
    ":FOLDERS_TEMPLATES": "Mod\u00e8ls",
    ":OPERATORS_NOT_BETWEEN": "Pas entre",
    ":TFORMS_LABEL_MAX": "Max.",
    ":FILTERS_LABEL_GTE_TIME": "Fins al (Data / ora)",
    ":TFORMS_LABEL_MONTH_TRUNC": "Annada + Mes",
    ":TRANSFORMS_DOM": "Jorn del mes",
    ":WIDGET_YEARS": "Annada(s)",
    ":OPERATORS_GT_TIME": "Apr\u00e8p (Data/Ora)",
    ":TFORMS_LABEL_QUARTERS_AGO": "Quarters ago",
    ":TRANSFORMS_DOW": "Jorn de la setmana",
    ":TEMPLATE_CONF_IN": "Field matches one of list (comma separated):",
    ":LINK_NULLABLE_DEFAULT": "Valor per defaut",
    ":OPERATORS_NOT_NULL_BLANK": "Es pas NULL o void",
    ":WIDGET_QUARTERS": "Trim\u00e8stre(s)",
    ":TRANSFORMS_DOY": "Jorn de l'annada",
    ":FILTERS_LABEL_NOT_IN": "Pas dins la lista",
    ":TRANSFORMS_QOY": "Trim\u00e8stre",
    ":FOLDER_WINDOW_COLNAME_SELECT": "Seleccionar",
    ":OPERATORS_IS_NOT_NULL": "Es pas NULL",
    ":TFORMS_LABEL_LAST": "Darri\u00e8ra valor",
    ":SOURCE_BROWSE_AGGREGATE": "Aggregate",
    ":TRANSFORMS_LAST": "Darri\u00e8ra valor",
    ":TFORMS_LABEL_WOY": "Setmana de l'annada",
    ":TEMPLATE_CONF_BARE": "Void",
    ":FOLDER_WINDOW_CHANGE_FOLDERS": "Change Folders",
    ":FILTERS_LABEL_NULL_BLANK": "Es NULL o void",
    ":OPERATORS_NE_ANY": "Correspond a cap",
    ":REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Please provide an output folder",
    ":SOURCE_BROWSE_NON_AGGREGATE": "Non-Aggregate",
    ":TRANSFORMS_COUNT_DISTINCT": "Calcul distincte",
    ":TRANSFORMS_FIRST": "Primi\u00e8ra valor",
    ":TEMPLATE_CONF_SUCCESS_SAVE": "Template ${0} was successfully saved.",
    ":FILTERS_LABEL_GT_TIME": "Apr\u00e8p (Data/Ora)",
    ":TRANSFORMS_QUARTERS_AGO": "Quarters ago",
    ":OPERATORS_LT_TIME": "Abans (Data/Ora)",
    ":TFORMS_LABEL_MONTH_NAME": "Nom del mes",
    ":TRANSFORMS_INT": "Drop trailing decimals",
    ":OPERATORS_LT_EQUAL": "Inferior o egal a",
    ":FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)",
    ":TRANSFORMS_MOY": "Mes de l'annada",
    ":FILTERS_LABEL_LESS_THAN": "Inferior a",
    ":FOLDERS_TEMPLATE": "Mod\u00e8l",
    ":FILTERS_LABEL_LIKE": "Contains Matching substring",
    ":TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string",
    ":OPERATORS_ILIKE": "Contains Matching substring (ignore case)",
    ":LINK_NULLABLE_RIGHT": "Parent",
    ":FILTERS_LABEL_LT_EQUAL": "Inferior o egal a",
    ":TRANSFORMS_SUBSTRING": "Soscadena",
    ":TRANSFORMS_MONTH_NAME": "Nom del mes",
    ":OPERATORS_IN_LIST": "Dins la lista",
    ":TFORMS_LABEL_AVERAGE": "Mejan",
    ":TRANSFORMS_LOWER": "Minusculas",
    ":FOLDERS_REPORT": "Rap\u00f2rt",
    ":TFORMS_LABEL_DOM": "Jorn del mes",
    ":FILTERS_LABEL_IN": "Dins la lista",
    ":TEMPLATE_CONF_RAW_DATA": "Donadas originalas",
    ":TFORMS_LABEL_DATE": "Data",
    ":TFORMS_LABEL_FIRST": "Primi\u00e8ra valor",
    ":TFORMS_LABEL_INT": "Drop trailing decimals",
    ":TFORMS_LABEL_UPPER": "Majusculas",
    ":TEMPLATE_CONF_TRUE": "Verai",
    ":TRANSFORMS_FIRST5": "First 5 characters (for US ZIP code)",
    ":TRANSFORMS_HOUR_TRUNC": "Ora",
    ":LINK_NULLABLE_LEFT": "Enfant",
    ":FILTERS_LABEL_NOT_NULL_BLANK": "Es pas NULL o void",
    ":TRANSFORMS_MONTHS_AGO": "Months ago",
    ":TRANSFORMS_HOD": "Ora",
    ":SOURCE_SETUP_CORE_SOURCES": "Fonts principalas",
    ":REPORT_EDITOR_INVALID_DATE_ALERT": "Data iniciala invalida - AAAA-MM-JJ",
    ":FOLDER_WINDOW_SELECT_ITEM": "Please select an item from the list",
    ":TRANSFORMS_AVERAGE": "Mejan",
    ":TFORMS_LABEL_LOWER": "Minusculas",
    ":OPERATORS_NOT_IN_LIST": "Pas dins la lista",
    ":TEMPLATE_CONF_NOT_IN": "Field does not match one of list (comma separated):",
    ":TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Change the field hint to:",
    ":OPERATORS_LIKE": "Contains Matching substring",
    ":FOLDER_WINDOW_COLNAME_NONE": "Pas cap",
    ":TFORMS_LABEL_MONTHS_AGO": "Months ago",
    ":TFORMS_LABEL_YEAR_TRUNC": "Annada",
    ":TRANSFORMS_UPPER": "Majusculas",
    ":OPERATORS_IS_NULL": "Es NULL",
    ":TFORMS_LABEL_COUNT": "Compte",
    ":FILTERS_LABEL_NOT_NULL": "Es pas NULL",
    ":WIDGET_MONTHS": "Mes(es)",
    ":TRANSFORMS_BARE": "Donadas originalas",
    ":WIDGET_REAL_DATE": "Data vertadi\u00e8ra",
    ":SOURCE_SETUP_ALL_AVAIL_SOURCES": "Totas las fonts disponiblas",
    ":OPERATORS_GTE_TIME": "Fins al (Data / ora)",
    ":REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Please change the report name",
    ":FILTERS_LABEL_GREATER_THAN": "Superior a",
    ":TFORMS_LABEL_MOY": "Mes de l'annada",
    ":FOLDERS_OUTPUT": "Fichi\u00e8r de destinacion",
    ":REPORT_EDITOR_OUTPUT_FOLDERS": "Output Folders",
    ":TEMPLATE_CONF_CONFIRM_RESET": "You have already added the [${0}] field\nfrom the [${1}] source. Click OK if you\nwould like to reset this field.",
    ":TRANSFORMS_FIRST_WORD": "First contiguous non-space string",
    ":FILTERS_LABEL_NULL": "Es NULL",
    ":REPORT_EDITOR_ENTER_NAME_ALERT": "Please enter a report name",
    ":WIDGET_RELATIVE_DATE": "Data relativa",
    ":TEMPLATE_CONF_BOOLEAN_VALUE": "Valor booleana",
    ":TEMPLATE_CONF_BETWEEN": "Field value is between (comma separated):",
    ":SOURCE_SETUP_CONFIRM_EXIT": "You have started building a template!\n Selecting a new starting source will destroy the current template and start over.  Is this OK?",
    ":FOLDERS_REPORTS": "Rap\u00f2rts",
    ":TFORMS_LABEL_HOUR_TRUNC": "Ora",
    ":FILTERS_LABEL_BETWEEN": "Entre",
    ":REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Please provide a report folder",
    ":TEMPLATE_CONF_FALSE": "Fals",
    ":TRANSFORMS_WOY": "Setmana de l'annada",
    ":OPERATORS_GREATER_THAN": "Superior a",
    ":TEMPLATE_CONF_NOT_BETWEEN": "Field value is not between (comma separated):",
    ":TRANSFORMS_MONTH_TRUNC": "Annada + Mes",
    ":TRANSFORMS_COUNT": "Compte",
    ":OPERATORS_BETWEEN": "Entre",
    ":WIDGET_DAYS": "Jorn(s)",
    ":FILTERS_LABEL_EQ_ANY": "Egala",
    ":TFORMS_LABEL_QOY": "Trim\u00e8stre",
    ":TFORMS_LABEL_ROUND": "Arredondir",
    ":TEMPLATE_CONF_PROMPT_CHANGE": "Change the column header to: ${0}"
}