{
    ":OPERATOR_GTE": "is greater than or equal to",
    ":ADD_ROW": "Add Row",
    ":DEFAULT_DIALOG_TITLE": "Filter Results",
    ":CANCEL": "Cancel",
    ":OPERATOR_EQ": "is",
    ":OPERATOR_GT": "is greater than",
    ":OPERATOR_IN": "is in the set",
    ":NEED_NAME": "You must enter a name for the saved filters.",
    ":OPERATOR_NOT_LIKE": "is not like",
    ":OPERATOR_LTE": "is less than or equal to",
    ":CHOOSE_FILTER_TO_LOAD": "Choose filter sets to load",
    ":EMPTY_CASE_COMPACT": "Add rows to filter results.",
    ":OPERATOR_IS_NULL": "is null",
    ":OPERATOR_LIKE": "is like",
    ":OPERATOR_BETWEEN": "is between",
    ":EMPTY_CASE": "Add rows to filter results, or just click Apply to see unfiltered results.",
    ":APPLY": "Apply",
    ":OPERATOR_NOT_IN": "is not in the set",
    ":OPERATOR_IS_NOT_NULL": "is not null",
    ":LOAD_FILTERS": "Load Filters",
    ":NAME_SAVED_FILTER_SET": "Enter a name for your saved filter set:",
    ":OPERATOR_NE": "is not",
    ":EMPTY_LIST": "Cannot compile search filter.  Empty lists not allowed.",
    ":SAVE_FILTERS": "Save Filters",
    ":OPERATOR_NOT_BETWEEN": "is not between",
    ":OPERATOR_LT": "is less than"
}