{
    ":CAPTURE_BRESV_DATES": "Tiempo de reservaci\u00f3n:",
    ":AUTHOR": "Autor",
    ":PRINTED_BY": "Imprimido por",
    ":TITLE": "T\u00edtulo",
    ":CAPTURE_CAUSES_TRANSIT": "Este art\u00edculo esta ahora en camino",
    ":AUTO_ATTR_VALUE_capture": "Tomar",
    ":CAPTURE_TRANSIT_SOURCE": "De:",
    ":BARCODE": "C\u00f3digo de barras",
    ":TRANSIT": "*** Tr\u00e1nsito ***",
    ":SUCCESS": "Toma \u00e9xitosa",
    ":CAPTURE_BRESV_PICKUP_LIB": "Biblioteca de recolecci\u00f3n:",
    ":DURATION": "Reservado de",
    ":HERES_WHAT_WE_KNOW": "La siguiente informaci\u00f3n es disponible de la toma fracasada:",
    ":AUTO_resource_barcode": "Ingrese el c\u00f3digo de barras:",
    ":NEEDS_ROUTED_TO": "Este art\u00edculo necesita ser enviado a",
    ":RESERVATION_SHELF": "ESTANTE DE RESERVA",
    ":PRINT": "<u>I</u>mprimir",
    ":CAPTURE_INFO": "Informaci\u00f3n de toma",
    ":NO_PAYLOAD": "Nosotros no recebimos m\u00e1s informaci\u00f3n de el servidor sobre este intento de toma.",
    ":CAPTURE_TRANSIT_DEST": "Para:",
    ":SLIP_DATE": "Fecha de noticia",
    ":AT": "a",
    ":CAPTURED_NOTHING": "No capturo nada.",
    ":RESERVED": "Reservado para el cliente",
    ":CAPTURE_BRESV_BRSRC": "C\u00f3digo de barras del recurso:",
    ":PRINT_ACCESSKEY": "P",
    ":AUTO_capture_heading": "Recursos Reservados de Toma",
    ":REQUEST": "Solicitar tiempo",
    ":UNKNOWN_PROBLEM": "Un problema desconocido se produjo durante el intento de toma",
    ":FAILURE": "Toma fracasada",
    ":AUTO_pickup_lib_selector": "Biblioteca de recolecci\u00f3n:"
}