{
    ":COPY_ALERT": "${0}:\n${1}\n\n\u00bfQuiere proceder de todos modos?",
    ":AUTO_patron": "Usuario",
    ":NO_PATRON_BARCODE": "Introduzca el c\u00f3digo de barras del usuario",
    ":RETURN_NO_RESPONSE": "No hay respuesta del servidor al intentar retorno.",
    ":ADDRESS": "${0}\n${1}\n${2}, ${3} ${4}",
    ":AUTO_no_in_bresv": "EL usuario no ha entregado ning\u00fan recurso el d\u00eda de hoy",
    ":AUTO_ready_bresv": "El usuario tiene estas reservaciones listas para ser recogidas:",
    ":AUTO_ATTR_VALUE_pickup": "Contestar",
    ":AUTO_resource": "Recurso",
    ":AUTO_in_bresv": "El usuario ha devuelto estos recursos el d\u00eda de hoy:",
    ":RETURN_SUCCESS": "Devoluci\u00f3n exitosa.",
    ":RESERVATIONS_ERROR": "Error comunicando con el servidor (pidiendo reservaciones):",
    ":AUTO_out_bresv": "Actualmente el usuario tiene estas reservaciones en su custodia:",
    ":NO_SUCH_RETURNABLE_RESOURCE": "No existe el recurso puede ser devuelta.",
    ":AUTO_no_ready_bresv": "En este momento el usuario no tiene reservaciones listas para recolecci\u00f3n.",
    ":AUTO_patron_barcode": "Introducir c\u00f3digo de barras del usuario:",
    ":AUTO_return_h1": "Devoluci\u00f3n de reservaciones",
    ":AUTO_ATTR_VALUE_return": "Enter",
    ":PICKUP_NO_RESPONSE": "No hay respuesta del servidor al intentar recogida.",
    ":RETURN_ERROR": "Error al comunicarse con el servidor (retorno de intentar):",
    ":PICKUP_ERROR": "Error comunicando con el servidor (intentando contestar):",
    ":RETURNABLE_RESOURCE_ERROR": "Error al buscar recursos retornables:",
    ":RESERVATIONS_NO_RESPONSE": "No hay respuesta del servidor cuando se le pide para hacer reservas.",
    ":AUTO_ATTR_VALUE_reset": "Limpiar / Nuevo usuario",
    ":SELECT_SOMETHING": "No ha seleccionado ninguna reservaci\u00f3n",
    ":AUTO_barcode_type": "Regresar por c\u00f3digo de barras de",
    ":AUTO_ATTR_VALUE_go": "Ir",
    ":NOTICE_CHANGE_OF_PATRON": "Tenga en cuenta que el recurso escaneada estaba en reserva a un diferente\npatr\u00f3n de \u00faltimo recurso ha sido escaneada. Si esto no es\nera de esperar, dejar de examinar las reservas pendientes para su patr\u00f3n\no en el recurso.",
    ":AUTO_no_out_bresv": "Patr\u00f3n no tiene m\u00e1s reservas a cabo en este momento.",
    ":AUTO_h1": "Reservas de recogida"
}