{
    ":CANCEL": "Zru\u0161it",
    ":MASTER_RECORD": "Hlavn\u00ed z\u00e1znam",
    ":CONFIRM_DELETE_RESULT": "Smaz\u00e1n autoritn\u00ed z\u00e1znam # ${0}",
    ":NONE_LINK": "Hodnota nezad\u00e1na",
    ":LINKED_BIBS": "Po\u010det p\u0159ipojen\u00fdch bibliografick\u00fdch z\u00e1znam\u016f: ${0}",
    ":AUTHORITY_FIELD_METADATA": "${3} (${1} \u2021${2}) ${4}",
    ":AUTHORITY_FIELDS": "Autoritn\u00ed pole (${0})",
    ":VIEW_MARC": "Zobrazit form\u00e1t MARC",
    ":CONFIRM_DELETE_PROMPT": "Potvrd\u0165e smaz\u00e1n\u00ed z\u00e1znamu # ${0}",
    ":MENU_MERGE": "Ozna\u010dit pro slou\u010den\u00ed",
    ":ACTIONS": "Akce",
    ":MENU_DELETE": "Smazat",
    ":DELETE": "Smazat",
    ":CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    ":MERGE_RESULT_SUCCESS": "Slou\u010den\u00ed z\u00e1znam\u016f je dokon\u010deno",
    ":SAVE_RESULT_SUCCESS": "Z\u00e1znam byl ulo\u017een.",
    ":SAVE": "Ulo\u017eit",
    ":HIDE_MARC": "Skr\u00fdt form\u00e1t MARC",
    ":CONFIRM_DELETE_TITLE": "Smazat autoritn\u00ed z\u00e1znam: \"${0}\"?",
    ":THESAURI": "Tesaurus (${0})",
    ":MENU_EDIT": "Upravit",
    ":TARGET_RECORD": "C\u00edl"
}