{
    ":TFORMS_LABEL_SUM": "Toplam",
    ":TEMPLATE_CONF_SELECT_CANCEL": "Select the value, or cancel:",
    ":TRANSFORMS_SUM": "Toplam",
    ":TFORMS_LABEL_FIRST5": "First 5 characters (for US ZIP code)",
    ":TEMPLATE_CONF_DEFAULT": "De\u011fer ${0}:",
    ":TRANSFORMS_MIN": "Min",
    ":TRANSFORMS_DATE": "Tarih",
    ":OPERATORS_GT_EQUAL": "B\u00fcy\u00fck veya e\u015fit",
    ":FILTERS_LABEL_EQUALS": "Equals",
    ":TFORMS_LABEL_MIN": "Min",
    ":OPERATORS_LTE_TIME": "On or Before (Date/Time)",
    ":TFORMS_LABEL_DOY": "Y\u0131l\u0131n G\u00fcn\u00fc",
    ":TRANSFORMS_AGE": "Ya\u015f",
    ":FILTERS_LABEL_NE_ANY": "Does Not Equal Any",
    ":TFORMS_LABEL_DOW": "Haftan\u0131n G\u00fcn\u00fc",
    ":FILTERS_LABEL_LT_TIME": "Before (Date/Time)",
    ":OPERATORS_EQ_ANY": "Equals Any",
    ":FOLDER_WINDOW_COLNAME_ALL": "T\u00fcm\u00fc",
    ":LINK_NULLABLE_NONE": "None",
    ":FILTERS_LABEL_GT_EQUAL": "B\u00fcy\u00fck veya e\u015fit",
    ":RPT_BUILDER_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?",
    ":TRANSFORMS_ROUND": "Round",
    ":TFORMS_LABEL_RAW_DATA": "Raw Data",
    ":OPERATORS_NULL_BLANK": "Is NULL or Blank",
    ":OPERATORS_EQUALS": "Equals",
    ":FOLDER_WINDOW_REPORT_OUTPUT": "Report Output: ${0}",
    ":TEMPLATE_CONF_CONFIRM_STATE": "Click OK for TRUE and Cancel for FALSE.",
    ":TFORMS_LABEL_AGE": "Ya\u015f",
    ":TEMPLATE_CONF_EQUALS": "Equals",
    ":TRANSFORMS_DAY_NAME": "G\u00fcn \u0130smi",
    ":REPORT_EDITOR_REPORT_FOLDERS": "Rapor Klas\u00f6rleri",
    ":FILTERS_LABEL_LSE_TIME": "On or Before (Date/Time)",
    ":FILTERS_LABEL_NOT_BETWEEN": "Not between",
    ":TRANSFORMS_MAX": "Max",
    ":TFORMS_LABEL_HOD": "G\u00fcn\u00fcn saati",
    ":TRANSFORMS_YEAR_TRUNC": "Y\u0131l",
    ":TFORMS_LABEL_COUNT_DISTINCT": "Count Distinct",
    ":TFORMS_LABEL_DAY_NAME": "G\u00fcn \u0130smi",
    ":TEMPLATE_CONF_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?",
    ":TEMPLATE_CONF_NO_MATCH": "Field does not match one of list (comma separated):",
    ":OPERATORS_LESS_THAN": "K\u00fc\u00e7\u00fckt\u00fcr",
    ":FOLDERS_TEMPLATES": "\u015eablonlar",
    ":OPERATORS_NOT_BETWEEN": "Not between",
    ":TFORMS_LABEL_MAX": "Max",
    ":FILTERS_LABEL_GTE_TIME": "On or After (Date/Time)",
    ":TFORMS_LABEL_MONTH_TRUNC": "Y\u0131l +Ay",
    ":TRANSFORMS_DOM": "Ay\u0131n G\u00fcn\u00fc",
    ":WIDGET_YEARS": "Y\u0131l(lar)",
    ":OPERATORS_GT_TIME": "After (Date/Time)",
    ":TFORMS_LABEL_QUARTERS_AGO": "Quarters ago",
    ":TRANSFORMS_DOW": "Haftan\u0131n G\u00fcn\u00fc",
    ":TEMPLATE_CONF_IN": "Field matches one of list (comma separated):",
    ":LINK_NULLABLE_DEFAULT": "Varsay\u0131lan",
    ":OPERATORS_NOT_NULL_BLANK": "Is not NULL or Blank",
    ":WIDGET_QUARTERS": "Quarter(s)",
    ":TRANSFORMS_DOY": "Y\u0131l\u0131n G\u00fcn\u00fc",
    ":FILTERS_LABEL_NOT_IN": "Listede yok",
    ":TRANSFORMS_QOY": "Y\u0131l\u0131n \u00c7eyre\u011fi",
    ":FOLDER_WINDOW_COLNAME_SELECT": "Se\u00e7",
    ":OPERATORS_IS_NOT_NULL": "Is not NULL",
    ":TFORMS_LABEL_LAST": "Son De\u011fer",
    ":SOURCE_BROWSE_AGGREGATE": "Aggregate",
    ":TRANSFORMS_LAST": "Son De\u011fer",
    ":TFORMS_LABEL_WOY": "Y\u0131l\u0131n Haftas\u0131",
    ":TEMPLATE_CONF_BARE": "Bare",
    ":FOLDER_WINDOW_CHANGE_FOLDERS": "Klas\u00f6rleri De\u011fi\u015ftir",
    ":FILTERS_LABEL_NULL_BLANK": "Is NULL or Blank",
    ":OPERATORS_NE_ANY": "Does Not Equal Any",
    ":REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Please provide an output folder",
    ":SOURCE_BROWSE_NON_AGGREGATE": "Non-Aggregate",
    ":TRANSFORMS_COUNT_DISTINCT": "Count Distinct",
    ":TRANSFORMS_FIRST": "\u0130lk De\u011fer",
    ":TEMPLATE_CONF_SUCCESS_SAVE": "Template ${0} was successfully saved.",
    ":FILTERS_LABEL_GT_TIME": "After (Date/Time)",
    ":TRANSFORMS_QUARTERS_AGO": "Quarters ago",
    ":OPERATORS_LT_TIME": "Before (Date/Time)",
    ":TFORMS_LABEL_MONTH_NAME": "Ay ismi",
    ":TRANSFORMS_INT": "Drop trailing decimals",
    ":OPERATORS_LT_EQUAL": "B\u00fcy\u00fck veya e\u015fit",
    ":FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)",
    ":TRANSFORMS_MOY": "Y\u0131l\u0131n Ay\u0131",
    ":FILTERS_LABEL_LESS_THAN": "K\u00fc\u00e7\u00fckt\u00fcr",
    ":FOLDERS_TEMPLATE": "\u015eablon",
    ":FILTERS_LABEL_LIKE": "Contains Matching substring",
    ":TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string",
    ":OPERATORS_ILIKE": "Contains Matching substring (ignore case)",
    ":LINK_NULLABLE_RIGHT": "Ana",
    ":FILTERS_LABEL_LT_EQUAL": "B\u00fcy\u00fck veya e\u015fit",
    ":TRANSFORMS_SUBSTRING": "Substring",
    ":TRANSFORMS_MONTH_NAME": "Ay Ad\u0131",
    ":OPERATORS_IN_LIST": "Listede",
    ":TFORMS_LABEL_AVERAGE": "Ortalama",
    ":TRANSFORMS_LOWER": "K\u00fc\u00e7\u00fck harf",
    ":FOLDERS_REPORT": "Rapor",
    ":TFORMS_LABEL_DOM": "Ay\u0131n G\u00fcn\u00fc",
    ":FILTERS_LABEL_IN": "Listede",
    ":TEMPLATE_CONF_RAW_DATA": "Raw Data",
    ":TFORMS_LABEL_DATE": "Tarih",
    ":TFORMS_LABEL_FIRST": "\u0130lk De\u011fer",
    ":TFORMS_LABEL_INT": "Drop trailing decimals",
    ":TFORMS_LABEL_UPPER": "B\u00fcy\u00fck harf",
    ":TEMPLATE_CONF_TRUE": "True",
    ":TRANSFORMS_FIRST5": "First 5 characters (for US ZIP code)",
    ":TRANSFORMS_HOUR_TRUNC": "Saat",
    ":LINK_NULLABLE_LEFT": "Child",
    ":FILTERS_LABEL_NOT_NULL_BLANK": "Is not NULL or Blank",
    ":TRANSFORMS_MONTHS_AGO": "Ay \u00f6nce",
    ":TRANSFORMS_HOD": "G\u00fcn\u00fcn saati",
    ":SOURCE_SETUP_CORE_SOURCES": "Core Sources",
    ":REPORT_EDITOR_INVALID_DATE_ALERT": "invalid start date -  YYYY-MM-DD",
    ":FOLDER_WINDOW_SELECT_ITEM": "L\u00fctfen listeden bir \u00f6\u011fe se\u00e7in",
    ":TRANSFORMS_AVERAGE": "Ortalama",
    ":TFORMS_LABEL_LOWER": "K\u00fc\u00e7\u00fck harf",
    ":OPERATORS_NOT_IN_LIST": "Listede yok",
    ":TEMPLATE_CONF_NOT_IN": "Field does not match one of list (comma separated):",
    ":TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Change the field hint to:",
    ":OPERATORS_LIKE": "Contains Matching substring",
    ":FOLDER_WINDOW_COLNAME_NONE": "None",
    ":TFORMS_LABEL_MONTHS_AGO": "Ay \u00f6nce",
    ":TFORMS_LABEL_YEAR_TRUNC": "Y\u0131l",
    ":TRANSFORMS_UPPER": "B\u00fcy\u00fck harf",
    ":OPERATORS_IS_NULL": "Is NULL",
    ":TFORMS_LABEL_COUNT": "Saya\u00e7",
    ":FILTERS_LABEL_NOT_NULL": "Is not NULL",
    ":WIDGET_MONTHS": "Ay(lar)",
    ":TRANSFORMS_BARE": "Raw Data",
    ":WIDGET_REAL_DATE": "Ger\u00e7ek Tarih",
    ":SOURCE_SETUP_ALL_AVAIL_SOURCES": "All Available Sources",
    ":OPERATORS_GTE_TIME": "On or After (Date/Time)",
    ":REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Please change the report name",
    ":FILTERS_LABEL_GREATER_THAN": "B\u00fcy\u00fckt\u00fcr",
    ":TFORMS_LABEL_MOY": "Y\u0131l\u0131n Ay\u0131",
    ":FOLDERS_OUTPUT": "\u00c7\u0131kt\u0131",
    ":REPORT_EDITOR_OUTPUT_FOLDERS": "\u00c7\u0131kt\u0131 Klas\u00f6rleri",
    ":TEMPLATE_CONF_CONFIRM_RESET": "You have already added the [${0}] field\nfrom the [${1}] source. Click OK if you\nwould like to reset this field.",
    ":TRANSFORMS_FIRST_WORD": "First contiguous non-space string",
    ":FILTERS_LABEL_NULL": "Is NULL",
    ":REPORT_EDITOR_ENTER_NAME_ALERT": "L\u00fctfen bir rapor ismi yaz\u0131n\u0131z",
    ":WIDGET_RELATIVE_DATE": "Relative Date",
    ":TEMPLATE_CONF_BOOLEAN_VALUE": "Boolean Value",
    ":TEMPLATE_CONF_BETWEEN": "Field value is between (comma separated):",
    ":SOURCE_SETUP_CONFIRM_EXIT": "You have started building a template!\n Selecting a new starting source will destroy the current template and start over.  Is this OK?",
    ":FOLDERS_REPORTS": "Raporlar",
    ":TFORMS_LABEL_HOUR_TRUNC": "Saat",
    ":FILTERS_LABEL_BETWEEN": "Between",
    ":REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Please provide a report folder",
    ":TEMPLATE_CONF_FALSE": "False",
    ":TRANSFORMS_WOY": "Y\u0131l\u0131n Haftas\u0131",
    ":OPERATORS_GREATER_THAN": "B\u00fcy\u00fckt\u00fcr",
    ":TEMPLATE_CONF_NOT_BETWEEN": "Field value is not between (comma separated):",
    ":TRANSFORMS_MONTH_TRUNC": "Y\u0131l +Ay",
    ":TRANSFORMS_COUNT": "Saya\u00e7",
    ":OPERATORS_BETWEEN": "Between",
    ":WIDGET_DAYS": "G\u00fcn(ler)",
    ":FILTERS_LABEL_EQ_ANY": "Equals Any",
    ":TFORMS_LABEL_QOY": "Y\u0131l\u0131n \u00c7eyre\u011fi",
    ":TFORMS_LABEL_ROUND": "Round",
    ":TEMPLATE_CONF_PROMPT_CHANGE": "Kolon ba\u015fl\u0131\u011f\u0131n\u0131 ${0} olarak de\u011fi\u015ftir:"
}