{
    ":CREATE_MFHD": "enregistrement MFHD ajout\u00e9 pour ${0}",
    ":OK": "OK",
    ":DELETE_MFHD_CONFIRM": "\u00cates-vous s\u00fbr de vouloir supprimer cet enregistrement de s\u00e9rie?",
    ":CANCEL_BUTTON_LABEL": "Annuler",
    ":SUBMIT_BUTTON_LABEL": "Soumettre",
    ":BASIC_HOLDINGS_ADD": "Informations suppl\u00e9mentaires sur le volume",
    ":PWD_RESET_SUBMIT_ERROR": "Le syst\u00e8me n'a pas pu traiter votre demande de r\u00e9initialisation du mot de passe. S'il vous pla\u00eet essayez de nouveau, ou contactez le personnel d'aide pratique.",
    ":PWD_RESET_SUBMIT_SUCCESS": "Votre demande de r\u00e9initialisation du mot de passe a \u00e9t\u00e9 trait\u00e9e. Si une adresse de courriel valide est associ\u00e9e \u00e0 votre compte, vous devriez recevoir sous peu un message contenant les instructions permettant la r\u00e9initialisation de votre mot de passe.",
    ":SAVE_MFHD_LABEL": "Sauvegarder l'enregistrement MFHD",
    ":CURRENT_HOLDINGS": "Volume actuel",
    ":MORE": "Plus",
    ":MORE_COPIES_FULL_RECORD": "...plus de copies \u00e9num\u00e9r\u00e9s dans l'enregistrement complet",
    ":CREATED_MFHD_RECORD": "enregistrement MFHD cr\u00e9\u00e9 pour ${0}",
    ":EDIT_MFHD_RECORD": "Modifier la notice",
    ":HOLD_STATUS_SINGULAR": "hold # ${0} of ${1} total holds and ${2} potential item",
    ":EDIT_MFHD_MENU": "Modifier fonds",
    ":EDIT_PROPERTIES": "Editer les propri\u00e9t\u00e9s",
    ":PWD_RESET_FORGOT_PROMPT": "Mot de passe oubli\u00e9 ?",
    ":MISSING_VOLUMES": "Volumes manquants",
    ":PWD_RESET_SUBMIT_PROMPT": "Pour d\u00e9buter le processus de renouvellement du mot de passe, indiquez votre code-barres ou votre nom d'utilisateur dans le formulaire ci-dessous et cliquez sur \u00ab Soumettre \u00bb.",
    ":HOLD_STATUS_PLURAL": "hold # ${0} of ${1} total holds and ${2} potential items",
    ":PWD_RESET_FORM_TITLE": "Demander un nouveau mot de passe",
    ":PLACE_HOLD": "R\u00e9serv\u00e9",
    ":BARCODE_PROMPT": "Code-barres : ",
    ":INCOMPLETE_VOLUMES": "Volumes incomplets",
    ":INDEX_HOLDINGS": "Index",
    ":CURRENT_INDEXES": "index courant",
    ":SOURCE_CANNOT_HAVE_COPIES": "Les enregistrements de ${0} ne peuvent pas avoir de copies.",
    ":DELETE_MFHD": "Supprimer la notice",
    ":PWD_RESET_RESPONSE_TITLE": "R\u00e9ponse de r\u00e9initialisation du mot de passe",
    ":CURRENT_SUPPLEMENTS": "Suppl\u00e9ments actuels",
    ":INDEX_HOLDINGS_ADD": "Informations suppl\u00e9mentaires sur l'index",
    ":USERNAME_PROMPT": "Nom d'utilisateur : ",
    ":SUPPLEMENT_HOLDINGS": "Suppl\u00e9ments",
    ":ONLINE_VOLUMES": "Volumes en ligne",
    ":PWD_RESET_SUBMIT_STATUS": "Envoi de la demande...",
    ":SUPPLEMENT_HOLDINGS_ADD": "Information suppl\u00e9mentaire",
    ":BASIC_HOLDINGS": "Volumes",
    ":DELETED_MFHD_RECORD": "Supprimer l'enregistrement MFHD ${0}",
    ":HOLDINGS_TABLE_CAPTION": "Sommaire de fonds (${0})"
}