{
    ":CREATE_MFHD": "MHFD Kayd\u0131 Ekle",
    ":OK": "OK",
    ":DELETE_MFHD_CONFIRM": "Bu seri kayd\u0131 silmek istedi\u011finizden emin m\u0131s\u0131n\u0131z?",
    ":CANCEL_BUTTON_LABEL": "Cancel",
    ":SUBMIT_BUTTON_LABEL": "Submit",
    ":BASIC_HOLDINGS_ADD": "Additional Volume Information",
    ":PWD_RESET_SUBMIT_ERROR": "The system could not process your request for a password reset. Please try again, or contact circulation staff for assistance.",
    ":PWD_RESET_SUBMIT_SUCCESS": "Parola s\u0131f\u0131rlama i\u015flemine ba\u015flamak i\u00e7in iste\u011finiz i\u015flendi. Hesab\u0131n\u0131z\u0131n ge\u00e7erli bir e-posta adresi varsa, yak\u0131nda \u015fifrenizi s\u0131f\u0131rlamak i\u00e7in ayr\u0131nt\u0131l\u0131 talimatlar i\u00e7eren bir e-posta almak gerekir.",
    ":SAVE_MFHD_LABEL": "MFHD Kaydet",
    ":CURRENT_HOLDINGS": "Ge\u00e7erli cilt",
    ":MORE": "More",
    ":MORE_COPIES_FULL_RECORD": "... more copies listed in full record",
    ":CREATED_MFHD_RECORD": "${0} \u0130\u00e7in MHFD Kay\u0131tlar\u0131",
    ":EDIT_MFHD_RECORD": "Kay\u0131tlar\u0131 De\u011fi\u015ftir",
    ":HOLD_STATUS_SINGULAR": "hold # ${0} of ${1} total holds and ${2} potential item",
    ":EDIT_MFHD_MENU": "Edit Holdings",
    ":EDIT_PROPERTIES": "\u00d6zellikleri D\u00fczenle",
    ":PWD_RESET_FORGOT_PROMPT": "Forgot your password?",
    ":MISSING_VOLUMES": "Eksik disk b\u00f6l\u00fcmleri",
    ":PWD_RESET_SUBMIT_PROMPT": "To begin the password reset process, enter either your barcode or user name in the form below and click 'Submit'",
    ":HOLD_STATUS_PLURAL": "hold # ${0} of ${1} total holds and ${2} potential items",
    ":PWD_RESET_FORM_TITLE": "\u015eifre s\u0131f\u0131rlama iste\u011fi",
    ":PLACE_HOLD": "Place hold",
    ":BARCODE_PROMPT": "barkod: ",
    ":INCOMPLETE_VOLUMES": "Incomplete volumes",
    ":INDEX_HOLDINGS": "Indexes",
    ":CURRENT_INDEXES": "g\u00fcncel indeksler",
    ":SOURCE_CANNOT_HAVE_COPIES": "Records from ${0} cannot have copies.",
    ":DELETE_MFHD": "Kayd\u0131 Sil",
    ":PWD_RESET_RESPONSE_TITLE": "Password reset response",
    ":CURRENT_SUPPLEMENTS": "Mevcut Eklentiler",
    ":INDEX_HOLDINGS_ADD": "Additional Index Information",
    ":USERNAME_PROMPT": "User name: ",
    ":SUPPLEMENT_HOLDINGS": "Takviyeler",
    ":ONLINE_VOLUMES": "Online volumes",
    ":PWD_RESET_SUBMIT_STATUS": "Sending request...",
    ":SUPPLEMENT_HOLDINGS_ADD": "Additional Supplement Information",
    ":BASIC_HOLDINGS": "Volumes",
    ":DELETED_MFHD_RECORD": "Silinmi\u015f MFHD kay\u0131t $ {0}",
    ":HOLDINGS_TABLE_CAPTION": "Holdings summary (${0})"
}