{
    ":DUPE_USERNAME": "K\u00e4ytt\u00e4j\u00e4tunnus on jo k\u00e4yt\u00f6ss\u00e4",
    ":SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    ":ALL_CARDS_ACTIVE": "Aktiivinen",
    ":REQUESTING_USER": "Tilin pyyt\u00e4j\u00e4: ${0} ${1}",
    ":RESET_PASSWORD": "Luo salasana",
    ":SHOW_REQUIRED": "N\u00e4yt\u00e4 vain vaaditut kent\u00e4t",
    ":DUPE_PATRON_EMAIL": "${0} asiakkaalla on sama s\u00e4hk\u00f6postiosoite",
    ":HOLD_NOTIFY_SMS": "SMS: ",
    ":DUPE_PATRON_PHONE": "${0} asiakkaalla on sama puhelinnumero",
    ":DUPE_PATRON_ADDR": "${0} asiakkaalla on sama osoite",
    ":SHOW_ALL": "N\u00e4yt\u00e4 kaikki kent\u00e4t",
    ":VERIFY_PASSWORD": "Vahvista salasana",
    ":EXAMPLE": "Esimerkki: ",
    ":USER_SETTINGS": "K\u00e4ytt\u00e4j\u00e4n asetukset",
    ":ADDRESS_MAILING": "Postitus",
    ":INVALID_FORM": "Muoto ei kelpaa. Muokkaa ja yrit\u00e4 uudelleen.",
    ":ADDRESS_BILLING": "Laskutus",
    ":PARENT_OR_GUARDIAN": "Vanhempi/huoltaja",
    ":SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    ":INVALIDATE": "Mit\u00e4t\u00f6i",
    ":UPDATE_EXPIRE_DATE": "Update Expire Date",
    ":DUPE_PATRON_NAME": "${0} asiakkaalla on sama nimi",
    ":SEE_ALL": "N\u00e4yt\u00e4 kaikki",
    ":ADDRESS_PENDING": "T\u00e4m\u00e4 on vireill\u00e4 oleva osoite: ",
    ":SAVE_CLONE": "Tallenna ja kloonaa",
    ":ADDRESS_HEADER": "Osoite",
    ":DELETE": "Delete",
    ":STAT_CATS": "Tilastolliset kategoriat",
    ":ALL_CARDS_BARCODE": "Asiakastunnus",
    ":HOLD_NOTIFY_EMAIL": "S\u00e4hk\u00f6posti: ",
    ":ADDRESS_OWNED": "Osoitteen omistaa toinen k\u00e4ytt\u00e4j\u00e4: ",
    ":HOLD_NOTIFY_PHONE": "Puhelin: ",
    ":REPLACE_BARCODE": "Korvaa asiakastunnus",
    ":SHOW_SUGGESTED": "N\u00e4yt\u00e4 ehdotetut kent\u00e4t",
    ":ADD": "Add",
    ":SAVE": "Tallenna",
    ":REPLACED_ADDRESS": "Korvaa osoitteen ${0}<br/> ${1} ${2}<br/> ${3}, ${4} ${5}",
    ":BARCODE_IN_USE": "Asiakastunnus on jo k\u00e4yt\u00f6ss\u00e4",
    ":SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    ":DEFAULT_ADDRESS_TYPE": "POSTITUS",
    ":NEED_ADDRESS": "Osoite vaaditaan rekister\u00f6ityess\u00e4.",
    ":SECONDARY_GROUP_ERROR": "Error saving secondary groups.",
    ":DUPE_PATRON_IDENT": "${0} asiakkaalla on sama tunnistautuminen",
    ":ALL_CARDS_APPLY": "Ota muutokset k\u00e4ytt\u00f6\u00f6n",
    ":ALL_CARDS_CLOSE": "Sulje",
    ":ADDRESS_APPROVE": "Hyv\u00e4ksy osoite",
    ":DELETE_ADDRESS": "Poistetaanko osoite ${0}?",
    ":ALL_CARDS_PRIMARY": "Ensisijainen",
    ":ADDRESS_NEW": "Uusi osoite"
}