{
    ":TFORMS_LABEL_SUM": "Soma",
    ":TEMPLATE_CONF_SELECT_CANCEL": "Selecione o valor, ou cancele:",
    ":TRANSFORMS_SUM": "Soma",
    ":TFORMS_LABEL_FIRST5": "Primeiros 5 caracteres (para CEP)",
    ":TEMPLATE_CONF_DEFAULT": "Valor ${0}:",
    ":TRANSFORMS_MIN": "Min",
    ":TRANSFORMS_DATE": "Data",
    ":OPERATORS_GT_EQUAL": "Maior ou igual a",
    ":FILTERS_LABEL_EQUALS": "Iguais",
    ":TFORMS_LABEL_MIN": "Min",
    ":OPERATORS_LTE_TIME": "Dentro ou Antes (Data/Hora)",
    ":TFORMS_LABEL_DOY": "Dia do Ano",
    ":TRANSFORMS_AGE": "Idade/Tempo",
    ":FILTERS_LABEL_NE_ANY": "N\u00e3o \u00e9 igual a nenhum",
    ":TFORMS_LABEL_DOW": "Dia da Semana",
    ":FILTERS_LABEL_LT_TIME": "Antes (Data/Hora)",
    ":OPERATORS_EQ_ANY": "Iguais a Qualquer",
    ":FOLDER_WINDOW_COLNAME_ALL": "Tudo",
    ":LINK_NULLABLE_NONE": "Nenhum",
    ":FILTERS_LABEL_GT_EQUAL": "Maior ou igual a",
    ":RPT_BUILDER_CONFIRM_SAVE": "Nome : ${0}\nDescri\u00e7\u00e3o: ${1}\nSalvar Modelo?",
    ":TRANSFORMS_ROUND": "Arredondamento",
    ":TFORMS_LABEL_RAW_DATA": "Dados puros",
    ":OPERATORS_NULL_BLANK": "\u00c9 NULO ou Branco",
    ":OPERATORS_EQUALS": "Iguais",
    ":FOLDER_WINDOW_REPORT_OUTPUT": "Relat\u00f3rio Gravado: {0}",
    ":TEMPLATE_CONF_CONFIRM_STATE": "Clique OK para VERDADEIRO ou Cancelar para FALSO",
    ":TFORMS_LABEL_AGE": "Idade/Tempo",
    ":TEMPLATE_CONF_EQUALS": "Iguais",
    ":TRANSFORMS_DAY_NAME": "Nome do Dia",
    ":REPORT_EDITOR_REPORT_FOLDERS": "Pastas de Relat\u00f3rio",
    ":FILTERS_LABEL_LSE_TIME": "Dentro ou Antes (Data/Hora)",
    ":FILTERS_LABEL_NOT_BETWEEN": "N\u00e3o Dentre",
    ":TRANSFORMS_MAX": "M\u00e1x",
    ":TFORMS_LABEL_HOD": "Hora do dia",
    ":TRANSFORMS_YEAR_TRUNC": "Ano",
    ":TFORMS_LABEL_COUNT_DISTINCT": "Qtde de Distintos",
    ":TFORMS_LABEL_DAY_NAME": "Nome do Dia",
    ":TEMPLATE_CONF_CONFIRM_SAVE": "Nome : ${0}\nDescri\u00e7\u00e3o: ${1}\nSalvar Modelo?",
    ":TEMPLATE_CONF_NO_MATCH": "Campo \u00e9 diferente a algum da lista (separados por virgulas):",
    ":OPERATORS_LESS_THAN": "Menor que",
    ":FOLDERS_TEMPLATES": "Modelos",
    ":OPERATORS_NOT_BETWEEN": "N\u00e3o Dentre",
    ":TFORMS_LABEL_MAX": "M\u00e1x",
    ":FILTERS_LABEL_GTE_TIME": "Dentro ou ap\u00f3s (Data/Hora)",
    ":TFORMS_LABEL_MONTH_TRUNC": "Ano + M\u00eas",
    ":TRANSFORMS_DOM": "Dia do M\u00eas",
    ":WIDGET_YEARS": "Ano(s)",
    ":OPERATORS_GT_TIME": "Depois (Data/Hora)",
    ":TFORMS_LABEL_QUARTERS_AGO": "Quadrimestres atr\u00e1s",
    ":TRANSFORMS_DOW": "Dia da Semana",
    ":TEMPLATE_CONF_IN": "Campo \u00e9 igual a algum da lista (separados por virgulas):",
    ":LINK_NULLABLE_DEFAULT": "Default",
    ":OPERATORS_NOT_NULL_BLANK": "N\u00e3o \u00e9 NULO ou Branco",
    ":WIDGET_QUARTERS": "Quadrimestre(s)",
    ":TRANSFORMS_DOY": "Dia do Ano",
    ":FILTERS_LABEL_NOT_IN": "Fora da lista",
    ":TRANSFORMS_QOY": "Quadrimestre",
    ":FOLDER_WINDOW_COLNAME_SELECT": "Selecione",
    ":OPERATORS_IS_NOT_NULL": "N\u00e3o \u00e9 NULO",
    ":TFORMS_LABEL_LAST": "\u00daltimo Valor",
    ":SOURCE_BROWSE_AGGREGATE": "Agregar",
    ":TRANSFORMS_LAST": "\u00daltimo Valor",
    ":TFORMS_LABEL_WOY": "Semana do Ano",
    ":TEMPLATE_CONF_BARE": "Puro",
    ":FOLDER_WINDOW_CHANGE_FOLDERS": "Alterar senha",
    ":FILTERS_LABEL_NULL_BLANK": "\u00c9 NULO ou Branco",
    ":OPERATORS_NE_ANY": "N\u00e3o \u00e9 igual a nenhum",
    ":REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Por favor informa uma pasa para grava\u00e7\u00e3o",
    ":SOURCE_BROWSE_NON_AGGREGATE": "N\u00e3o-Agregado",
    ":TRANSFORMS_COUNT_DISTINCT": "Qtde de Distintos",
    ":TRANSFORMS_FIRST": "Primeiro Valor",
    ":TEMPLATE_CONF_SUCCESS_SAVE": "O modelo ${0} foi salvo com sucesso.",
    ":FILTERS_LABEL_GT_TIME": "Depois (Data/Hora)",
    ":TRANSFORMS_QUARTERS_AGO": "Quadrimestres atr\u00e1s",
    ":OPERATORS_LT_TIME": "Antes (Data/Hora)",
    ":TFORMS_LABEL_MONTH_NAME": "Nome do M\u00eas'",
    ":TRANSFORMS_INT": "Descarta decimais",
    ":OPERATORS_LT_EQUAL": "Menor ou igual a",
    ":FILTERS_LABEL_ILIKE": "cont\u00e9m os subtextos iguais ao fornecido (ignorando mai\u00fasculas e min\u00fasculas)",
    ":TRANSFORMS_MOY": "M\u00eas do Ano",
    ":FILTERS_LABEL_LESS_THAN": "Menor que",
    ":FOLDERS_TEMPLATE": "Modelo",
    ":FILTERS_LABEL_LIKE": "cont\u00e9m os subtextos iguais ao fornecido",
    ":TFORMS_LABEL_FIRST_WORD": "Primeira sequ\u00eancia contigua de caracteres sem espa\u00e7o",
    ":OPERATORS_ILIKE": "cont\u00e9m os subtextos iguais ao fornecido (ignorando mai\u00fasculas e min\u00fasculas)",
    ":LINK_NULLABLE_RIGHT": "Pai",
    ":FILTERS_LABEL_LT_EQUAL": "Menor ou igual a",
    ":TRANSFORMS_SUBSTRING": "Subtexto",
    ":TRANSFORMS_MONTH_NAME": "Nome do M\u00eas",
    ":OPERATORS_IN_LIST": "Na lista",
    ":TFORMS_LABEL_AVERAGE": "M\u00e9dia",
    ":TRANSFORMS_LOWER": "Min\u00fasculas",
    ":FOLDERS_REPORT": "Relat\u00f3rio",
    ":TFORMS_LABEL_DOM": "Dia do M\u00eas",
    ":FILTERS_LABEL_IN": "Na lista",
    ":TEMPLATE_CONF_RAW_DATA": "Dados puros",
    ":TFORMS_LABEL_DATE": "Data",
    ":TFORMS_LABEL_FIRST": "Primeiro Valor",
    ":TFORMS_LABEL_INT": "Descarta decimais",
    ":TFORMS_LABEL_UPPER": "Mai\u00fasculas",
    ":TEMPLATE_CONF_TRUE": "Verdadeiro",
    ":TRANSFORMS_FIRST5": "Primeiros 5 caracteres (para CEP)",
    ":TRANSFORMS_HOUR_TRUNC": "Hora",
    ":LINK_NULLABLE_LEFT": "Crian\u00e7a",
    ":FILTERS_LABEL_NOT_NULL_BLANK": "N\u00e3o \u00e9 NULO ou Branco",
    ":TRANSFORMS_MONTHS_AGO": "Meses atr\u00e1s",
    ":TRANSFORMS_HOD": "Hora do dia",
    ":SOURCE_SETUP_CORE_SOURCES": "Fontes Principais",
    ":REPORT_EDITOR_INVALID_DATE_ALERT": "data de in\u00edcio inv\u00e1lida - AAAA-MM-DD",
    ":FOLDER_WINDOW_SELECT_ITEM": "Por favor selecione um item da lista",
    ":TRANSFORMS_AVERAGE": "M\u00e9dia",
    ":TFORMS_LABEL_LOWER": "Min\u00fasculas",
    ":OPERATORS_NOT_IN_LIST": "Fora da lista",
    ":TEMPLATE_CONF_NOT_IN": "Campo \u00e9 diferente a algum da lista (separados por virgulas):",
    ":TEMPLATE_FIELD_DOC_PROMPT_CHANGE": "Change the field hint to:",
    ":OPERATORS_LIKE": "cont\u00e9m os subtextos iguais ao fornecido",
    ":FOLDER_WINDOW_COLNAME_NONE": "Nenhum",
    ":TFORMS_LABEL_MONTHS_AGO": "Meses atr\u00e1s",
    ":TFORMS_LABEL_YEAR_TRUNC": "Ano",
    ":TRANSFORMS_UPPER": "Mai\u00fasculas",
    ":OPERATORS_IS_NULL": "\u00c9 Nulo",
    ":TFORMS_LABEL_COUNT": "Qtde",
    ":FILTERS_LABEL_NOT_NULL": "N\u00e3o \u00e9 NULO",
    ":WIDGET_MONTHS": "M\u00eas(es)",
    ":TRANSFORMS_BARE": "Dados puros",
    ":WIDGET_REAL_DATE": "Data Real",
    ":SOURCE_SETUP_ALL_AVAIL_SOURCES": "Todas Fontes Dispon\u00edveis",
    ":OPERATORS_GTE_TIME": "Dentro ou ap\u00f3s (Data/Hora)",
    ":REPORT_EDITOR_ENTER_NEW_NAME_ALERT": "Please change the report name",
    ":FILTERS_LABEL_GREATER_THAN": "Maior do que",
    ":TFORMS_LABEL_MOY": "M\u00eas do Ano",
    ":FOLDERS_OUTPUT": "Gravar em",
    ":REPORT_EDITOR_OUTPUT_FOLDERS": "Pastas de grava\u00e7\u00e3o",
    ":TEMPLATE_CONF_CONFIRM_RESET": "Voc\u00ea j\u00e1 incluiu o campo [${0}]\nda fonte [${1}]. Clique OK se voc\u00ea\ndeseja redefinir este campo.",
    ":TRANSFORMS_FIRST_WORD": "Primeira sequ\u00eancia contigua de caracteres sem espa\u00e7o",
    ":FILTERS_LABEL_NULL": "\u00c9 Nulo",
    ":REPORT_EDITOR_ENTER_NAME_ALERT": "Por favor entre com o nome do relat\u00f3rio",
    ":WIDGET_RELATIVE_DATE": "Data Relativa",
    ":TEMPLATE_CONF_BOOLEAN_VALUE": "Valor boleano",
    ":TEMPLATE_CONF_BETWEEN": "Valor do campo esta entre (separado por virgula):",
    ":SOURCE_SETUP_CONFIRM_EXIT": "Voc\u00ea iniciou a cria\u00e7\u00e3o de um modelo!\n Ao selecionar uma nova fonte ser\u00e1 destru\u00eddo o modelo atual e come\u00e7ar\u00e1 novamente. \u00c9 isto que DESEJA?",
    ":FOLDERS_REPORTS": "Relat\u00f3rios",
    ":TFORMS_LABEL_HOUR_TRUNC": "Hora",
    ":FILTERS_LABEL_BETWEEN": "Entre",
    ":REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Por favor informe a pasta para o relat\u00f3rio",
    ":TEMPLATE_CONF_FALSE": "Falso",
    ":TRANSFORMS_WOY": "Semana do Ano",
    ":OPERATORS_GREATER_THAN": "Maior do que",
    ":TEMPLATE_CONF_NOT_BETWEEN": "Valor do campo n\u00e3o esta entre (separado por virgula):",
    ":TRANSFORMS_MONTH_TRUNC": "Ano + M\u00eas",
    ":TRANSFORMS_COUNT": "Qtde",
    ":OPERATORS_BETWEEN": "Entre",
    ":WIDGET_DAYS": "Dia(s)",
    ":FILTERS_LABEL_EQ_ANY": "Iguais a Qualquer",
    ":TFORMS_LABEL_QOY": "Quadrimestre",
    ":TFORMS_LABEL_ROUND": "Arredondamento",
    ":TEMPLATE_CONF_PROMPT_CHANGE": "Alterar o cabe\u00e7alho da coluna para: $(0)"
}